/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file test_geir_bn_infer_grad.cpp
 * \brief BNInferGrad GEIR graph-mode example with numerical validation.
 */

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <ctime>
#include <iostream>
#include <map>
#include <string>
#include <vector>

#include "array_ops.h"
#include "ge_api.h"
#include "ge_api_types.h"
#include "ge_error_codes.h"
#include "ge_ir_build.h"
#include "graph.h"
#include "tensor.h"
#include "types.h"

#include "../op_graph/bn_infer_grad_proto.h"

#define FAILED -1
#define SUCCESS 0

using namespace ge;
using std::map;
using std::string;
using std::vector;

namespace {
constexpr float kEpsilon = 1.0F;
constexpr int64_t kBatchSize = 128;
constexpr int64_t kChannels = 3;
constexpr int64_t kHeight = 32;
constexpr int64_t kWidth = 32;
constexpr int64_t kInnerSize = kHeight * kWidth;
constexpr DataType kGradsDtype = DT_FLOAT16;
constexpr float kTolerance = 5.0e-3F;

vector<float> gGrads;
vector<float> gScale = {0.75F, -1.25F, 2.5F};
vector<float> gBatchVariance = {0.5F, 2.0F, 7.0F};
vector<uint16_t> gGradsStorage;

string GetTime()
{
    time_t timeValue;
    time(&timeValue);
    char buffer[64];
    strftime(buffer, sizeof(buffer), "%Y-%m-%d %H:%M:%S,000", localtime(&timeValue));
    return buffer;
}

uint16_t FloatToHalfBits(float value)
{
    uint32_t bits;
    std::memcpy(&bits, &value, sizeof(bits));
    const uint32_t sign = (bits >> 31) & 1U;
    const uint32_t exponent = (bits >> 23) & 0xFFU;
    const uint32_t mantissa = bits & 0x7FFFFFU;
    if (exponent == 0xFFU) {
        return static_cast<uint16_t>((sign << 15) | 0x7C00U | (mantissa == 0 ? 0U : 0x0200U));
    }
    const int32_t halfExponent = static_cast<int32_t>(exponent) - 127 + 15;
    if (halfExponent <= 0) {
        return static_cast<uint16_t>(sign << 15);
    }
    if (halfExponent >= 31) {
        return static_cast<uint16_t>((sign << 15) | 0x7C00U);
    }
    uint16_t result = static_cast<uint16_t>((sign << 15) | (static_cast<uint32_t>(halfExponent) << 10) |
                                            (mantissa >> 13));
    const uint32_t remainder = mantissa & 0x1FFFU;
    if (remainder > 0x1000U || (remainder == 0x1000U && (result & 1U) != 0U)) {
        ++result;
    }
    return result;
}

float HalfBitsToFloat(uint16_t value)
{
    const uint32_t sign = (value >> 15) & 1U;
    const uint32_t exponent = (value >> 10) & 0x1FU;
    const uint32_t mantissa = value & 0x03FFU;
    uint32_t bits;
    if (exponent == 0) {
        bits = sign << 31;
    } else if (exponent == 0x1FU) {
        bits = (sign << 31) | 0x7F800000U | (mantissa << 13);
    } else {
        bits = (sign << 31) | ((exponent - 15U + 127U) << 23) | (mantissa << 13);
    }
    float result;
    std::memcpy(&result, &bits, sizeof(result));
    return result;
}

void InitializeGradsStorage()
{
    const int64_t elementCount = kBatchSize * kChannels * kInnerSize;
    gGrads.clear();
    gGrads.reserve(elementCount);
    for (int64_t index = 0; index < elementCount; ++index) {
        gGrads.push_back(0.25F + static_cast<float>(index % 31) * 0.03125F);
    }

    gGradsStorage.clear();
    gGradsStorage.reserve(gGrads.size());
    for (float value : gGrads) {
        gGradsStorage.push_back(FloatToHalfBits(value));
    }
}

Tensor MakeFloatTensor(const vector<int64_t>& shape, vector<float>& data, TensorDesc& desc)
{
    desc = TensorDesc(Shape(shape), FORMAT_ND, DT_FLOAT);
    desc.SetPlacement(kPlacementHost);
    desc.SetFormat(FORMAT_ND);
    desc.SetOriginFormat(FORMAT_ND);
    desc.SetRealDimCnt(shape.size());
    return Tensor(desc, reinterpret_cast<uint8_t*>(data.data()), data.size() * sizeof(float));
}

Tensor MakeGradsTensor(const vector<int64_t>& shape, TensorDesc& desc)
{
    desc = TensorDesc(Shape(shape), FORMAT_NCHW, kGradsDtype);
    desc.SetPlacement(kPlacementHost);
    desc.SetFormat(FORMAT_NCHW);
    desc.SetOriginFormat(FORMAT_NCHW);
    desc.SetRealDimCnt(shape.size());
    return Tensor(desc, reinterpret_cast<uint8_t*>(gGradsStorage.data()), gGradsStorage.size() * sizeof(uint16_t));
}

int CreateGraph(vector<Tensor>& input, vector<Operator>& inputs, vector<Operator>& outputs, Graph& graph,
                const vector<int64_t>& scaleShape, const vector<int64_t>& varianceShape)
{
    auto bnInferGrad = op::BNInferGrad("bnInferGrad");
    // This shape exceeds one per-core UB tile on Ascend950. Each participating
    // core rereads the same channel-varying scale/variance broadcast inputs.
    const vector<int64_t> gradsShape = {kBatchSize, kChannels, kHeight, kWidth};

    TensorDesc gradsDesc;
    Tensor gradsTensor = MakeGradsTensor(gradsShape, gradsDesc);
    auto grads = op::Data("grads").set_attr_index(0);
    grads.update_input_desc_x(gradsDesc);
    grads.update_output_desc_y(gradsDesc);
    graph.AddOp(grads);
    bnInferGrad.set_input_grads(grads);
    input.push_back(gradsTensor);
    inputs.push_back(grads);

    TensorDesc scaleDesc;
    Tensor scaleTensor = MakeFloatTensor(scaleShape, gScale, scaleDesc);
    auto scale = op::Data("scale").set_attr_index(1);
    scale.update_input_desc_x(scaleDesc);
    scale.update_output_desc_y(scaleDesc);
    graph.AddOp(scale);
    bnInferGrad.set_input_scale(scale);
    input.push_back(scaleTensor);
    inputs.push_back(scale);

    TensorDesc varianceDesc;
    Tensor varianceTensor = MakeFloatTensor(varianceShape, gBatchVariance, varianceDesc);
    auto batchVariance = op::Data("batchVariance").set_attr_index(2);
    batchVariance.update_input_desc_x(varianceDesc);
    batchVariance.update_output_desc_y(varianceDesc);
    graph.AddOp(batchVariance);
    bnInferGrad.set_input_batch_variance(batchVariance);
    input.push_back(varianceTensor);
    inputs.push_back(batchVariance);

    TensorDesc outputDesc(Shape(gradsShape), FORMAT_NCHW, kGradsDtype);
    outputDesc.SetOriginFormat(FORMAT_NCHW);
    bnInferGrad.update_output_desc_x_backprop(outputDesc);
    bnInferGrad.set_attr_epsilon(kEpsilon);
    outputs.push_back(bnInferGrad);
    return SUCCESS;
}

bool ValidateOutput(const vector<Tensor>& output)
{
    if (output.size() != 1) {
        std::cerr << "Expected one output, got " << output.size() << std::endl;
        return false;
    }
    const Tensor& tensor = output[0];
    const int64_t count = tensor.GetTensorDesc().GetShape().GetShapeSize();
    if (count != static_cast<int64_t>(gGrads.size())) {
        std::cerr << "Unexpected output element count: " << count << std::endl;
        return false;
    }

    const uint16_t* result = reinterpret_cast<const uint16_t*>(tensor.GetData());
    bool valid = true;
    for (int64_t index = 0; index < count; ++index) {
        const int64_t channel = (index / kInnerSize) % kChannels;
        const float expected = gGrads[index] * gScale[channel] / std::sqrt(gBatchVariance[channel] + kEpsilon);
        const float actual = HalfBitsToFloat(result[index]);
        const float difference = std::fabs(actual - expected);
        if (difference > kTolerance) {
            std::cerr << "Mismatch at " << index << ": actual=" << actual << ", expected=" << expected
                      << ", diff=" << difference << std::endl;
            valid = false;
        }
    }
    return valid;
}

bool ValidateInvalidScaleRankRejected()
{
    Graph graph("bn_infer_grad_invalid_scale_rank");
    vector<Tensor> input;
    vector<Operator> inputs;
    vector<Operator> outputs;
    if (CreateGraph(input, inputs, outputs, graph, {1, kChannels}, {kChannels}) != SUCCESS) {
        return false;
    }
    graph.SetInputs(inputs).SetOutputs(outputs);

    map<AscendString, AscendString> sessionOptions;
    Session session(sessionOptions);
    const uint32_t graphId = 1;
    map<AscendString, AscendString> graphOptions;
    Status status = session.AddGraph(graphId, graph, graphOptions);
    if (status != SUCCESS) {
        return true;
    }
    vector<Tensor> output;
    return session.RunGraph(graphId, input, output) != SUCCESS;
}
} // namespace

int main()
{
    InitializeGradsStorage();
    Graph graph("bn_infer_grad_geir_example");
    vector<Tensor> input;
    vector<Operator> inputs;
    vector<Operator> outputs;

    map<AscendString, AscendString> globalOptions = {
        {"ge.exec.deviceId", "0"},
        {"ge.graphRunMode", "1"},
    };
    Status status = GEInitialize(globalOptions);
    if (status != SUCCESS) {
        std::cerr << GetTime() << " GEInitialize failed: " << status << std::endl;
        return FAILED;
    }

    if (CreateGraph(input, inputs, outputs, graph, {kChannels}, {kChannels}) != SUCCESS) {
        GEFinalize();
        return FAILED;
    }
    graph.SetInputs(inputs).SetOutputs(outputs);

    map<AscendString, AscendString> sessionOptions;
    Session session(sessionOptions);
    const uint32_t graphId = 0;
    map<AscendString, AscendString> graphOptions;
    status = session.AddGraph(graphId, graph, graphOptions);
    if (status != SUCCESS) {
        std::cerr << GetTime() << " AddGraph failed: " << status << std::endl;
        GEFinalize();
        return FAILED;
    }

    vector<Tensor> output;
    status = session.RunGraph(graphId, input, output);
    if (status != SUCCESS) {
        std::cerr << GetTime() << " RunGraph failed: " << status << std::endl;
        GEFinalize();
        return FAILED;
    }

    const bool valid = ValidateOutput(output);
    const bool invalidRankRejected = ValidateInvalidScaleRankRejected();
    status = GEFinalize();
    if (status != SUCCESS) {
        std::cerr << GetTime() << " GEFinalize failed: " << status << std::endl;
        return FAILED;
    }
    if (!valid) {
        std::cerr << "BNInferGrad FP16 GEIR numerical validation failed." << std::endl;
        return FAILED;
    }
    if (!invalidRankRejected) {
        std::cerr << "BNInferGrad invalid scale rank was not rejected." << std::endl;
        return FAILED;
    }
    std::cout << "Shape, dtype and values PASSED for [[128,3,32,32],[3],[3]]" << std::endl;
    std::cout << "BNInferGrad FP16 multi-core broadcast GEIR numerical validation passed; "
                 "invalid scale rank rejected."
              << std::endl;
    std::cout << "BNInferGrad static GEIR verification PASSED" << std::endl;
    return SUCCESS;
}
