/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file soft_margin_loss_grad_apt.cpp
 * \brief SoftMarginLossGrad 算子 kernel 入口（arch35 架构, RegBase Broadcast）
 *
 * 输入顺序: self(x), target(y), grad_output(grad)；RANK 来自 TilingKey, DTYPE 来自 self
 */
#include "kernel_operator.h"
#include "arch35/soft_margin_loss_grad.h"
#include "arch35/soft_margin_loss_grad_tiling_data.h"
#include "arch35/soft_margin_loss_grad_tiling_key.h"

using TilingData4 = SoftMarginLossGradTilingData<SMLG_RANK_4>;
using TilingData8 = SoftMarginLossGradTilingData<SMLG_RANK_8>;

template <int RANK>
__global__ __aicore__ void soft_margin_loss_grad(GM_ADDR self, GM_ADDR target, GM_ADDR grad_output, GM_ADDR out,
                                                 GM_ADDR workspace, GM_ADDR tiling)
{
    GM_ADDR ins[3] = {self, target, grad_output};
    GM_ADDR outs[1] = {out};
    REGISTER_NONE_TILING;
    KERNEL_TASK_TYPE_DEFAULT(KERNEL_TYPE_AIV_ONLY);
    if constexpr (RANK == SMLG_RANK_4) {
        GET_TILING_DATA_WITH_STRUCT(TilingData4, td, tiling);
        if (td.total_num == 0) {
            return;
        }
        SmlgKernel<DTYPE_PREDICT, SMLG_RANK_4> kernel;
        kernel.Init(ins, outs, &td);
        kernel.Process();
    } else {
        GET_TILING_DATA_WITH_STRUCT(TilingData8, td, tiling);
        if (td.total_num == 0) {
            return;
        }
        SmlgKernel<DTYPE_PREDICT, SMLG_RANK_8> kernel;
        kernel.Init(ins, outs, &td);
        kernel.Process();
    }
}
