/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file fused_bias_leaky_relu_tiling.cpp
 * \brief FusedBiasLeakyRelu Tiling implementation (arch35)
 */

#include "register/op_impl_registry.h"
#include "op_common/log/log.h"
#include "op_common/op_host/util/math_util.h"
#include "op_common/op_host/util/platform_util.h"
#include "op_common/op_host/tiling_base_util.h"
#include "../../op_kernel/arch35/fused_bias_leaky_relu_tiling_data.h"
#include "../../op_kernel/arch35/fused_bias_leaky_relu_tiling_key.h"

namespace optiling {

using Ops::Base::CeilAlign;
using Ops::Base::CeilDiv;
using Ops::Base::EnsureNotScalar;
using Ops::Base::FloorAlign;
using Ops::Base::FloorDiv;

constexpr uint32_t WS_SYS_SIZE = 0U;
constexpr int64_t TENSOR_NUM = 3;
constexpr int64_t FP16_CAST_BUF_NUM = 3; // xFp32, biasFp32, yFp32 for FP16 Cast path
constexpr int64_t BLOCK_ALIGN_BYTES = 32;
constexpr int64_t TYPE_SIZE_FP16 = 2;
constexpr int64_t TYPE_SIZE_FP32 = 4;
constexpr int64_t DOUBLE_BUFFER_THRESHOLD = 2;
constexpr int64_t DOUBLE_BUFFER_MULTIPLIER = 2;
constexpr float DEFAULT_NEGATIVE_SLOPE = 0.2f;
constexpr float DEFAULT_SCALE = 1.414213562373f;

static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t& ubSize, int64_t& coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus GetShapeAttrsInfo(gert::TilingContext* context, int64_t& totalNum, ge::DataType& dataType,
                                         float& negativeSlope, float& scale)
{
    constexpr int64_t MAX_DIM_NUM = 8;

    auto inputX = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputX);
    auto inputShapeX = EnsureNotScalar(inputX->GetStorageShape());

    OP_CHECK_IF(inputShapeX.GetDimNum() > MAX_DIM_NUM,
                OP_LOGE_FOR_INVALID_SHAPEDIM_WITH_REASON(context->GetNodeName(), "x",
                                                         std::to_string(inputShapeX.GetDimNum()).c_str(),
                                                         "The dim num of x must be less than or equal to 8"),
                return ge::GRAPH_FAILED);

    auto inputBias = context->GetInputShape(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputBias);
    auto inputShapeBias = EnsureNotScalar(inputBias->GetStorageShape());

    OP_CHECK_IF(inputShapeBias.GetDimNum() > MAX_DIM_NUM,
                OP_LOGE_FOR_INVALID_SHAPEDIM_WITH_REASON(context->GetNodeName(), "bias",
                                                         std::to_string(inputShapeBias.GetDimNum()).c_str(),
                                                         "The dim num of bias must be less than or equal to 8"),
                return ge::GRAPH_FAILED);

    auto outY = context->GetOutputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, outY);
    auto outShapeY = EnsureNotScalar(outY->GetStorageShape());

    OP_CHECK_IF(inputShapeX.GetShapeSize() != inputShapeBias.GetShapeSize() ||
                    inputShapeX.GetShapeSize() != outShapeY.GetShapeSize(),
                OP_LOGE(context, "FusedBiasLeakyRelu: shape size mismatch: x=%ld, bias=%ld, y=%ld",
                        inputShapeX.GetShapeSize(), inputShapeBias.GetShapeSize(), outShapeY.GetShapeSize()),
                return ge::GRAPH_FAILED);

    totalNum = inputShapeX.GetShapeSize();

    const std::set<ge::DataType> supportedDtype = {ge::DT_FLOAT16, ge::DT_FLOAT};
    auto inputDescX = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDescX);
    dataType = inputDescX->GetDataType();
    OP_CHECK_IF(supportedDtype.count(dataType) == 0,
                OP_LOGE_WITH_INVALID_INPUT_DTYPE(context->GetNodeName(), "x", Ops::Base::ToString(dataType).c_str(),
                                                 "DT_FLOAT16, DT_FLOAT"),
                return ge::GRAPH_FAILED);

    auto inputDescBias = context->GetInputDesc(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDescBias);
    auto biasDtype = inputDescBias->GetDataType();
    OP_CHECK_IF(supportedDtype.count(biasDtype) == 0,
                OP_LOGE_WITH_INVALID_INPUT_DTYPE(context->GetNodeName(), "bias", Ops::Base::ToString(biasDtype).c_str(),
                                                 "DT_FLOAT16, DT_FLOAT"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(biasDtype != dataType,
                OP_LOGE(context->GetNodeName(), "bias dtype %s must be same as x dtype %s",
                        Ops::Base::ToString(biasDtype).c_str(), Ops::Base::ToString(dataType).c_str()),
                return ge::GRAPH_FAILED);

    auto attrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, attrs);
    const float* pNegativeSlope = attrs->GetFloat(0);
    negativeSlope = (pNegativeSlope == nullptr) ? DEFAULT_NEGATIVE_SLOPE : *pNegativeSlope;
    const float* pScale = attrs->GetFloat(1);
    scale = (pScale == nullptr) ? DEFAULT_SCALE : *pScale;

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    size_t* currentWorkspace = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = WS_SYS_SIZE;
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus FusedBiasLeakyReluTilingFunc(gert::TilingContext* context)
{
    uint64_t ubSize;
    int64_t coreNum;
    OP_CHECK_IF(GetPlatformInfo(context, ubSize, coreNum) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetPlatformInfo error"), return ge::GRAPH_FAILED);

    int64_t totalNum;
    ge::DataType dataType;
    float negativeSlope;
    float scale;
    OP_CHECK_IF(GetShapeAttrsInfo(context, totalNum, dataType, negativeSlope, scale) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetShapeAttrsInfo error"), return ge::GRAPH_FAILED);

    OP_CHECK_IF(GetWorkspaceSize(context) != ge::GRAPH_SUCCESS, OP_LOGE(context, "GetWorkspaceSize error"),
                return ge::GRAPH_FAILED);

    FusedBiasLeakyReluTilingData* tiling = context->GetTilingData<FusedBiasLeakyReluTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(memset_s(tiling, sizeof(FusedBiasLeakyReluTilingData), 0, sizeof(FusedBiasLeakyReluTilingData)) != EOK,
                OP_LOGE(context, "set tiling data error"), return ge::GRAPH_FAILED);

    if (totalNum == 0) {
        tiling->totalNum = 0;
        tiling->blockFactor = 0;
        tiling->ubFactor = 0;
        tiling->negativeSlope = negativeSlope;
        tiling->scale = scale;
        context->SetBlockDim(1);
        ASCENDC_TPL_SEL_PARAM(context, static_cast<uint64_t>(0));
        return ge::GRAPH_SUCCESS;
    }

    int64_t typeSize = (dataType == ge::DT_FLOAT16) ? TYPE_SIZE_FP16 : TYPE_SIZE_FP32;
    int64_t ubBlockSize = BLOCK_ALIGN_BYTES / typeSize;

    int64_t blockFactor = CeilAlign(CeilDiv(totalNum, coreNum), ubBlockSize);
    int64_t usedCoreNum = CeilDiv(totalNum, blockFactor);

    // FP16 path needs extra Cast buffers (xFp32, biasFp32, yFp32) at FP32 size
    bool isFp16 = (dataType == ge::DT_FLOAT16);
    int64_t extraBuf = isFp16 ? FP16_CAST_BUF_NUM : 0;
    int64_t totalBufNum = TENSOR_NUM + extraBuf;

    int64_t loopCountIfDouble = CeilDiv(
        blockFactor, static_cast<int64_t>(ubSize) / typeSize / (totalBufNum * DOUBLE_BUFFER_MULTIPLIER));
    uint64_t useDoubleBuffer = (loopCountIfDouble >= DOUBLE_BUFFER_THRESHOLD) ? 1 : 0;

    // UB budget: TENSOR_NUM queue buffers (doubled if double buffer) + extraBuf cast bufs (single)
    int64_t queueBufNum = TENSOR_NUM * (useDoubleBuffer ? DOUBLE_BUFFER_MULTIPLIER : 1);
    int64_t ubFactor;
    if (isFp16) {
        // FP16: queue buffers × sizeof(half) + cast bufs × sizeof(float)
        // Queue buffers are doubled in double buffer mode; cast bufs (TBuf) are single
        int64_t bytesPerElem = queueBufNum * TYPE_SIZE_FP16 + FP16_CAST_BUF_NUM * TYPE_SIZE_FP32;
        ubFactor = FloorAlign(FloorDiv(static_cast<int64_t>(ubSize), bytesPerElem), ubBlockSize);
    } else {
        ubFactor = FloorAlign(FloorDiv(static_cast<int64_t>(ubSize) / typeSize, queueBufNum), ubBlockSize);
    }

    tiling->totalNum = totalNum;
    tiling->blockFactor = blockFactor;
    tiling->ubFactor = ubFactor;
    tiling->negativeSlope = negativeSlope;
    tiling->scale = scale;

    context->SetBlockDim(usedCoreNum);

    ASCENDC_TPL_SEL_PARAM(context, useDoubleBuffer);

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForFusedBiasLeakyRelu([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

struct FusedBiasLeakyReluCompileInfo {};

IMPL_OP_OPTILING(FusedBiasLeakyRelu)
    .Tiling(FusedBiasLeakyReluTilingFunc)
    .TilingParse<FusedBiasLeakyReluCompileInfo>(TilingParseForFusedBiasLeakyRelu);

} // namespace optiling
