/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* !
 * \file smooth_l1_loss_v2_tiling_key.h
 * \brief mseloss tiling key
 */

#ifndef _SMOOTH_L1_LOSS_V2_TILING_KEY_H_
#define _SMOOTH_L1_LOSS_V2_TILING_KEY_H_
#define REDUCTION_BIT_WIDTH 2
#define SMOOTHL1LOSSV2_SUM 1
#define SMOOTHL1LOSSV2_MEAN 2
#define SMOOTHL1LOSSV2_TPL_FP16 10
#define SMOOTHL1LOSSV2_TPL_FP32 20
#define SMOOTHL1LOSSV2_TPL_BFP16 30
#include "atvoss/reduce/reduce_tiling_key_decl.h"

ASCENDC_TPL_ARGS_DECL(SMOOTHL1LOSSV2, REDUCE_TPL_KEY_DECL(),
    ASCENDC_TPL_UINT_DECL(Reduction, REDUCTION_BIT_WIDTH, ASCENDC_TPL_UI_LIST, 0, SMOOTHL1LOSSV2_SUM, SMOOTHL1LOSSV2_MEAN),
    ASCENDC_TPL_UINT_DECL(Dtype, BIT_WIDTH, ASCENDC_TPL_UI_LIST, SMOOTHL1LOSSV2_TPL_FP16, SMOOTHL1LOSSV2_TPL_FP32, SMOOTHL1LOSSV2_TPL_BFP16));

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_EMPTY(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(Dtype, ASCENDC_TPL_UI_LIST, SMOOTHL1LOSSV2_TPL_FP16)),

    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_EMPTY(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(Dtype, ASCENDC_TPL_UI_LIST, SMOOTHL1LOSSV2_TPL_FP32)),

    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_EMPTY(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(Dtype, ASCENDC_TPL_UI_LIST, SMOOTHL1LOSSV2_TPL_BFP16)),

    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_EMPTY(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, SMOOTHL1LOSSV2_SUM, SMOOTHL1LOSSV2_MEAN),
        ASCENDC_TPL_UINT_SEL(Dtype, ASCENDC_TPL_UI_LIST, SMOOTHL1LOSSV2_TPL_FP32)),

    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_AR_NORMAL(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, SMOOTHL1LOSSV2_SUM, SMOOTHL1LOSSV2_MEAN),
        ASCENDC_TPL_UINT_SEL(Dtype, ASCENDC_TPL_UI_LIST, SMOOTHL1LOSSV2_TPL_FP32)),

    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_AR_GROUP(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, SMOOTHL1LOSSV2_SUM, SMOOTHL1LOSSV2_MEAN),
        ASCENDC_TPL_UINT_SEL(Dtype, ASCENDC_TPL_UI_LIST, SMOOTHL1LOSSV2_TPL_FP32)),

    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_A(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, SMOOTHL1LOSSV2_SUM, SMOOTHL1LOSSV2_MEAN),
        ASCENDC_TPL_UINT_SEL(Dtype, ASCENDC_TPL_UI_LIST, SMOOTHL1LOSSV2_TPL_FP32)));
#endif