/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file inplace_apply_proximal_adagrad_tiling_arch35.cpp
 * \brief InplaceApplyProximalAdagrad tiling (arch35).
 *
 * Tiling strategy fully reuses ApplyProximalAdagrad V1 (zero changes):
 *   1. Multi-core: split total elements evenly across AI vector cores.
 *   2. UB: ubFactor = floor((UB_size / 4B) / N) where N counts the per-element
 *   4-byte-unit footprint of all co-resident UB tensors.
 *
 * Def-driven dtype: DTYPE_VAR 由 def DataType 列表编译期注入，tiling 无需
 * 编码 dtype / padTail / hasL1 到 TilingKey。
 */

#include "register/op_def_registry.h"
#include "op_common/log/log.h"
#include "op_common/op_host/util/math_util.h"
#include "op_common/op_host/util/platform_util.h"
#include "atvoss/broadcast/broadcast_tiling.h"
#include "optim/inplace_apply_proximal_adagrad/op_kernel/arch35/inplace_apply_proximal_adagrad_tiling_data.h"

namespace optiling {

using Ops::Base::CeilAlign;
using Ops::Base::CeilDiv;
using Ops::Base::EnsureNotScalar;
using Ops::Base::FloorAlign;
using Ops::Base::FloorDiv;
using Ops::Base::GetUbBlockSize;

constexpr uint32_t WS_SYS_SIZE = 0U;
constexpr uint32_t IDX_VAR = 0;
constexpr uint32_t IDX_ACCUM = 1;
constexpr uint32_t IDX_LR = 2;
constexpr uint32_t IDX_L1 = 3;
constexpr uint32_t IDX_L2 = 4;
constexpr uint32_t IDX_GRAD = 5;
constexpr int64_t TILE_ELEM_NUM_TARGET = 2048;
constexpr int64_t UB_BUFFER_COUNT_FP32 = 14;
constexpr int64_t UB_BUFFER_COUNT_HALF = 12;
constexpr int64_t SIZE_FP32 = 4;
constexpr size_t MAX_DIM_NUM = 8;
constexpr int64_t SCALAR_ELEM_SIZE = 1;
constexpr int64_t EMPTY_BLOCK_DIM = 1;

static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t& ubSize, int64_t& coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus GetShapeInfo(gert::TilingContext* context, int64_t& totalElements, ge::DataType& dataType)
{
    const char* opName = context->GetNodeName();

    auto inputVar = context->GetInputShape(IDX_VAR);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputVar);
    auto varShape = EnsureNotScalar(inputVar->GetStorageShape());
    totalElements = varShape.GetShapeSize();

    OP_CHECK_IF(varShape.GetDimNum() > MAX_DIM_NUM,
                OP_LOGE_FOR_INVALID_SHAPEDIM_WITH_REASON(opName, "var", std::to_string(varShape.GetDimNum()).c_str(),
                                                         "The dim num of var must be less than or equal to 8"),
                return ge::GRAPH_FAILED);

    auto inputAccum = context->GetInputShape(IDX_ACCUM);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputAccum);
    auto accumShape = EnsureNotScalar(inputAccum->GetStorageShape());
    auto inputGrad = context->GetInputShape(IDX_GRAD);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputGrad);
    auto gradShape = EnsureNotScalar(inputGrad->GetStorageShape());
    if (varShape != accumShape || varShape != gradShape) {
        OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(opName, "var, accum, grad", "var, accum, grad",
                                               "var, accum, grad shapes must be identical");
        return ge::GRAPH_FAILED;
    }

    auto inputDesc = context->GetInputDesc(IDX_VAR);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
    dataType = inputDesc->GetDataType();

    auto varFormat = inputDesc->GetFormat().GetStorageFormat();
    OP_CHECK_IF(varFormat != ge::FORMAT_ND,
                OP_LOGE(opName, "var format must be ND, got %d", static_cast<int32_t>(varFormat)),
                return ge::GRAPH_FAILED);

    OP_CHECK_IF(dataType != ge::DT_FLOAT && dataType != ge::DT_FLOAT16 && dataType != ge::DT_BF16,
                OP_LOGE(context,
                        "InplaceApplyProximalAdagrad: only float32 / float16 / "
                        "bfloat16 are supported, got %d",
                        static_cast<int>(dataType)),
                return ge::GRAPH_FAILED);

    auto accumDesc = context->GetInputDesc(IDX_ACCUM);
    OP_CHECK_NULL_WITH_CONTEXT(context, accumDesc);
    if (accumDesc->GetDataType() != dataType) {
        OP_LOGE(opName, "accum dtype must match var");
        return ge::GRAPH_FAILED;
    }
    auto gradDesc = context->GetInputDesc(IDX_GRAD);
    OP_CHECK_NULL_WITH_CONTEXT(context, gradDesc);
    if (gradDesc->GetDataType() != dataType) {
        OP_LOGE(opName, "grad dtype must match var");
        return ge::GRAPH_FAILED;
    }

    for (uint32_t i = IDX_LR; i <= IDX_L2; ++i) {
        auto scalarDesc = context->GetInputDesc(i);
        OP_CHECK_NULL_WITH_CONTEXT(context, scalarDesc);
        if (scalarDesc->GetDataType() != dataType) {
            OP_LOGE(opName, "lr/l1/l2 dtype must match var");
            return ge::GRAPH_FAILED;
        }
        auto scalarShape = context->GetInputShape(i);
        OP_CHECK_NULL_WITH_CONTEXT(context, scalarShape);
        auto scalarStorageShape = scalarShape->GetStorageShape();
        if (!scalarStorageShape.IsScalar() && scalarStorageShape.GetShapeSize() != SCALAR_ELEM_SIZE) {
            const char* names[] = {nullptr, nullptr, "lr", "l1", "l2"};
            OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(opName, names[i], "not scalar", "lr/l1/l2 must be scalar or size=1");
            return ge::GRAPH_FAILED;
        }
    }

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    size_t* currentWorkspace = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = WS_SYS_SIZE;
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ComputeMultiCoreSplit(gert::TilingContext* context, int64_t totalElements, int64_t coreNum,
                                             int64_t& blockFactor, int64_t& usedCoreNum, int64_t& ubBlockSize)
{
    ubBlockSize = Ops::Base::GetUbBlockSize(context);
    OP_CHECK_IF(ubBlockSize <= 0, OP_LOGE(context, "invalid ubBlockSize=%ld", ubBlockSize), return ge::GRAPH_FAILED);

    blockFactor = CeilAlign(CeilDiv(totalElements, coreNum), ubBlockSize);
    usedCoreNum = CeilDiv(totalElements, blockFactor);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ComputeUbSplit(gert::TilingContext* context, uint64_t ubSize, ge::DataType dataType,
                                      int64_t blockFactor, int64_t ubBlockSize, int64_t& ubFactor)
{
    int64_t ubBufCount = (dataType == ge::DT_FLOAT) ? UB_BUFFER_COUNT_FP32 : UB_BUFFER_COUNT_HALF;
    int64_t perElemBytes = SIZE_FP32;

    int64_t ubCapacityElem = FloorAlign(FloorDiv(static_cast<int64_t>(ubSize) / perElemBytes, ubBufCount), ubBlockSize);
    OP_CHECK_IF(ubCapacityElem <= 0, OP_LOGE(context, "UB too small: ubCapacityElem=%ld", ubCapacityElem),
                return ge::GRAPH_FAILED);

    ubFactor = (TILE_ELEM_NUM_TARGET < ubCapacityElem) ? TILE_ELEM_NUM_TARGET : ubCapacityElem;

    if (ubFactor > blockFactor) {
        ubFactor = FloorAlign(blockFactor, ubBlockSize);
        if (ubFactor <= 0) {
            ubFactor = ubBlockSize;
        }
    }
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus FillTilingForNonEmpty(gert::TilingContext* context, int64_t totalElements, ge::DataType dataType,
                                             uint64_t ubSize, int64_t coreNum,
                                             InplaceApplyProximalAdagradTilingData* tiling)
{
    int64_t blockFactor = 0;
    int64_t usedCoreNum = 0;
    int64_t ubBlockSize = 0;
    OP_CHECK_IF(ComputeMultiCoreSplit(context, totalElements, coreNum, blockFactor, usedCoreNum, ubBlockSize) !=
                    ge::GRAPH_SUCCESS,
                OP_LOGE(context, "ComputeMultiCoreSplit error"), return ge::GRAPH_FAILED);

    int64_t ubFactor = 0;
    OP_CHECK_IF(ComputeUbSplit(context, ubSize, dataType, blockFactor, ubBlockSize, ubFactor) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "ComputeUbSplit error"), return ge::GRAPH_FAILED);

    tiling->blockFactor = blockFactor;
    tiling->ubFactor = ubFactor;
    context->SetBlockDim(usedCoreNum);

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus InplaceApplyProximalAdagradTilingFunc(gert::TilingContext* context)
{
    OP_LOGI(context->GetNodeName(), "Enter InplaceApplyProximalAdagradTilingFunc");
    uint64_t ubSize = 0;
    int64_t coreNum = 0;
    OP_CHECK_IF(GetPlatformInfo(context, ubSize, coreNum) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetPlatformInfo error"), return ge::GRAPH_FAILED);

    int64_t totalElements = 0;
    ge::DataType dataType = ge::DT_FLOAT;
    OP_CHECK_IF(GetShapeInfo(context, totalElements, dataType) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetShapeInfo error"), return ge::GRAPH_FAILED);

    OP_CHECK_IF(GetWorkspaceSize(context) != ge::GRAPH_SUCCESS, OP_LOGE(context, "GetWorkspaceSize error"),
                return ge::GRAPH_FAILED);

    InplaceApplyProximalAdagradTilingData* tiling = context->GetTilingData<InplaceApplyProximalAdagradTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(memset_s(tiling, sizeof(InplaceApplyProximalAdagradTilingData), 0,
                         sizeof(InplaceApplyProximalAdagradTilingData)) != EOK,
                OP_LOGE(context, "set tiling data error"), return ge::GRAPH_FAILED);

    tiling->totalElements = totalElements;

    if (totalElements == 0) {
        tiling->blockFactor = 0;
        tiling->ubFactor = 0;
        context->SetBlockDim(EMPTY_BLOCK_DIM);
        return ge::GRAPH_SUCCESS;
    }

    return FillTilingForNonEmpty(context, totalElements, dataType, ubSize, coreNum, tiling);
}

static ge::graphStatus TilingParseForInplaceApplyProximalAdagrad([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

struct InplaceApplyProximalAdagradCompileInfo {};

IMPL_OP_OPTILING(InplaceApplyProximalAdagrad)
    .Tiling(InplaceApplyProximalAdagradTilingFunc)
    .TilingParse<InplaceApplyProximalAdagradCompileInfo>(TilingParseForInplaceApplyProximalAdagrad);

} // namespace optiling
