/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include "inplace_scatter_add_tiling_key.h"
#include "inplace_scatter_add_simt.h"

template <uint32_t schMode>
__global__ __aicore__ void inplace_scatter_add(GM_ADDR var, GM_ADDR indices, GM_ADDR updates, GM_ADDR var_out,
                                               GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(InplaceScatterAddTilingData);
    GET_TILING_DATA_WITH_STRUCT(InplaceScatterAddTilingData, tilingData, tiling);
    NsInplaceScatterAdd::Process<DTYPE_VAR, DTYPE_INDICES>(var, indices, updates, &tilingData);
}
