/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#ifndef INPLACE_SCATTER_ADD_SIMT_H
#define INPLACE_SCATTER_ADD_SIMT_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "simt_api/common_functions.h"
#include "simt_api/device_atomic_functions.h"
#include "simt_api/device_warp_functions.h"
#include "simt_api/device_sync_functions.h"
#include "inplace_scatter_add_tiling_data.h"

namespace NsInplaceScatterAdd {

using namespace AscendC;

constexpr uint32_t THREAD_NUM = 1024;

// ============ N-split path: N >= K, split N across cores, each core handles all K ============

template <typename T, typename IDX_T>
__simt_vf__ __aicore__ __launch_bounds__(THREAD_NUM) inline void ScatterAddNSplit32(
    uint32_t M, uint32_t N, uint32_t K, uint32_t blockOffset, uint32_t blockLength, uint32_t magic, uint32_t shift,
    __gm__ T* var, __gm__ IDX_T* indices, __gm__ T* updates)
{
    uint32_t totalElements = K * blockLength;
    for (uint32_t i = threadIdx.x; i < totalElements; i += blockDim.x) {
        uint32_t k = Simt::UintDiv<uint32_t>(i, magic, shift);
        uint32_t colLocal = i - k * blockLength;
        uint32_t col = blockOffset + colLocal;
        if (col >= N) {
            continue;
        }
        IDX_T idx = indices[k];
        if (idx >= 0 && static_cast<uint64_t>(idx) < static_cast<uint64_t>(M)) {
            uint64_t varOffset = static_cast<uint64_t>(idx) * static_cast<uint64_t>(N) + col;
            uint64_t updOffset = static_cast<uint64_t>(k) * static_cast<uint64_t>(N) + col;
            asc_atomic_add(&var[varOffset], updates[updOffset]);
        }
    }
}

template <typename T, typename IDX_T>
__simt_vf__ __aicore__ __launch_bounds__(THREAD_NUM) inline void ScatterAddNSplit64(
    uint64_t M, uint64_t N, uint64_t K, uint64_t blockOffset, uint64_t blockLength, uint64_t magic, uint64_t shift,
    __gm__ T* var, __gm__ IDX_T* indices, __gm__ T* updates)
{
    uint64_t totalElements = K * blockLength;
    for (uint64_t i = static_cast<uint64_t>(threadIdx.x); i < totalElements; i += static_cast<uint64_t>(blockDim.x)) {
        uint64_t k = Simt::UintDiv<uint64_t>(i, magic, shift);
        uint64_t colLocal = i - k * blockLength;
        uint64_t col = blockOffset + colLocal;
        if (col >= N) {
            continue;
        }
        IDX_T idx = indices[k];
        if (idx >= 0 && static_cast<uint64_t>(idx) < M) {
            uint64_t varOffset = static_cast<uint64_t>(idx) * N + col;
            uint64_t updOffset = k * N + col;
            asc_atomic_add(&var[varOffset], updates[updOffset]);
        }
    }
}

// ============ K-split path: K > N, split K across cores, each core handles all N ============

template <typename T, typename IDX_T>
__simt_vf__ __aicore__ __launch_bounds__(THREAD_NUM) inline void ScatterAddKSplit32(
    uint32_t M, uint32_t N, uint32_t K, uint32_t blockOffset, uint32_t blockLength, uint32_t magic, uint32_t shift,
    __gm__ T* var, __gm__ IDX_T* indices, __gm__ T* updates)
{
    uint32_t totalElements = blockLength * N;
    for (uint32_t i = threadIdx.x; i < totalElements; i += blockDim.x) {
        uint32_t localRow = Simt::UintDiv<uint32_t>(i, magic, shift);
        uint32_t col = i - localRow * N;
        uint32_t globalRow = blockOffset + localRow;
        if (globalRow >= K) {
            break;
        }
        IDX_T idx = indices[globalRow];
        if (idx >= 0 && static_cast<uint64_t>(idx) < static_cast<uint64_t>(M)) {
            uint64_t varOffset = static_cast<uint64_t>(idx) * static_cast<uint64_t>(N) + col;
            uint64_t updOffset = static_cast<uint64_t>(globalRow) * static_cast<uint64_t>(N) + col;
            asc_atomic_add(&var[varOffset], updates[updOffset]);
        }
    }
}

template <typename T, typename IDX_T>
__simt_vf__ __aicore__ __launch_bounds__(THREAD_NUM) inline void ScatterAddKSplit64(
    uint64_t M, uint64_t N, uint64_t K, uint64_t blockOffset, uint64_t blockLength, uint64_t magic, uint64_t shift,
    __gm__ T* var, __gm__ IDX_T* indices, __gm__ T* updates)
{
    uint64_t totalElements = blockLength * N;
    for (uint64_t i = static_cast<uint64_t>(threadIdx.x); i < totalElements; i += static_cast<uint64_t>(blockDim.x)) {
        uint64_t localRow = Simt::UintDiv<uint64_t>(i, magic, shift);
        uint64_t col = i - localRow * N;
        uint64_t globalRow = blockOffset + localRow;
        if (globalRow >= K) {
            break;
        }
        IDX_T idx = indices[globalRow];
        if (idx >= 0 && static_cast<uint64_t>(idx) < M) {
            uint64_t varOffset = static_cast<uint64_t>(idx) * N + col;
            uint64_t updOffset = globalRow * N + col;
            asc_atomic_add(&var[varOffset], updates[updOffset]);
        }
    }
}

// ============ Entry ============

template <typename T, typename IDX_T>
__aicore__ inline void Process(GM_ADDR var, GM_ADDR indices, GM_ADDR updates,
                               const InplaceScatterAddTilingData* tilingData)
{
    int64_t M = tilingData->M;
    int64_t N = tilingData->N;
    int64_t K = tilingData->K;
    if (K == 0 || M == 0 || N == 0) {
        return;
    }

    uint32_t blockIdx = AscendC::GetBlockIdx();
    uint64_t blockLength = tilingData->blockLength;
    uint64_t blockOffset = blockLength * static_cast<uint64_t>(blockIdx);

    bool canUse32Bit = (M <= UINT32_MAX) && (N <= UINT32_MAX) && (K <= UINT32_MAX) && (blockOffset <= UINT32_MAX) &&
                       (blockLength <= UINT32_MAX);

    if (tilingData->splitAxis == 0) {
        // N-split: each core handles a slice of N, iterates all K
        if (blockOffset >= static_cast<uint64_t>(N)) {
            return;
        }
        uint64_t remain = blockLength;
        if (blockOffset + remain > static_cast<uint64_t>(N)) {
            remain = static_cast<uint64_t>(N) - blockOffset;
        }
        if (canUse32Bit) {
            uint32_t magic = 0, shift = 0;
            if (remain > 1) {
                GetUintDivMagicAndShift<uint32_t>(magic, shift, static_cast<uint32_t>(remain));
            }
            asc_vf_call<ScatterAddNSplit32<T, IDX_T>>(
                dim3(THREAD_NUM), static_cast<uint32_t>(M), static_cast<uint32_t>(N), static_cast<uint32_t>(K),
                static_cast<uint32_t>(blockOffset), static_cast<uint32_t>(remain), magic, shift, (__gm__ T*)var,
                (__gm__ IDX_T*)indices, (__gm__ T*)updates);
        } else {
            uint64_t magic = 0, shift = 0;
            if (remain > 1) {
                GetUintDivMagicAndShift<uint64_t>(magic, shift, remain);
            }
            asc_vf_call<ScatterAddNSplit64<T, IDX_T>>(dim3(THREAD_NUM), static_cast<uint64_t>(M),
                                                      static_cast<uint64_t>(N), static_cast<uint64_t>(K),
                                                      static_cast<uint64_t>(blockOffset), remain, magic, shift,
                                                      (__gm__ T*)var, (__gm__ IDX_T*)indices, (__gm__ T*)updates);
        }
    } else {
        // K-split: each core handles a slice of K, iterates all N
        if (blockOffset >= static_cast<uint64_t>(K)) {
            return;
        }
        uint64_t remain = blockLength;
        if (blockOffset + remain > static_cast<uint64_t>(K)) {
            remain = static_cast<uint64_t>(K) - blockOffset;
        }
        if (canUse32Bit) {
            uint32_t magic = 0, shift = 0;
            if (N > 1) {
                GetUintDivMagicAndShift<uint32_t>(magic, shift, static_cast<uint32_t>(N));
            }
            asc_vf_call<ScatterAddKSplit32<T, IDX_T>>(
                dim3(THREAD_NUM), static_cast<uint32_t>(M), static_cast<uint32_t>(N), static_cast<uint32_t>(K),
                static_cast<uint32_t>(blockOffset), static_cast<uint32_t>(remain), magic, shift, (__gm__ T*)var,
                (__gm__ IDX_T*)indices, (__gm__ T*)updates);
        } else {
            uint64_t magic = 0, shift = 0;
            if (N > 1) {
                GetUintDivMagicAndShift<uint64_t>(magic, shift, static_cast<uint64_t>(N));
            }
            asc_vf_call<ScatterAddKSplit64<T, IDX_T>>(
                dim3(THREAD_NUM), static_cast<uint64_t>(M), static_cast<uint64_t>(N), static_cast<uint64_t>(K),
                static_cast<uint64_t>(blockOffset), static_cast<uint64_t>(remain), magic, shift, (__gm__ T*)var,
                (__gm__ IDX_T*)indices, (__gm__ T*)updates);
        }
    }
}

} // namespace NsInplaceScatterAdd

#endif // INPLACE_SCATTER_ADD_SIMT_H
