/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file fused_bias_leaky_relu.cpp
 * \brief FusedBiasLeakyRelu kernel entry (arch35)
 *
 * dtype is driven by def file (DataType list → DTYPE_X macro).
 * TilingKey only encodes BUFFER_MODE.
 */

#include "arch35/fused_bias_leaky_relu.h"

template <int BUFFER_MODE>
__global__ __aicore__ void fused_bias_leaky_relu(GM_ADDR x, GM_ADDR bias, GM_ADDR y, GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(FusedBiasLeakyReluTilingData);
    GET_TILING_DATA_WITH_STRUCT(FusedBiasLeakyReluTilingData, tilingData, tiling);
    NsFusedBiasLeakyRelu::FusedBiasLeakyRelu<DTYPE_X, BUFFER_MODE> op;
    op.Init(x, bias, y, &tilingData);
    op.Process();
}
