/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file inplace_apply_proximal_adagrad.cpp
 * \brief InplaceApplyProximalAdagrad kernel entry (arch35 / Ascend950).
 *
 * Def-driven dtype: DTYPE_VAR 由 def DataType 列表编译期注入，框架按 dtype
 * 自动实例化 fp32 / fp16 / bf16 三个 kernel 变体。无需 TilingKey 模板参数。
 *
 * V2 signature: 6 inputs -> 2 outputs -> workspace -> tiling.
 */

#include "./inplace_apply_proximal_adagrad.h"

extern "C" __global__ __aicore__ void inplace_apply_proximal_adagrad(GM_ADDR var, GM_ADDR accum, GM_ADDR lr, GM_ADDR l1,
                                                                     GM_ADDR l2, GM_ADDR grad, GM_ADDR var_out,
                                                                     GM_ADDR accum_out, GM_ADDR workspace,
                                                                     GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(InplaceApplyProximalAdagradTilingData);
    GET_TILING_DATA_WITH_STRUCT(InplaceApplyProximalAdagradTilingData, tilingData, tiling);

    NsInplaceApplyProximalAdagrad::InplaceApplyProximalAdagradKernel<DTYPE_VAR> op;
    op.Init(var, accum, lr, l1, l2, grad, var_out, accum_out, &tilingData);
    op.Process();
}
