/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

#include "fused_mul_apply_momentum_tiling_arch35.h"
#include "optim/fused_mul_apply_momentum/op_kernel/arch35/fused_mul_apply_momentum_struct.h"
#include <algorithm>
#include <set>
#include <graph/utils/type_utils.h>

using namespace ge;

// ============================================================
// Tiling helper functions
// ============================================================

namespace fused_mul_apply_momentum {

constexpr int64_t kUBAlignBytes = 32;
constexpr int64_t kCompDtypeSize = 4; // FP32 internal computation dtype
constexpr size_t MAX_DIM_NUM = 8;

bool CheckBroadcastShape(const std::vector<std::vector<int64_t>>& padded_in,
                         const std::vector<std::vector<int64_t>>& padded_out, int64_t max_rank)
{
    for (int64_t d = 0; d < max_rank; d++) {
        int64_t ref = -1;
        for (size_t i = 0; i < padded_in.size(); i++) {
            if (padded_in[i][d] != 1) {
                if (ref == -1)
                    ref = padded_in[i][d];
                else if (padded_in[i][d] != ref) {
                    OP_LOGE("CheckBroadcastShape", "dim %d broadcast incompatible: input[%d] size %d != %d", (int)d,
                            (int)i, (int)padded_in[i][d], (int)ref);
                    return false;
                }
            }
        }
        for (size_t i = 0; i < padded_out.size(); i++) {
            if (padded_out[i][d] != 1) {
                if (ref == -1)
                    ref = padded_out[i][d];
                else if (padded_out[i][d] != ref) {
                    OP_LOGE("CheckBroadcastShape", "dim %d broadcast incompatible: output[%d] size %d != %d", (int)d,
                            (int)i, (int)padded_out[i][d], (int)ref);
                    return false;
                }
            }
        }
    }
    return true;
}

void SqueezeDims(const std::vector<std::vector<int64_t>>& padded_in,
                 const std::vector<std::vector<int64_t>>& padded_out, int64_t max_rank, int64_t num_inputs,
                 int64_t num_outputs, std::vector<int64_t>& maximum_bro_shape,
                 std::vector<std::vector<int64_t>>& normal_input_shapes,
                 std::vector<std::vector<int64_t>>& normal_output_shapes)
{
    maximum_bro_shape.clear();
    normal_input_shapes.assign(num_inputs, std::vector<int64_t>());
    normal_output_shapes.assign(num_outputs, std::vector<int64_t>());
    for (int64_t d = 0; d < max_rank; d++) {
        bool all_one = true;
        int64_t max_dim = 0;
        for (int64_t i = 0; i < num_inputs; i++) {
            if (padded_in[i][d] != 1)
                all_one = false;
            max_dim = std::max(max_dim, padded_in[i][d]);
        }
        for (int64_t i = 0; i < num_outputs; i++) {
            if (padded_out[i][d] != 1)
                all_one = false;
            max_dim = std::max(max_dim, padded_out[i][d]);
        }
        if (!all_one) {
            maximum_bro_shape.push_back(max_dim);
            for (int64_t i = 0; i < num_inputs; i++)
                normal_input_shapes[i].push_back(padded_in[i][d]);
            for (int64_t i = 0; i < num_outputs; i++)
                normal_output_shapes[i].push_back(padded_out[i][d]);
        }
    }
    if (maximum_bro_shape.empty()) {
        maximum_bro_shape.push_back(1);
        for (int64_t i = 0; i < num_inputs; i++)
            normal_input_shapes[i].push_back(1);
        for (int64_t i = 0; i < num_outputs; i++)
            normal_output_shapes[i].push_back(1);
    }
}

bool PadAndSqueeze(const std::vector<std::vector<int64_t>>& input_shapes,
                   const std::vector<std::vector<int64_t>>& output_shapes, std::vector<int64_t>& maximum_bro_shape,
                   std::vector<std::vector<int64_t>>& normal_input_shapes,
                   std::vector<std::vector<int64_t>>& normal_output_shapes)
{
    int64_t num_inputs = (int64_t)input_shapes.size();
    int64_t num_outputs = (int64_t)output_shapes.size();
    int64_t max_rank = 0;
    for (auto& s : input_shapes)
        max_rank = std::max(max_rank, (int64_t)s.size());
    for (auto& s : output_shapes)
        max_rank = std::max(max_rank, (int64_t)s.size());

    auto pad = [&](const std::vector<int64_t>& s) {
        std::vector<int64_t> p;
        p.assign(max_rank - (int64_t)s.size(), 1);
        p.insert(p.end(), s.begin(), s.end());
        return p;
    };
    std::vector<std::vector<int64_t>> padded_in(num_inputs), padded_out(num_outputs);
    for (int64_t i = 0; i < num_inputs; i++)
        padded_in[i] = pad(input_shapes[i]);
    for (int64_t i = 0; i < num_outputs; i++)
        padded_out[i] = pad(output_shapes[i]);

    SqueezeDims(padded_in, padded_out, max_rank, num_inputs, num_outputs, maximum_bro_shape, normal_input_shapes,
                normal_output_shapes);
    return true;
}

bool FindSplitAxis(const std::vector<int64_t>& max_bro_shape, int64_t dtype_size, int64_t ub_per_core,
                   int64_t phys_nodes, SplitResult& out)
{
    int64_t per_buf_bytes = (ub_per_core / phys_nodes) & ~(kUBAlignBytes - 1);
    int64_t per_buf_elems = per_buf_bytes / dtype_size;
    constexpr int64_t MAX_COUNT = 4096;
    if (per_buf_elems > MAX_COUNT) {
        per_buf_elems = MAX_COUNT;
    }
    int64_t rank = (int64_t)max_bro_shape.size();
    int64_t inner = 1;
    for (int64_t k = rank - 1; k >= 0; k--) {
        if (max_bro_shape[k] * inner > per_buf_elems) {
            out.a_i = per_buf_elems / inner;
            out.a_o = (max_bro_shape[k] + out.a_i - 1) / out.a_i;
            int64_t rem = max_bro_shape[k] % out.a_i;
            out.a_i_tail = (rem == 0) ? out.a_i : rem;
            out.axis = k;
            return true;
        }
        if (k == 0) {
            out.axis = 0;
            out.a_i = max_bro_shape[0];
            out.a_o = 1;
            out.a_i_tail = max_bro_shape[0];
            return true;
        }
        inner *= max_bro_shape[k];
    }
    return true;
}

bool MultiCoreSplit(const std::vector<int64_t>& max_bro_shape, const SplitResult& ub_split, int64_t max_cores,
                    MultiCoreResult& out)
{
    int64_t k = ub_split.axis, outer_prod = 1;
    for (int64_t j = 0; j < k; j++)
        outer_prod *= max_bro_shape[j];
    out.total_tiles = outer_prod * ub_split.a_o;
    out.num_cores = (out.total_tiles < max_cores) ? out.total_tiles : max_cores;
    out.tiles_main = out.total_tiles / out.num_cores;
    out.cores_tail = out.total_tiles % out.num_cores;
    return true;
}

bool PrecomputeStrides(const std::vector<int64_t>& s, std::vector<int64_t>& strides)
{
    int64_t rank = (int64_t)s.size();
    strides.assign(rank, 0);
    for (int64_t d = rank - 1; d >= 0; d--) {
        if (s[d] == 1) {
            strides[d] = 0;
            continue;
        }
        int64_t prod = 1;
        for (int64_t j = d + 1; j < rank; j++)
            prod *= s[j];
        strides[d] = prod;
    }
    return true;
}

template <int64_t R>
void FillTensorSlots(FusedMulApplyMomentumTilingData<R>* tiling,
                     const std::vector<std::vector<int64_t>>& normal_input_shapes,
                     const std::vector<std::vector<int64_t>>& normal_output_shapes,
                     const std::vector<std::vector<int64_t>>& in_strides,
                     const std::vector<std::vector<int64_t>>& out_strides, int64_t rank_, int64_t delta)
{
    int64_t num_in = (int64_t)normal_input_shapes.size();
    int64_t num_out = (int64_t)normal_output_shapes.size();

    for (int64_t i = 0; i < num_in; i++) {
        for (int64_t d = 0; d < delta; d++) {
            tiling->input_shapes[i][d] = 1;
            tiling->input_strides[i][d] = 0;
        }
        for (int64_t d = 0; d < rank_; d++) {
            tiling->input_shapes[i][d + delta] = normal_input_shapes[i][d];
            tiling->input_strides[i][d + delta] = in_strides[i][d];
        }
    }
    for (int64_t i = num_in; i < kMaxInputSlots; i++)
        for (int64_t d = 0; d < R; d++) {
            tiling->input_shapes[i][d] = 1;
            tiling->input_strides[i][d] = 0;
        }

    for (int64_t i = 0; i < num_out; i++) {
        for (int64_t d = 0; d < delta; d++) {
            tiling->output_shapes[i][d] = 1;
            tiling->output_strides[i][d] = 0;
        }
        for (int64_t d = 0; d < rank_; d++) {
            tiling->output_shapes[i][d + delta] = normal_output_shapes[i][d];
            tiling->output_strides[i][d + delta] = out_strides[i][d];
        }
    }
    for (int64_t i = num_out; i < kMaxOutputSlots; i++)
        for (int64_t d = 0; d < R; d++) {
            tiling->output_shapes[i][d] = 1;
            tiling->output_strides[i][d] = 0;
        }
}

template <int64_t R>
void PadAndFillSlots(FusedMulApplyMomentumTilingData<R>* tiling,
                     const std::vector<std::vector<int64_t>>& normal_input_shapes,
                     const std::vector<std::vector<int64_t>>& normal_output_shapes,
                     const std::vector<std::vector<int64_t>>& in_strides,
                     const std::vector<std::vector<int64_t>>& out_strides, int64_t rank_, int64_t delta,
                     const std::vector<int64_t>& max_bro_shape)
{
    tiling->rank = rank_;
    for (int64_t d = 0; d < delta; d++)
        tiling->max_bro_shape[d] = 1;
    for (int64_t d = 0; d < rank_; d++)
        tiling->max_bro_shape[d + delta] = max_bro_shape[d];
    tiling->split.axis += delta;
    tiling->num_inputs = (int64_t)normal_input_shapes.size();
    tiling->num_outputs = (int64_t)normal_output_shapes.size();
    FillTensorSlots<R>(tiling, normal_input_shapes, normal_output_shapes, in_strides, out_strides, rank_, delta);
}

} // namespace fused_mul_apply_momentum

// ============================================================
// Tiling main class
// ============================================================

namespace optiling {

using namespace fused_mul_apply_momentum;

static std::string Arr2String(const int64_t* arr, int64_t n)
{
    std::ostringstream oss;
    oss << "[";
    if (n > 0) {
        for (int64_t i = 0; i < n - 1; ++i) {
            oss << arr[i] << ",";
        }
        oss << arr[n - 1];
    }
    oss << "]";
    return oss.str();
}

FusedMulApplyMomentumTiling::FusedMulApplyMomentumTiling(gert::TilingContext* ctx) : ctx_(ctx) {}

ge::graphStatus FusedMulApplyMomentumTiling::GetShapeInfo()
{
    const char* opName = ctx_->GetNodeName();
    auto compileInfo = reinterpret_cast<const FusedMulApplyMomentumCompileInfo*>(ctx_->GetCompileInfo());
    OP_CHECK_NULL_WITH_CONTEXT(ctx_, compileInfo);

    for (size_t i = 0; i < ctx_->GetComputeNodeInfo()->GetInputsNum(); ++i) {
        auto shape = ctx_->GetInputShape(i);
        OP_CHECK_NULL_WITH_CONTEXT(ctx_, shape);
        std::vector<int64_t> dims;
        gert::Shape s = shape->GetStorageShape();
        for (size_t d = 0; d < s.GetDimNum(); ++d)
            dims.push_back(s.GetDim(d));
        rawInputShapes_.push_back(dims);
    }

    const auto* firstInputShape = ctx_->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(ctx_, firstInputShape);
    const auto& varShape = firstInputShape->GetStorageShape();
    if (varShape.GetDimNum() > MAX_DIM_NUM) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(opName, "var.dim_num", std::to_string(varShape.GetDimNum()).c_str(),
                                              "The dim num of var must be less than or equal to 8");
        return ge::GRAPH_FAILED;
    }

    for (size_t i = 0; i < ctx_->GetComputeNodeInfo()->GetOutputsNum(); ++i) {
        auto shape = ctx_->GetOutputShape(i);
        OP_CHECK_NULL_WITH_CONTEXT(ctx_, shape);
        std::vector<int64_t> dims;
        gert::Shape s = shape->GetStorageShape();
        for (size_t d = 0; d < s.GetDimNum(); ++d)
            dims.push_back(s.GetDim(d));
        rawOutputShapes_.push_back(dims);
    }

    auto inputDesc = ctx_->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(ctx_, inputDesc);
    ge::DataType dtype = inputDesc->GetDataType();

    const std::set<ge::DataType> supportedDtypes = {ge::DT_FLOAT16, ge::DT_FLOAT};
    if (supportedDtypes.count(dtype) == 0) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(opName, "var.dtype", ge::TypeUtils::DataTypeToSerialString(dtype).c_str(),
                                              "expected DT_FLOAT16, DT_FLOAT");
        return ge::GRAPH_FAILED;
    }

    auto varFormat = inputDesc->GetFormat().GetStorageFormat();
    OP_CHECK_IF(varFormat != ge::FORMAT_ND,
                OP_LOGE(opName, "var format must be ND, got %d", static_cast<int32_t>(varFormat)),
                return ge::GRAPH_FAILED);

    uint32_t dtypeSize = 0;
    if (!ge::TypeUtils::GetDataTypeLength(dtype, dtypeSize) || dtypeSize == 0) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(opName, "var.dtype", ge::TypeUtils::DataTypeToSerialString(dtype).c_str(),
                                              "failed to get dtype length");
        return ge::GRAPH_FAILED;
    }
    dtypeSize_ = static_cast<int64_t>(dtypeSize);

    constexpr size_t kNumInputs = 6;
    for (size_t i = 1; i < kNumInputs; ++i) {
        auto desc = ctx_->GetInputDesc(i);
        OP_CHECK_NULL_WITH_CONTEXT(ctx_, desc);
        ge::DataType inputDtype = desc->GetDataType();
        if (inputDtype != dtype) {
            OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(
                opName, "input dtype", ge::TypeUtils::DataTypeToSerialString(inputDtype).c_str(),
                ("must match var dtype " + ge::TypeUtils::DataTypeToSerialString(dtype)).c_str());
            return ge::GRAPH_FAILED;
        }
    }

    PadAndSqueeze(rawInputShapes_, rawOutputShapes_, maxBroShape_, normalInputShapes_, normalOutputShapes_);
    rank_ = (int64_t)maxBroShape_.size();

    if (rank_ > kMaxRank) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(opName, "rank", std::to_string(rank_).c_str(),
                                              "rank exceeds maximum supported rank 8");
        return GRAPH_FAILED;
    }

    OP_LOGI(opName, "GetShapeInfo done rank %ld dtype %ld ub %llu core %lu", rank_, dtypeSize_,
            (unsigned long long)compileInfo->ubSize, compileInfo->coreNum);

    if (!CheckBroadcastShape(normalInputShapes_, normalOutputShapes_, rank_)) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(opName, "broadcast_shape", "incompatible",
                                              "input and output shapes are not broadcast compatible");
        return ge::GRAPH_FAILED;
    }

    return GRAPH_SUCCESS;
}

bool ReadUseNesterovAttr(gert::TilingContext* ctx)
{
    bool use_nesterov = false;
    auto nodeAttrs = ctx->GetComputeNodeInfo()->GetAttrs();
    if (nodeAttrs != nullptr) {
        const bool* attr_val = nodeAttrs->GetBool(0);
        if (attr_val != nullptr) {
            use_nesterov = *attr_val;
        }
    }
    return use_nesterov;
}

template <int64_t R>
ge::graphStatus FusedMulApplyMomentumTiling::DoTilingAndSet()
{
    auto* tiling = ctx_->GetTilingData<FusedMulApplyMomentumTilingData<R>>();
    OP_CHECK_NULL_WITH_CONTEXT(ctx_, tiling);

    auto* compileInfo = reinterpret_cast<const FusedMulApplyMomentumCompileInfo*>(ctx_->GetCompileInfo());
    int64_t ub_per_core = (int64_t)compileInfo->ubSize;
    int64_t per_buf_bytes = (ub_per_core / kPhysNodes) & ~(kUBAlignBytes - 1);

    int64_t comp_dtype_size = kCompDtypeSize;
    FindSplitAxis(maxBroShape_, comp_dtype_size, ub_per_core, kPhysNodes, tiling->split);
    MultiCoreSplit(maxBroShape_, tiling->split, (int64_t)compileInfo->coreNum, tiling->multicore);
    tiling->per_buf_bytes = per_buf_bytes;
    tiling->per_buf_elems = per_buf_bytes / comp_dtype_size;

    tiling->use_nesterov = ReadUseNesterovAttr(ctx_);

    int64_t num_in = (int64_t)normalInputShapes_.size();
    int64_t num_out = (int64_t)normalOutputShapes_.size();
    std::vector<std::vector<int64_t>> in_strides(num_in), out_strides(num_out);
    for (int64_t i = 0; i < num_in; i++)
        PrecomputeStrides(normalInputShapes_[i], in_strides[i]);
    for (int64_t i = 0; i < num_out; i++)
        PrecomputeStrides(normalOutputShapes_[i], out_strides[i]);

    int64_t delta = R - rank_;
    PadAndFillSlots<R>(tiling, normalInputShapes_, normalOutputShapes_, in_strides, out_strides, rank_, delta,
                       maxBroShape_);

    ctx_->SetBlockDim(tiling->multicore.num_cores);

    OP_LOGI(ctx_->GetNodeName(),
            "TilingData: per_buf_bytes=%ld per_buf_elems=%ld rank=%ld->R=%d "
            "use_nesterov=%d max_bro_shape=%s "
            "split(axis=%ld a_i=%ld a_o=%ld a_i_tail=%ld) "
            "multi(cores=%ld tiles=%ld main=%ld core_tail=%ld) num_in=%ld num_out=%ld",
            tiling->per_buf_bytes, tiling->per_buf_elems, rank_, (int)R, (int)tiling->use_nesterov,
            Arr2String(tiling->max_bro_shape, R).c_str(), tiling->split.axis, tiling->split.a_i, tiling->split.a_o,
            tiling->split.a_i_tail, tiling->multicore.num_cores, tiling->multicore.total_tiles,
            tiling->multicore.tiles_main, tiling->multicore.cores_tail, num_in, num_out);

    return GRAPH_SUCCESS;
}

ge::graphStatus FusedMulApplyMomentumTiling::RunTiling()
{
    ge::graphStatus ret = GetShapeInfo();
    if (ret != GRAPH_SUCCESS)
        return ret;

    int64_t mapped = (rank_ <= FUSED_MUL_APPLY_MOMENTUM_RANK_4) ? FUSED_MUL_APPLY_MOMENTUM_RANK_4 :
                                                                  FUSED_MUL_APPLY_MOMENTUM_RANK_8;
    if (mapped == FUSED_MUL_APPLY_MOMENTUM_RANK_4) {
        ret = DoTilingAndSet<FUSED_MUL_APPLY_MOMENTUM_RANK_4>();
        ctx_->SetTilingKey(GET_TPL_TILING_KEY(FUSED_MUL_APPLY_MOMENTUM_RANK_4));
    } else {
        ret = DoTilingAndSet<FUSED_MUL_APPLY_MOMENTUM_RANK_8>();
        ctx_->SetTilingKey(GET_TPL_TILING_KEY(FUSED_MUL_APPLY_MOMENTUM_RANK_8));
    }
    return ret;
}

static ge::graphStatus TilingFuncFusedMulApplyMomentum(gert::TilingContext* context)
{
    if (context == nullptr) {
        OP_LOGE("FusedMulApplyMomentum", "Tiling context is null");
        return ge::GRAPH_FAILED;
    }
    OP_LOGI(context->GetNodeName(), "Enter FusedMulApplyMomentumTilingFunc");
    FusedMulApplyMomentumTiling tiling(context);
    auto ret = tiling.RunTiling();
    if (ret != GRAPH_SUCCESS)
        return ret;
    size_t* workspaces = context->GetWorkspaceSizes(1);
    if (workspaces == nullptr)
        return GRAPH_FAILED;
    workspaces[0] = 0; // workspace = 0 for this operator
    return GRAPH_SUCCESS;
}

ge::graphStatus TilingPrepareForFusedMulApplyMomentum(gert::TilingParseContext* context)
{
    if (context == nullptr) {
        OP_LOGE("FusedMulApplyMomentum", "TilingParse context is null");
        return ge::GRAPH_FAILED;
    }
    fe::PlatFormInfos* platformInfo = context->GetPlatformInfo();
    auto compileInfo = context->GetCompiledInfo<FusedMulApplyMomentumCompileInfo>();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfo);
    OP_CHECK_NULL_WITH_CONTEXT(context, compileInfo);
    auto ap = platform_ascendc::PlatformAscendC(platformInfo);
    compileInfo->coreNum = ap.GetCoreNumAiv();
    ap.GetCoreMemSize(platform_ascendc::CoreMemType::UB, compileInfo->ubSize);
    return GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(FusedMulApplyMomentum)
    .Tiling(TilingFuncFusedMulApplyMomentum)
    .TilingParse<FusedMulApplyMomentumCompileInfo>(TilingPrepareForFusedMulApplyMomentum);

} // namespace optiling
