/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

/*!
 * \file test_avg_pool1_d.cpp
 * \brief Kernel UT for avg_pool1_d — single default scene mode (schMode=0)
 *        Test case: x shape (1,3,8), float32, ksize=2, strides=2, pads=[1,1],
 *        ceil_mode=false, count_include_pad=false
 *        Expected L_out=5, totalOutputElements=15, needCoreNum=1
 */

#include "../../../op_kernel/arch35/avg_pool1_d.cpp"
#include "avg_pool1_d_tiling_def.h"
#include <array>
#include <vector>
#include <iostream>
#include <string>
#include <cstdint>
#include <cstdlib>
#include "gtest/gtest.h"
#include "tikicpulib.h"
#include "data_utils.h"

using namespace std;

class AvgPool1dTest : public testing::Test {
protected:
    static void SetUpTestCase()
    {
        cout << "AvgPool1dTest SetUp\n" << endl;
        const string cmd = "cp -rf " + dataPath + " ./";
        system(cmd.c_str());
        system("chmod -R 755 ./avg_pool1_d_data/");
    }
    static void TearDownTestCase() { cout << "AvgPool1dTest TearDown\n" << endl; }

private:
    const static std::string rootPath;
    const static std::string dataPath;
};

const std::string AvgPool1dTest::rootPath = "../../../../";
const std::string AvgPool1dTest::dataPath = rootPath + "pooling/avg_pool1_d/tests/ut/op_kernel/avg_pool1_d_data";

TEST_F(AvgPool1dTest, test_case_0)
{
    // x shape (1, 3, 8), float32 -> 24 elements
    // y shape (1, 3, 5), float32 -> 15 elements (L_out=5)
    size_t xByteSize = 1 * 3 * 8 * sizeof(float);
    size_t yByteSize = 1 * 3 * 5 * sizeof(float);
    size_t tiling_data_size = sizeof(AvgPool1dTilingData);
    uint32_t numBlocks = 1;

    // gen_data.py: shape, dtype, ksize, strides, pads, ceil_mode, count_include_pad
    system("cd ./avg_pool1_d_data/ && python3 gen_data.py '(1, 3, 8)' 'float32' 2 2 '1,1' 0 0");
    std::string fileName = "./avg_pool1_d_data/float32_input_avg_pool1_d.bin";
    uint8_t* x = (uint8_t*)AscendC::GmAlloc(xByteSize);
    ReadFile(fileName, xByteSize, x, xByteSize);
    uint8_t* y = (uint8_t*)AscendC::GmAlloc(yByteSize);
    uint8_t* workspace = (uint8_t*)AscendC::GmAlloc(32);
    uint8_t* tiling = (uint8_t*)AscendC::GmAlloc(tiling_data_size);

    char* path_ = get_current_dir_name();
    string path(path_);

    AvgPool1dTilingData* tilingDatafromBin = reinterpret_cast<AvgPool1dTilingData*>(tiling);
    // 与 op_host/arch35/avg_pool1_d_tiling.cpp 的 TilingData 填充逻辑一致
    tilingDatafromBin->needCoreNum = 1;
    tilingDatafromBin->totalOutputElements = 15; // N*C*L_out = 1*3*5
    tilingDatafromBin->L = 8;
    tilingDatafromBin->L_out = 5;
    tilingDatafromBin->ksize = 2;
    tilingDatafromBin->strides = 2;
    tilingDatafromBin->pad_left = 1;
    tilingDatafromBin->pad_right = 1;
    tilingDatafromBin->count_include_pad = 0; // false

    // 单一默认场景模式，tiling_key = AVG_POOL1D_SCH_MODE_DEFAULT = 0
    ICPU_SET_TILING_KEY(0);
    AscendC::SetKernelMode(KernelMode::AIV_MODE);

    // kernel 入口: template <uint32_t schMode> avg_pool1_d(GM_ADDR x, GM_ADDR y, GM_ADDR workspace, GM_ADDR tiling)
    // 参数顺序: x, y, workspace, tiling（与 kernel 签名一致）
    ICPU_RUN_KF(avg_pool1_d<0>, numBlocks, x, y, workspace, (uint8_t*)(tilingDatafromBin));

    fileName = "./avg_pool1_d_data/float32_output_avg_pool1_d.bin";
    WriteFile(fileName, y, yByteSize);

    // 释放资源
    AscendC::GmFree(x);
    AscendC::GmFree(y);
    AscendC::GmFree(workspace);
    AscendC::GmFree(tiling);

    system("cd ./avg_pool1_d_data/ && python3 compare_data.py 'float32'");
    free(path_);
}
