/**
 * Copyright (c) 2025 Tianjin University Ltd.
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file foreach_mul_list_tiling_arch35.cpp
 * \brief arch35 tiling for foreach_mul_list
 */

#include "log/log.h"
#include "util/math_util.h"
#include "util/platform_util.h"
#include "op_host/tiling_util.h"
#include "op_host/tiling_templates_registry.h"
#include "../../op_kernel/arch35/foreach_mul_list_tiling_data.h"
#include "../../op_kernel/arch35/foreach_mul_list_tiling_key.h"

namespace optiling {

using namespace Ops::NN::Optiling;

constexpr uint32_t WS_SYS_SIZE = 0U;
constexpr int32_t INPUT_IDX_0 = 0;
constexpr uint32_t DCACHE_SIZE = 128 * 1024;
constexpr int64_t ALIGN_SIZE = 32;
constexpr int32_t MAX_TENSOR_NUM = 256;

struct ForeachMulListCompileInfo {};

static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t& ubSize, int64_t& coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ForeachMulListTilingFunc(gert::TilingContext* context)
{
    // 1. Get platform info
    uint64_t ubSize;
    int64_t coreNum;
    OP_CHECK_IF(GetPlatformInfo(context, ubSize, coreNum) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetPlatformInfo error"), return ge::GRAPH_FAILED);

    // 2. Get tensor list info from x1
    auto computeNodeInfoPtr = context->GetComputeNodeInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, computeNodeInfoPtr);
    auto idxInstanceInfoPtr = computeNodeInfoPtr->GetInputInstanceInfo(INPUT_IDX_0);
    OP_CHECK_NULL_WITH_CONTEXT(context, idxInstanceInfoPtr);
    uint64_t tensorNum = idxInstanceInfoPtr->GetInstanceNum();

    // 3. Get dtype for tiling key
    auto inputDesc = context->GetDynamicInputDesc(INPUT_IDX_0, 0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
    ge::DataType dataType = inputDesc->GetDataType();

    // 4. Calculate total elements and per-tensor sizes
    int64_t totalElements = 0;
    ForeachMulListTilingData* tiling = context->GetTilingData<ForeachMulListTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(memset_s(tiling, sizeof(ForeachMulListTilingData), 0, sizeof(ForeachMulListTilingData)) != EOK,
                OP_LOGE(context, "set tiling data error"), return ge::GRAPH_FAILED);

    OP_CHECK_IF(tensorNum > MAX_TENSOR_NUM, OP_LOGE(context, "tensorNum should be less than or equal to 256"),
                return ge::GRAPH_FAILED);
    for (uint64_t i = 0; i < tensorNum; i++) {
        auto shapePtr = context->GetDynamicInputShape(INPUT_IDX_0, i);
        OP_CHECK_NULL_WITH_CONTEXT(context, shapePtr);
        auto storageShape = shapePtr->GetStorageShape();
        int64_t numel = storageShape.GetShapeSize();
        tiling->tensorSizes[i] = numel;
        totalElements += numel;
    }
    tiling->tensorNum = static_cast<int32_t>(tensorNum);
    tiling->totalElements = totalElements;

    // 5. Calculate core split
    if (totalElements == 0) {
        tiling->needCoreNum = 1;
        tiling->perCoreElements = 0;
        tiling->lastCoreElements = 0;
        context->SetBlockDim(1);
    } else {
        tiling->perCoreElements = std::min(static_cast<int64_t>(65536), Ops::Base::CeilDiv(totalElements, coreNum));
        // Align to 32 (warp size)
        tiling->perCoreElements = Ops::Base::CeilAlign(tiling->perCoreElements, ALIGN_SIZE);
        tiling->needCoreNum = Ops::Base::CeilDiv(totalElements, tiling->perCoreElements);
        tiling->lastCoreElements = totalElements - tiling->perCoreElements * (tiling->needCoreNum - 1);
        context->SetBlockDim(tiling->needCoreNum);
    }

    // 6. Set workspace
    size_t* currentWorkspace = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = WS_SYS_SIZE;

    // 7. Set local memory size
    context->SetLocalMemorySize(static_cast<uint32_t>(ubSize - DCACHE_SIZE));

    // 8. Set tiling key by dtype
    uint64_t tilingKey = 0;
    if (dataType == ge::DT_FLOAT) {
        tilingKey = GET_TPL_TILING_KEY(FOREACH_MUL_LIST_TPL_SCH_MODE_FLOAT);
    } else if (dataType == ge::DT_FLOAT16) {
        tilingKey = GET_TPL_TILING_KEY(FOREACH_MUL_LIST_TPL_SCH_MODE_FLOAT16);
    } else if (dataType == ge::DT_BF16) {
        tilingKey = GET_TPL_TILING_KEY(FOREACH_MUL_LIST_TPL_SCH_MODE_BF16);
    } else if (dataType == ge::DT_INT32) {
        tilingKey = GET_TPL_TILING_KEY(FOREACH_MUL_LIST_TPL_SCH_MODE_INT32);
    } else if (dataType == ge::DT_INT16) {
        tilingKey = GET_TPL_TILING_KEY(FOREACH_MUL_LIST_TPL_SCH_MODE_INT16);
    } else if (dataType == ge::DT_INT8) {
        tilingKey = GET_TPL_TILING_KEY(FOREACH_MUL_LIST_TPL_SCH_MODE_INT8);
    } else if (dataType == ge::DT_UINT8) {
        tilingKey = GET_TPL_TILING_KEY(FOREACH_MUL_LIST_TPL_SCH_MODE_UINT8);
    } else {
        OP_LOGE(context, "unsupported dtype for foreach_mul_list");
        return ge::GRAPH_FAILED;
    }
    context->SetTilingKey(tilingKey);

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForForeachMulList([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(ForeachMulList)
    .Tiling(ForeachMulListTilingFunc)
    .TilingParse<ForeachMulListCompileInfo>(TilingParseForForeachMulList);

} // namespace optiling
