/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file sparse_apply_adagrad_v2_infershape.cpp
 * \brief shape and dtype inference for sparse_apply_adagrad_v2
 */

#include "graph/utils/type_utils.h"
#include "register/op_impl_registry.h"
#include "log/log.h"

using namespace ge;

namespace ops {

static constexpr int64_t IDX_VAR = 0;
static constexpr int64_t IDX_ACCUM = 1;
static constexpr int64_t IDX_LR = 2;
static constexpr int64_t IDX_EPSILON = 3;
static constexpr int64_t IDX_GRAD = 4;
static constexpr int64_t IDX_INDICES = 5;

static constexpr int64_t UNKNOWN_DIM = -1;
static constexpr int64_t UNKNOWN_RANK = -2;

static bool IsUnknownRank(const gert::Shape* shape)
{
    return (shape->GetDimNum() == 1U) && (shape->GetDim(0) == UNKNOWN_RANK);
}

static ge::graphStatus InferShapeSparseApplyAdagradV2(gert::InferShapeContext* context)
{
    OP_LOGD(context->GetNodeName(), "Begin to do InferShapeSparseApplyAdagradV2");

    // 输出 var shape = 输入 var shape（原地更新）
    const gert::Shape* varShape = context->GetInputShape(IDX_VAR);
    OP_CHECK_NULL_WITH_CONTEXT(context, varShape);
    gert::Shape* varOutShape = context->GetOutputShape(IDX_VAR);
    OP_CHECK_NULL_WITH_CONTEXT(context, varOutShape);

    // 输出 accum shape = 输入 accum shape（原地更新）
    const gert::Shape* accumShape = context->GetInputShape(IDX_ACCUM);
    OP_CHECK_NULL_WITH_CONTEXT(context, accumShape);
    gert::Shape* accumOutShape = context->GetOutputShape(IDX_ACCUM);
    OP_CHECK_NULL_WITH_CONTEXT(context, accumOutShape);

    // 获取其余输入 shape（null 校验）
    const gert::Shape* lrShape = context->GetInputShape(IDX_LR);
    OP_CHECK_NULL_WITH_CONTEXT(context, lrShape);
    const gert::Shape* epsilonShape = context->GetInputShape(IDX_EPSILON);
    OP_CHECK_NULL_WITH_CONTEXT(context, epsilonShape);
    const gert::Shape* gradShape = context->GetInputShape(IDX_GRAD);
    OP_CHECK_NULL_WITH_CONTEXT(context, gradShape);
    const gert::Shape* indicesShape = context->GetInputShape(IDX_INDICES);
    OP_CHECK_NULL_WITH_CONTEXT(context, indicesShape);

    // Unknown rank (-2): 任一输入为 unknown rank 时，无法做任何 rank/shape 校验，
    // 直接将输出透传为 unknown rank
    if (IsUnknownRank(varShape) || IsUnknownRank(accumShape) || IsUnknownRank(lrShape) || IsUnknownRank(epsilonShape) ||
        IsUnknownRank(gradShape) || IsUnknownRank(indicesShape)) {
        varOutShape->SetDimNum(1U);
        varOutShape->SetDim(0, UNKNOWN_RANK);
        accumOutShape->SetDimNum(1U);
        accumOutShape->SetDim(0, UNKNOWN_RANK);
        OP_LOGD(context->GetNodeName(), "Some input is unknown rank, set outputs to unknown rank");
        return GRAPH_SUCCESS;
    }

    auto varDimNum = varShape->GetDimNum();
    varOutShape->SetDimNum(varDimNum);
    for (size_t i = 0; i < varDimNum; i++) {
        varOutShape->SetDim(i, varShape->GetDim(i));
    }

    auto accumDimNum = accumShape->GetDimNum();
    accumOutShape->SetDimNum(accumDimNum);
    for (size_t i = 0; i < accumDimNum; i++) {
        accumOutShape->SetDim(i, accumShape->GetDim(i));
    }

    // 校验约束（与 SE 文档 §5.4/5.5、MDE §3.4 一致）:

    // 0. var/accum 应至少为 2 维（shape (N, C)），rank < 2 语义非法
    OP_CHECK_IF(varDimNum < 2,
                OP_LOGE_FOR_INVALID_SHAPEDIM(context->GetNodeName(), "var", std::to_string(varDimNum), "at least 2D"),
                return ge::GRAPH_FAILED);

    // 1. accum.shape == var.shape
    OP_CHECK_IF(accumDimNum != varDimNum,
                OP_LOGE_FOR_INVALID_SHAPEDIMS_WITH_REASON(
                    context->GetNodeName(), "accum and var",
                    (std::to_string(accumDimNum) + "D, " + std::to_string(varDimNum) + "D").c_str(),
                    "accum dim num must equal var dim num"),
                return ge::GRAPH_FAILED);
    for (size_t i = 0; i < varDimNum; i++) {
        auto accumDim = accumShape->GetDim(i);
        auto varDim = varShape->GetDim(i);
        // Unknown shape (-1): 某维为 -1 表示取值未知，无法校验具体值，仅当两侧均已知且不等时才报错
        OP_CHECK_IF(accumDim != UNKNOWN_DIM && varDim != UNKNOWN_DIM && accumDim != varDim,
                    OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(
                        context->GetNodeName(), "accum and var",
                        (Ops::Base::ToString(*accumShape) + ", " + Ops::Base::ToString(*varShape)).c_str(),
                        "accum shape must equal var shape"),
                    return ge::GRAPH_FAILED);
    }

    // 2. lr 应为标量（shape 为空或 [1]）；动态 shape 下 [−1] 也视为合法标量
    auto lrDimNum = lrShape->GetDimNum();
    OP_CHECK_IF(lrDimNum != 0 && !(lrDimNum == 1 && (lrShape->GetDim(0) == 1 || lrShape->GetDim(0) == UNKNOWN_DIM)),
                OP_LOGE_FOR_INVALID_SHAPEDIM_WITH_REASON(context->GetNodeName(), "lr", std::to_string(lrDimNum).c_str(),
                                                         "lr must be a scalar (shape empty or [1])"),
                return ge::GRAPH_FAILED);

    // 3. epsilon 应为标量（shape 为空或 [1]）；动态 shape 下 [−1] 也视为合法标量
    auto epsDimNum = epsilonShape->GetDimNum();
    OP_CHECK_IF(
        epsDimNum != 0 && !(epsDimNum == 1 && (epsilonShape->GetDim(0) == 1 || epsilonShape->GetDim(0) == UNKNOWN_DIM)),
        OP_LOGE_FOR_INVALID_SHAPEDIM_WITH_REASON(context->GetNodeName(), "epsilon", std::to_string(epsDimNum).c_str(),
                                                 "epsilon must be a scalar (shape empty or [1])"),
        return ge::GRAPH_FAILED);

    // 4. indices 应为一维向量（shape 仅含 1 个维度）
    auto indicesDimNum = indicesShape->GetDimNum();
    OP_CHECK_IF(indicesDimNum != 1,
                OP_LOGE_FOR_INVALID_SHAPEDIM(context->GetNodeName(), "indices", std::to_string(indicesDimNum), "1D"),
                return ge::GRAPH_FAILED);
    int64_t N = indicesShape->GetDim(0);

    // 5. grad.shape[0] == N, grad.shape[1:] == var.shape[1:]
    auto gradDimNum = gradShape->GetDimNum();
    OP_CHECK_IF(gradDimNum != varDimNum,
                OP_LOGE_FOR_INVALID_SHAPEDIMS_WITH_REASON(
                    context->GetNodeName(), "grad and var",
                    (std::to_string(gradDimNum) + "D, " + std::to_string(varDimNum) + "D").c_str(),
                    "grad dim num must equal var dim num"),
                return ge::GRAPH_FAILED);
    // Unknown shape (-1): grad[0] 或 N 为 -1 时跳过值校验
    auto gradDim0 = gradShape->GetDim(0);
    OP_CHECK_IF(gradDim0 != UNKNOWN_DIM && N != UNKNOWN_DIM && gradDim0 != N,
                OP_LOGE_FOR_INVALID_SHAPE_WITH_REASON(
                    context->GetNodeName(), "grad", Ops::Base::ToString(*gradShape).c_str(),
                    ("grad first dim must equal indices length " + std::to_string(N)).c_str()),
                return ge::GRAPH_FAILED);
    for (size_t i = 1; i < varDimNum; i++) {
        auto gradDimI = gradShape->GetDim(i);
        auto varDimI = varShape->GetDim(i);
        // Unknown shape (-1): 某维为 -1 时跳过值校验
        OP_CHECK_IF(gradDimI != UNKNOWN_DIM && varDimI != UNKNOWN_DIM && gradDimI != varDimI,
                    OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(
                        context->GetNodeName(), "grad and var",
                        (Ops::Base::ToString(*gradShape) + ", " + Ops::Base::ToString(*varShape)).c_str(),
                        "grad shape[1:] must equal var shape[1:]"),
                    return ge::GRAPH_FAILED);
    }

    OP_LOGD(context->GetNodeName(), "End to do InferShapeSparseApplyAdagradV2");
    return GRAPH_SUCCESS;
}

static ge::graphStatus InferDataTypeSparseApplyAdagradV2(gert::InferDataTypeContext* context)
{
    // dtype 一致性校验（与 SE 文档 §5.5、MDE §3.4 一致）:
    // var.dtype == accum.dtype == lr.dtype == epsilon.dtype == grad.dtype
    auto varDtype = context->GetInputDataType(IDX_VAR);
    auto accumDtype = context->GetInputDataType(IDX_ACCUM);
    auto lrDtype = context->GetInputDataType(IDX_LR);
    auto epsilonDtype = context->GetInputDataType(IDX_EPSILON);
    auto gradDtype = context->GetInputDataType(IDX_GRAD);

    OP_CHECK_IF(varDtype != accumDtype,
                OP_LOGE_FOR_INVALID_DTYPES_WITH_REASON(context->GetNodeName(), "var and accum",
                                                       (ge::TypeUtils::DataTypeToSerialString(varDtype) + ", " +
                                                        ge::TypeUtils::DataTypeToSerialString(accumDtype))
                                                           .c_str(),
                                                       "var dtype must equal accum dtype"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(varDtype != lrDtype,
                OP_LOGE_FOR_INVALID_DTYPES_WITH_REASON(context->GetNodeName(), "var and lr",
                                                       (ge::TypeUtils::DataTypeToSerialString(varDtype) + ", " +
                                                        ge::TypeUtils::DataTypeToSerialString(lrDtype))
                                                           .c_str(),
                                                       "var dtype must equal lr dtype"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(varDtype != epsilonDtype,
                OP_LOGE_FOR_INVALID_DTYPES_WITH_REASON(context->GetNodeName(), "var and epsilon",
                                                       (ge::TypeUtils::DataTypeToSerialString(varDtype) + ", " +
                                                        ge::TypeUtils::DataTypeToSerialString(epsilonDtype))
                                                           .c_str(),
                                                       "var dtype must equal epsilon dtype"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(varDtype != gradDtype,
                OP_LOGE_FOR_INVALID_DTYPES_WITH_REASON(context->GetNodeName(), "var and grad",
                                                       (ge::TypeUtils::DataTypeToSerialString(varDtype) + ", " +
                                                        ge::TypeUtils::DataTypeToSerialString(gradDtype))
                                                           .c_str(),
                                                       "var dtype must equal grad dtype"),
                return ge::GRAPH_FAILED);

    // indices.dtype == int32
    auto indicesDtype = context->GetInputDataType(IDX_INDICES);
    OP_CHECK_IF(indicesDtype != ge::DT_INT32,
                OP_LOGE_FOR_INVALID_DTYPE(context->GetNodeName(), "indices",
                                          ge::TypeUtils::DataTypeToSerialString(indicesDtype).c_str(), "INT32"),
                return ge::GRAPH_FAILED);

    // 输出 var dtype = 输入 var dtype（原地更新）
    context->SetOutputDataType(IDX_VAR, varDtype);

    // 输出 accum dtype = 输入 accum dtype（原地更新）
    context->SetOutputDataType(IDX_ACCUM, accumDtype);

    return GRAPH_SUCCESS;
}

IMPL_OP_INFERSHAPE(SparseApplyAdagradV2)
    .InferShape(InferShapeSparseApplyAdagradV2)
    .InferDataType(InferDataTypeSparseApplyAdagradV2);

} // namespace ops
