/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file sparse_apply_rms_prop_proto.h
 * \brief
 */
#ifndef OPS_OP_PROTO_INC_SPARSEAPPLYRMSPROP_H_
#define OPS_OP_PROTO_INC_SPARSEAPPLYRMSPROP_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
 *@brief Sparse apply RMSProp optimization algorithm for sparse gradients.
 *@par Inputs:
 *Nine inputs, including:
 * @li var: A ND Tensor. Must be one of the following types: float16, bfloat16, float32.
 * @li ms: A ND Tensor. Must be one of the following types: float16, bfloat16, float32.
 * @li mom: A ND Tensor. Must be one of the following types: float16, bfloat16, float32.
 * @li lr: A ND scalar Tensor. Must be one of the following types: float16, bfloat16, float32.
 * @li rho: A ND scalar Tensor. Must be one of the following types: float16, bfloat16, float32.
 * @li momentum: A ND scalar Tensor. Must be one of the following types: float16, bfloat16, float32.
 * @li epsilon: A ND scalar Tensor. Must be one of the following types: float16, bfloat16, float32.
 * @li grad: A ND Tensor. Must be one of the following types: float16, bfloat16, float32.
 * @li indices: A 1D Tensor. Must be one of the following types: int32, int64.
 *@par Outputs:
 * @li var: A ND Tensor. Must be one of the following types: float16, bfloat16, float32.
 * @li ms: A ND Tensor. Must be one of the following types: float16, bfloat16, float32.
 * @li mom: A ND Tensor. Must be one of the following types: float16, bfloat16, float32.
 *@par Attributes:
 * @li use_locking: A optional bool. Defaults to false. Whether to use mutex lock.
 *@par Third-party framework compatibility
 *Compatible with the TensorFlow operator SparseApplyRMSProp.
 */
#ifndef OPS_PROTO_DEF_SPARSEAPPLYRMSPROP
#define OPS_PROTO_DEF_SPARSEAPPLYRMSPROP
REG_OP(SparseApplyRMSProp)
    .INPUT(var, TensorType::NumberType())
    .INPUT(ms, TensorType::NumberType())
    .INPUT(mom, TensorType::NumberType())
    .INPUT(lr, TensorType::NumberType())
    .INPUT(rho, TensorType::NumberType())
    .INPUT(momentum, TensorType::NumberType())
    .INPUT(epsilon, TensorType::NumberType())
    .INPUT(grad, TensorType::NumberType())
    .INPUT(indices, TensorType::IndexNumberType())
    .OUTPUT(var, TensorType::NumberType())
    .OUTPUT(ms, TensorType::NumberType())
    .OUTPUT(mom, TensorType::NumberType())
    .ATTR(use_locking, Bool, false)
    .OP_END_FACTORY_REG(SparseApplyRMSProp)
#endif
} // namespace ge

#endif // OPS_OP_PROTO_INC_SPARSEAPPLYRMSPROP_H_
