/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file bn_infer_grad_tiling_arch35.h
 * \brief BNInferGrad Tiling — arch35 头文件
 *
 * 无状态 Tiling 函数模块（与 CANN 框架零耦合），对齐 Broadcast 范式参考算子 adam_apply_one_assign。
 */
#pragma once
#include <cstdint>
#include <vector>
#include <exe_graph/runtime/tiling_context.h>
#include "../../op_kernel/arch35/bn_infer_grad_tiling_data.h"

namespace bn_infer_grad {

// numpy 广播兼容性校验（补 1 后逐维核对）
bool CheckBroadcastShape(const std::vector<std::vector<int64_t>>& padded_in,
                         const std::vector<std::vector<int64_t>>& padded_out, int64_t max_rank);

// 去 size-1 维 + 前补 1，生成 max_bro_shape 及各输入/输出的 normal shape
bool PadAndSqueeze(const std::vector<std::vector<int64_t>>& input_shapes,
                   const std::vector<std::vector<int64_t>>& output_shapes, std::vector<int64_t>& maximum_bro_shape,
                   std::vector<std::vector<int64_t>>& normal_input_shapes,
                   std::vector<std::vector<int64_t>>& normal_output_shapes);

// UB 切分轴选择（per_buf = (UB/P)&~31）
// c_axis: 归一化 max_bro_shape 中 C 维下标；禁止选 C 为切分轴，但 C 大小仍计入 inner 累乘。C=1 时传 -1。
bool FindSplitAxis(const std::vector<int64_t>& max_bro_shape, int64_t dtype_size, int64_t ub_per_core,
                   int64_t phys_nodes, int64_t c_axis, SplitResult& out);

// 多核切分
bool MultiCoreSplit(const std::vector<int64_t>& max_bro_shape, const SplitResult& ub_split, int64_t max_cores,
                    MultiCoreResult& out);

// GM 物理 stride 预计算（size-1 轴 = 0，为广播轴）
bool PrecomputeInputStrides(const std::vector<int64_t>& s, std::vector<int64_t>& strides);
bool PrecomputeOutputStrides(const std::vector<int64_t>& s, std::vector<int64_t>& strides);

} // namespace bn_infer_grad

namespace optiling {

struct BNInferGradCompileInfo {
    uint64_t coreNum;
    uint64_t ubSize;
};

class BNInferGradTiling {
public:
    explicit BNInferGradTiling(gert::TilingContext* ctx);
    ge::graphStatus RunTiling();

private:
    ge::graphStatus ValidateTensorDescs();
    ge::graphStatus GetShapeInfo();
    template <int64_t R>
    ge::graphStatus DoTilingAndSet();

    gert::TilingContext* ctx_;
    std::vector<std::vector<int64_t>> raw_input_shapes_;
    std::vector<std::vector<int64_t>> raw_output_shapes_;
    std::vector<int64_t> max_bro_shape_;
    std::vector<std::vector<int64_t>> normal_input_shapes_;
    std::vector<std::vector<int64_t>> normal_output_shapes_;
    ge::Format data_format_ = ge::FORMAT_RESERVED;
    int64_t dtype_size_ = 0;
    int64_t rank_ = 0;
    float epsilon_ = 0.0001f;
    bool is_empty_ = false; // grads 任意维度为 0 → 空 tensor，不执行 Kernel（DESIGN.md §5.4.1）
};

} // namespace optiling
