/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file test_bn_infer_grad_tiling.cpp
 * \brief BNInferGrad Tiling UT（主线仓级范式）
 *
 * 挂载：nn_op_tiling_ut 聚合体（add_modules_ut_sources HOSTNAME ${OP_TILING_MODULE_NAME}）。
 * 框架：仓级 gert::TilingContextPara + ExecuteTiling（tests/ut/common/tiling_case_executor.*）。
 *
 * 覆盖矩阵：两 TilingKey（RANK_4 / RANK_8）× 三 dtype（fp16/fp32/bf16）
 *   + scale/batch_variance 沿 C 广播
 *   + 边界：空 tensor（某维 0）、单核小 shape、多核大 shape
 *   + 负例：dtype、format、输出描述、grads rank、scale/variance rank 与 C 长度不匹配。
 *
 * TilingKey 由 ASCENDC_TPL_SEL_PARAM(RANK) 生成，数值编码不硬编码；本 UT 通过
 * "同组一致、跨组相异" 的关系断言验证两档 RANK Key 正确分流：
 *   - grads rank 2~4（有效 rank<=4）→ RANK_4
 *   - grads rank 5（有效 rank 5，映射 R=8）→ RANK_8
 *
 * 注：BNInferGrad tiling 直接从 ctx->GetCompileInfo() 读取 coreNum/ubSize，
 *     UT 不跑 TilingParse，故构造 BNInferGradCompileInfo 通过 CompileInfo() 传入。
 */

#include <iostream>
#include <vector>
#include <gtest/gtest.h>
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"
// CompileInfo 结构与 optiling 类声明（相对交付源 op_host/arch35）
#include "../../../../op_host/arch35/bn_infer_grad_tiling_arch35.h"

namespace BNInferGradTilingUT {
using namespace std;
using namespace ge;

static const std::string OP_NAME = "BNInferGrad";

// DAV_3510：UB 248KB，核数取 32（值不影响 TilingKey 分流，仅影响切分粒度）
static constexpr uint64_t kUbSize = 248UL * 1024UL;
static constexpr uint64_t kCoreNum = 32UL;
static constexpr uint64_t kTilingDataSize = 4096UL;
static constexpr float kEpsilon = 0.0001f;

// 由运行期 vector 构造 gert::StorageShape（rank=0 时为空 shape）
static gert::StorageShape MakeStorageShape(const std::vector<int64_t>& dims)
{
    gert::StorageShape ss;
    for (auto d : dims) {
        ss.MutableOriginShape().AppendDim(d);
        ss.MutableStorageShape().AppendDim(d);
    }
    return ss;
}

// Ascend950 Vector 分支的 grads/x_backprop 支持 NCHW/NHWC；scale/batch_variance 固定为一维 FP32 ND。
// scaleLen/varLen 默认取 grads format 对应的 C 轴；负例可显式改写以触发校验。
static bool RunOneCase(const std::vector<int64_t>& gradsShape, ge::DataType gradsDtype, ge::graphStatus expectStatus,
                       TilingInfo& info, int64_t scaleLenOverride = -1, int64_t varLenOverride = -1,
                       int64_t scaleRankOverride = 1, int64_t varRankOverride = 1,
                       ge::DataType scaleDtype = ge::DT_FLOAT, ge::DataType varDtype = ge::DT_FLOAT,
                       ge::Format gradsFormat = ge::FORMAT_NCHW, ge::Format scaleFormat = ge::FORMAT_ND,
                       ge::Format varFormat = ge::FORMAT_ND, const std::vector<int64_t>& outputShapeOverride = {},
                       ge::DataType outputDtype = ge::DT_UNDEFINED, ge::Format outputFormat = ge::FORMAT_RESERVED,
                       ge::Format gradsOriginFormat = ge::FORMAT_NCHW,
                       ge::Format scaleOriginFormat = ge::FORMAT_RESERVED,
                       ge::Format varOriginFormat = ge::FORMAT_RESERVED,
                       ge::Format outputOriginFormat = ge::FORMAT_RESERVED)
{
    int64_t channels = 1;
    if (gradsShape.size() >= 2) {
        channels = gradsFormat == ge::FORMAT_NHWC ? gradsShape.back() : gradsShape[1];
    }
    int64_t scaleLen = (scaleLenOverride >= 0) ? scaleLenOverride : channels;
    int64_t varLen = (varLenOverride >= 0) ? varLenOverride : channels;

    // scale / batch_variance 的 shape：默认 rank1 [C]；负例可构造 rank2 触发 rank 校验。
    std::vector<int64_t> scaleDims = (scaleRankOverride == 1) ? std::vector<int64_t>{scaleLen} :
                                                                std::vector<int64_t>{scaleLen, 1};
    std::vector<int64_t> varDims = (varRankOverride == 1) ? std::vector<int64_t>{varLen} :
                                                            std::vector<int64_t>{varLen, 1};

    gert::StorageShape gShape = MakeStorageShape(gradsShape);
    gert::StorageShape sShape = MakeStorageShape(scaleDims);
    gert::StorageShape vShape = MakeStorageShape(varDims);

    // 3 输入：grads(dtype), scale(fp32), batch_variance(fp32)
    const ge::Format resolvedScaleOrigin = scaleOriginFormat == ge::FORMAT_RESERVED ? scaleFormat : scaleOriginFormat;
    const ge::Format resolvedVarOrigin = varOriginFormat == ge::FORMAT_RESERVED ? varFormat : varOriginFormat;
    std::vector<gert::TilingContextPara::TensorDescription> inputs = {
        {gShape, gradsDtype, gradsFormat, false, nullptr, gradsOriginFormat},   // grads
        {sShape, scaleDtype, scaleFormat, false, nullptr, resolvedScaleOrigin}, // scale
        {vShape, varDtype, varFormat, false, nullptr, resolvedVarOrigin},       // batch_variance
    };
    // 1 输出：x_backprop（与 grads 同 shape/同 dtype）
    gert::StorageShape outputShape = outputShapeOverride.empty() ? gShape : MakeStorageShape(outputShapeOverride);
    ge::DataType resolvedOutputDtype = outputDtype == ge::DT_UNDEFINED ? gradsDtype : outputDtype;
    ge::Format resolvedOutputFormat = outputFormat == ge::FORMAT_RESERVED ? gradsFormat : outputFormat;
    ge::Format resolvedOutputOrigin = outputOriginFormat == ge::FORMAT_RESERVED ? gradsOriginFormat :
                                                                                  outputOriginFormat;
    std::vector<gert::TilingContextPara::TensorDescription> outputs = {
        {outputShape, resolvedOutputDtype, resolvedOutputFormat, false, nullptr, resolvedOutputOrigin},
    };
    // 属性：epsilon(0)
    std::vector<gert::TilingContextPara::OpAttr> attrs = {
        {"epsilon", Ops::NN::AnyValue::CreateFrom<float>(kEpsilon)},
    };

    // GetShapeInfo/DoTilingAndSet 直接读取该 compileInfo（UT 不跑 TilingParse）
    optiling::BNInferGradCompileInfo compileInfo{kCoreNum, kUbSize};

    gert::TilingContextPara para(OP_NAME, inputs, outputs, attrs, &compileInfo, kCoreNum, kUbSize, kTilingDataSize);

    bool ok = ExecuteTiling(para, info);
    if (expectStatus == ge::GRAPH_SUCCESS) {
        EXPECT_TRUE(ok) << "tiling should succeed for the given case";
    } else {
        EXPECT_FALSE(ok) << "tiling should fail for the given case";
    }
    return ok;
}

class BNInferGradTilingTest : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "BNInferGradTilingTest SetUp." << std::endl; }
    static void TearDownTestCase() { std::cout << "BNInferGradTilingTest TearDown." << std::endl; }
};

// ---------------------------------------------------------------------------
// RANK_4 组：grads rank 2~4，三 dtype
// ---------------------------------------------------------------------------
TEST_F(BNInferGradTilingTest, Rank4_Fp32_2D)
{
    TilingInfo info;
    ASSERT_TRUE(RunOneCase({4, 8}, ge::DT_FLOAT, ge::GRAPH_SUCCESS, info));
    EXPECT_GE(info.blockNum, 1u);
    EXPECT_NE(info.tilingKey, -1);
}

TEST_F(BNInferGradTilingTest, Rank4_Fp16_3D)
{
    TilingInfo info;
    ASSERT_TRUE(RunOneCase({2, 16, 5}, ge::DT_FLOAT16, ge::GRAPH_SUCCESS, info));
    EXPECT_GE(info.blockNum, 1u);
}

TEST_F(BNInferGradTilingTest, Rank4_Bf16_4D)
{
    TilingInfo info;
    ASSERT_TRUE(RunOneCase({4, 32, 14, 14}, ge::DT_BF16, ge::GRAPH_SUCCESS, info));
    EXPECT_GE(info.blockNum, 1u);
}

// ---------------------------------------------------------------------------
// RANK_8 组：grads rank 5（有效 rank 5 → 映射 R=8）
// ---------------------------------------------------------------------------
TEST_F(BNInferGradTilingTest, Rank8_Fp32_5D)
{
    TilingInfo info;
    ASSERT_TRUE(RunOneCase({2, 8, 3, 5, 7}, ge::DT_FLOAT, ge::GRAPH_SUCCESS, info));
    EXPECT_GE(info.blockNum, 1u);
}

TEST_F(BNInferGradTilingTest, Rank8_Fp16_5D)
{
    TilingInfo info;
    ASSERT_TRUE(RunOneCase({2, 16, 2, 4, 5}, ge::DT_FLOAT16, ge::GRAPH_SUCCESS, info));
    EXPECT_GE(info.blockNum, 1u);
}

TEST_F(BNInferGradTilingTest, Rank8_Bf16_5D)
{
    TilingInfo info;
    ASSERT_TRUE(RunOneCase({3, 8, 2, 3, 4}, ge::DT_BF16, ge::GRAPH_SUCCESS, info));
    EXPECT_GE(info.blockNum, 1u);
}

// ---------------------------------------------------------------------------
// TilingKey 分流关系：同组一致、跨组相异
// ---------------------------------------------------------------------------
TEST_F(BNInferGradTilingTest, TilingKey_RankGroupDispatch)
{
    TilingInfo r4a, r4b, r8a, r8b;
    ASSERT_TRUE(RunOneCase({4, 8}, ge::DT_FLOAT, ge::GRAPH_SUCCESS, r4a));             // rank2 -> RANK_4
    ASSERT_TRUE(RunOneCase({4, 32, 14, 14}, ge::DT_BF16, ge::GRAPH_SUCCESS, r4b));     // rank4 -> RANK_4
    ASSERT_TRUE(RunOneCase({2, 8, 3, 5, 7}, ge::DT_FLOAT, ge::GRAPH_SUCCESS, r8a));    // rank5 -> RANK_8
    ASSERT_TRUE(RunOneCase({2, 16, 2, 4, 5}, ge::DT_FLOAT16, ge::GRAPH_SUCCESS, r8b)); // rank5 -> RANK_8

    EXPECT_EQ(r4a.tilingKey, r4b.tilingKey) << "grads rank<=4 用例应命中同一 RANK_4 Key";
    EXPECT_EQ(r8a.tilingKey, r8b.tilingKey) << "grads rank5 用例应命中同一 RANK_8 Key";
    EXPECT_NE(r4a.tilingKey, r8a.tilingKey) << "RANK_4 与 RANK_8 应为不同 TilingKey";
}

// ---------------------------------------------------------------------------
// 广播：scale/batch_variance [C] 沿非 C 轴广播到 grads
// ---------------------------------------------------------------------------
TEST_F(BNInferGradTilingTest, Broadcast_ChannelScaleVariance)
{
    TilingInfo info;
    // grads [8,4,6,6]，C=4；scale/variance=[4] 广播。tiling 内部 reshape 为 [1,4,1,1]。
    ASSERT_TRUE(RunOneCase({8, 4, 6, 6}, ge::DT_FLOAT, ge::GRAPH_SUCCESS, info));
    EXPECT_GE(info.blockNum, 1u);
}

TEST_F(BNInferGradTilingTest, Broadcast_NhwcChannelScaleVariance)
{
    TilingInfo info;
    ASSERT_TRUE(RunOneCase({2, 3, 4, 8}, ge::DT_FLOAT, ge::GRAPH_SUCCESS, info, -1, -1, 1, 1, ge::DT_FLOAT,
                           ge::DT_FLOAT, ge::FORMAT_NHWC, ge::FORMAT_ND, ge::FORMAT_ND, {}, ge::DT_UNDEFINED,
                           ge::FORMAT_RESERVED, ge::FORMAT_NHWC));
}

// ---------------------------------------------------------------------------
// 边界：空 tensor（某维为 0）→ is_empty，total_tiles=0，block_dim 保底 1，SUCCESS
// ---------------------------------------------------------------------------
TEST_F(BNInferGradTilingTest, Boundary_EmptyTensor_N0)
{
    TilingInfo info;
    ASSERT_TRUE(RunOneCase({0, 8}, ge::DT_FLOAT, ge::GRAPH_SUCCESS, info));
    EXPECT_GE(info.blockNum, 1u); // launch 要求 block_dim >= 1
}

TEST_F(BNInferGradTilingTest, Boundary_EmptyTensor_Inner0)
{
    TilingInfo info;
    ASSERT_TRUE(RunOneCase({2, 8, 0, 5}, ge::DT_FLOAT16, ge::GRAPH_SUCCESS, info));
    EXPECT_GE(info.blockNum, 1u);
}

// ---------------------------------------------------------------------------
// 大 shape：多核切分（total_tiles > 核数）
// ---------------------------------------------------------------------------
TEST_F(BNInferGradTilingTest, LargeShape_MultiCore)
{
    TilingInfo info;
    ASSERT_TRUE(RunOneCase({256, 64, 28, 28}, ge::DT_FLOAT, ge::GRAPH_SUCCESS, info));
    EXPECT_GE(info.blockNum, 1u);
}

// ---------------------------------------------------------------------------
// 负例：grads rank<2 应被拒绝（GetShapeInfo grads_rank<2 校验）
// ---------------------------------------------------------------------------
TEST_F(BNInferGradTilingTest, Reject_GradsRankTooSmall)
{
    TilingInfo info;
    ASSERT_FALSE(RunOneCase({16}, ge::DT_FLOAT, ge::GRAPH_FAILED, info,
                            /*scaleLen*/ 16, /*varLen*/ 16));
}

// ---------------------------------------------------------------------------
// 负例：grads rank>5 应被拒绝（GetShapeInfo grads_rank>5 校验）
// ---------------------------------------------------------------------------
TEST_F(BNInferGradTilingTest, Reject_GradsRankTooLarge)
{
    TilingInfo info;
    ASSERT_FALSE(RunOneCase({2, 4, 2, 3, 2, 2}, ge::DT_FLOAT, ge::GRAPH_FAILED, info));
}

// ---------------------------------------------------------------------------
// 负例：scale 非 rank1（rank2）应被拒绝
// ---------------------------------------------------------------------------
TEST_F(BNInferGradTilingTest, Reject_ScaleNotRank1)
{
    TilingInfo info;
    ASSERT_FALSE(RunOneCase({4, 8}, ge::DT_FLOAT, ge::GRAPH_FAILED, info,
                            /*scaleLen*/ 8, /*varLen*/ 8, /*scaleRank*/ 2, /*varRank*/ 1));
}

// ---------------------------------------------------------------------------
// 负例：batch_variance 非 rank1（rank2）应被拒绝
// ---------------------------------------------------------------------------
TEST_F(BNInferGradTilingTest, Reject_VarianceNotRank1)
{
    TilingInfo info;
    ASSERT_FALSE(RunOneCase({4, 8}, ge::DT_FLOAT, ge::GRAPH_FAILED, info,
                            /*scaleLen*/ 8, /*varLen*/ 8, /*scaleRank*/ 1, /*varRank*/ 2));
}

// ---------------------------------------------------------------------------
// 负例：scale 长度 != grads C 应被拒绝
// ---------------------------------------------------------------------------
TEST_F(BNInferGradTilingTest, Reject_ScaleChannelMismatch)
{
    TilingInfo info;
    // grads C=8，但 scale 长度给 7 → 不匹配
    ASSERT_FALSE(RunOneCase({4, 8}, ge::DT_FLOAT, ge::GRAPH_FAILED, info,
                            /*scaleLen*/ 7, /*varLen*/ 8));
}

// ---------------------------------------------------------------------------
// 负例：batch_variance 长度 != grads C 应被拒绝
// ---------------------------------------------------------------------------
TEST_F(BNInferGradTilingTest, Reject_VarianceChannelMismatch)
{
    TilingInfo info;
    ASSERT_FALSE(RunOneCase({4, 8}, ge::DT_FLOAT, ge::GRAPH_FAILED, info,
                            /*scaleLen*/ 8, /*varLen*/ 5));
}

TEST_F(BNInferGradTilingTest, Reject_GradsDtypeUnsupported)
{
    TilingInfo info;
    ASSERT_FALSE(RunOneCase({4, 8}, ge::DT_INT8, ge::GRAPH_FAILED, info));
}

TEST_F(BNInferGradTilingTest, Reject_ScaleDtypeUnsupported)
{
    TilingInfo info;
    ASSERT_FALSE(RunOneCase({4, 8}, ge::DT_FLOAT, ge::GRAPH_FAILED, info, -1, -1, 1, 1, ge::DT_FLOAT16));
}

TEST_F(BNInferGradTilingTest, Reject_VarianceDtypeUnsupported)
{
    TilingInfo info;
    ASSERT_FALSE(RunOneCase({4, 8}, ge::DT_FLOAT, ge::GRAPH_FAILED, info, -1, -1, 1, 1, ge::DT_FLOAT, ge::DT_FLOAT16));
}

TEST_F(BNInferGradTilingTest, Reject_Nc1hwc0FormatOnAscend950)
{
    TilingInfo info;
    ASSERT_FALSE(RunOneCase({4, 8}, ge::DT_FLOAT, ge::GRAPH_FAILED, info, -1, -1, 1, 1, ge::DT_FLOAT, ge::DT_FLOAT,
                            ge::FORMAT_NC1HWC0));
}

TEST_F(BNInferGradTilingTest, Reject_ScaleFormatNotNd)
{
    TilingInfo info;
    ASSERT_FALSE(RunOneCase({2, 8, 4, 4}, ge::DT_FLOAT, ge::GRAPH_FAILED, info, -1, -1, 1, 1, ge::DT_FLOAT,
                            ge::DT_FLOAT, ge::FORMAT_NCHW, ge::FORMAT_NHWC));
}

TEST_F(BNInferGradTilingTest, Reject_VarianceFormatNotNd)
{
    TilingInfo info;
    ASSERT_FALSE(RunOneCase({2, 8, 4, 4}, ge::DT_FLOAT, ge::GRAPH_FAILED, info, -1, -1, 1, 1, ge::DT_FLOAT,
                            ge::DT_FLOAT, ge::FORMAT_NCHW, ge::FORMAT_ND, ge::FORMAT_NHWC));
}

TEST_F(BNInferGradTilingTest, Reject_OutputShapeMismatch)
{
    TilingInfo info;
    ASSERT_FALSE(RunOneCase({4, 8}, ge::DT_FLOAT, ge::GRAPH_FAILED, info, -1, -1, 1, 1, ge::DT_FLOAT, ge::DT_FLOAT,
                            ge::FORMAT_NCHW, ge::FORMAT_ND, ge::FORMAT_ND, {1, 8}));
}

TEST_F(BNInferGradTilingTest, Reject_OutputDtypeMismatch)
{
    TilingInfo info;
    ASSERT_FALSE(RunOneCase({4, 8}, ge::DT_FLOAT, ge::GRAPH_FAILED, info, -1, -1, 1, 1, ge::DT_FLOAT, ge::DT_FLOAT,
                            ge::FORMAT_NCHW, ge::FORMAT_ND, ge::FORMAT_ND, {}, ge::DT_FLOAT16));
}

TEST_F(BNInferGradTilingTest, Reject_OutputFormatUnsupported)
{
    TilingInfo info;
    ASSERT_FALSE(RunOneCase({4, 8}, ge::DT_FLOAT, ge::GRAPH_FAILED, info, -1, -1, 1, 1, ge::DT_FLOAT, ge::DT_FLOAT,
                            ge::FORMAT_NCHW, ge::FORMAT_ND, ge::FORMAT_ND, {}, ge::DT_UNDEFINED, ge::FORMAT_NC1HWC0));
}

} // namespace BNInferGradTilingUT
