/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file fused_bias_leaky_relu.h
 * \brief FusedBiasLeakyRelu kernel class definition (arch35)
 *
 * Computes: y = LeakyRelu(x + bias, negative_slope) * scale
 *
 * FP16 path: Cast → FP32 compute → Cast back to FP16
 * FP32 path: native FP32 compute
 */
#ifndef FUSED_BIAS_LEAKY_RELU_H
#define FUSED_BIAS_LEAKY_RELU_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "fused_bias_leaky_relu_tiling_data.h"
#include "fused_bias_leaky_relu_tiling_key.h"

namespace NsFusedBiasLeakyRelu {

using namespace AscendC;

constexpr int64_t BUFFER_MODE_SINGLE = 1;
constexpr int64_t BUFFER_MODE_DOUBLE = 2;

template <typename T, int BUFFER_MODE>
class FusedBiasLeakyRelu {
    static constexpr int32_t BUFFER_NUM = BUFFER_MODE ? BUFFER_MODE_DOUBLE : BUFFER_MODE_SINGLE;
    static constexpr bool NEED_CAST = !std::is_same_v<T, float>;
    using T_COMPUTE = float;

public:
    __aicore__ inline FusedBiasLeakyRelu(){};

    __aicore__ inline void Init(GM_ADDR x, GM_ADDR bias, GM_ADDR y, const FusedBiasLeakyReluTilingData* tilingData);
    __aicore__ inline void Process();

private:
    __aicore__ inline void CopyIn(int64_t progress, int64_t currentNum);
    __aicore__ inline void Compute(int64_t currentNum);
    __aicore__ inline void CopyOut(int64_t progress, int64_t currentNum);

private:
    TPipe pipe;
    TQue<QuePosition::VECIN, BUFFER_NUM> inputQueueX;
    TQue<QuePosition::VECIN, BUFFER_NUM> inputQueueBias;
    TQue<QuePosition::VECOUT, BUFFER_NUM> outputQueueY;
    TBuf<TPosition::VECCALC> xFp32Buf_;
    TBuf<TPosition::VECCALC> biasFp32Buf_;
    TBuf<TPosition::VECCALC> yFp32Buf_;

    GlobalTensor<T> inputGMX;
    GlobalTensor<T> inputGMBias;
    GlobalTensor<T> outputGMY;

    int64_t blockLength_ = 0;
    int64_t ubLength_ = 0;
    int64_t loopCount_ = 0;
    int64_t tailNum_ = 0;
    float negativeSlope_;
    float scale_;
};

template <typename T, int BUFFER_MODE>
__aicore__ inline void FusedBiasLeakyRelu<T, BUFFER_MODE>::Init(GM_ADDR x, GM_ADDR bias, GM_ADDR y,
                                                                const FusedBiasLeakyReluTilingData* tilingData)
{
    int64_t blockOffset = GetBlockIdx() * tilingData->blockFactor;
    int64_t remainderLength = tilingData->totalNum - blockOffset;
    blockLength_ = (remainderLength > tilingData->blockFactor) ? tilingData->blockFactor : remainderLength;

    ubLength_ = tilingData->ubFactor;
    if (ubLength_ <= 0) {
        blockLength_ = 0;
        loopCount_ = 0;
        tailNum_ = 0;
    } else {
        loopCount_ = blockLength_ / ubLength_;
        tailNum_ = blockLength_ % ubLength_;
    }

    negativeSlope_ = tilingData->negativeSlope;
    scale_ = tilingData->scale;

    inputGMX.SetGlobalBuffer((__gm__ T*)x + blockOffset, blockLength_);
    inputGMBias.SetGlobalBuffer((__gm__ T*)bias + blockOffset, blockLength_);
    outputGMY.SetGlobalBuffer((__gm__ T*)y + blockOffset, blockLength_);

    int64_t allocElems = ubLength_;
    pipe.InitBuffer(inputQueueX, BUFFER_NUM, allocElems * sizeof(T));
    pipe.InitBuffer(inputQueueBias, BUFFER_NUM, allocElems * sizeof(T));
    pipe.InitBuffer(outputQueueY, BUFFER_NUM, allocElems * sizeof(T));
    if constexpr (NEED_CAST) {
        pipe.InitBuffer(xFp32Buf_, allocElems * sizeof(T_COMPUTE));
        pipe.InitBuffer(biasFp32Buf_, allocElems * sizeof(T_COMPUTE));
        pipe.InitBuffer(yFp32Buf_, allocElems * sizeof(T_COMPUTE));
    }
}

template <typename T, int BUFFER_MODE>
__aicore__ inline void FusedBiasLeakyRelu<T, BUFFER_MODE>::Process()
{
    if (blockLength_ <= 0) {
        return;
    }
    for (int64_t i = 0; i < loopCount_; i++) {
        CopyIn(i, ubLength_);
        Compute(ubLength_);
        CopyOut(i, ubLength_);
    }
    if (tailNum_ > 0) {
        CopyIn(loopCount_, tailNum_);
        Compute(tailNum_);
        CopyOut(loopCount_, tailNum_);
    }
}

template <typename T, int BUFFER_MODE>
__aicore__ inline void FusedBiasLeakyRelu<T, BUFFER_MODE>::CopyIn(int64_t progress, int64_t currentNum)
{
    LocalTensor<T> xLocal = inputQueueX.template AllocTensor<T>();
    LocalTensor<T> biasLocal = inputQueueBias.template AllocTensor<T>();
    DataCopyExtParams copyParams;
    copyParams.blockCount = 1;
    copyParams.blockLen = static_cast<uint32_t>(currentNum * sizeof(T));
    copyParams.srcStride = 0;
    copyParams.dstStride = 0;
    DataCopyPadExtParams<T> padParams{false, 0, 0, 0};
    DataCopyPad(xLocal, inputGMX[progress * ubLength_], copyParams, padParams);
    DataCopyPad(biasLocal, inputGMBias[progress * ubLength_], copyParams, padParams);
    inputQueueX.EnQue(xLocal);
    inputQueueBias.EnQue(biasLocal);
}

template <typename T, int BUFFER_MODE>
__aicore__ inline void FusedBiasLeakyRelu<T, BUFFER_MODE>::Compute(int64_t currentNum)
{
    LocalTensor<T> xLocal = inputQueueX.template DeQue<T>();
    LocalTensor<T> biasLocal = inputQueueBias.template DeQue<T>();
    LocalTensor<T> yLocal = outputQueueY.template AllocTensor<T>();

    if constexpr (NEED_CAST) {
        LocalTensor<T_COMPUTE> xFp32 = xFp32Buf_.Get<T_COMPUTE>();
        LocalTensor<T_COMPUTE> biasFp32 = biasFp32Buf_.Get<T_COMPUTE>();
        LocalTensor<T_COMPUTE> yFp32 = yFp32Buf_.Get<T_COMPUTE>();

        Cast(xFp32, xLocal, RoundMode::CAST_NONE, currentNum);
        Cast(biasFp32, biasLocal, RoundMode::CAST_NONE, currentNum);

        Add(xFp32, xFp32, biasFp32, currentNum);
        LeakyRelu(xFp32, xFp32, negativeSlope_, currentNum);
        Muls(yFp32, xFp32, scale_, currentNum);

        Cast(yLocal, yFp32, RoundMode::CAST_ROUND, currentNum);
    } else {
        Add(xLocal, xLocal, biasLocal, currentNum);
        LeakyRelu(xLocal, xLocal, negativeSlope_, currentNum);
        Muls(yLocal, xLocal, scale_, currentNum);
    }

    outputQueueY.EnQue(yLocal);
    inputQueueX.FreeTensor(xLocal);
    inputQueueBias.FreeTensor(biasLocal);
}

template <typename T, int BUFFER_MODE>
__aicore__ inline void FusedBiasLeakyRelu<T, BUFFER_MODE>::CopyOut(int64_t progress, int64_t currentNum)
{
    LocalTensor<T> yLocal = outputQueueY.template DeQue<T>();
    DataCopyExtParams copyParams;
    copyParams.blockCount = 1;
    copyParams.blockLen = static_cast<uint32_t>(currentNum * sizeof(T));
    copyParams.srcStride = 0;
    copyParams.dstStride = 0;
    DataCopyPad(outputGMY[progress * ubLength_], yLocal, copyParams);
    outputQueueY.FreeTensor(yLocal);
}

} // namespace NsFusedBiasLeakyRelu
#endif // FUSED_BIAS_LEAKY_RELU_H
