#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.

# Generated By CANNBot

"""
avg_pool1_d Kernel UT 数据生成脚本。

参数: shape_str dtype ksize strides pads_str ceil_mode count_include_pad
  - shape_str:           输入 shape，如 '(1, 3, 8)'
  - dtype:               'float32' 或 'float16'
  - ksize:               池化窗口大小
  - strides:             滑动步长
  - pads_str:            padding，逗号分隔，如 '1,1'
  - ceil_mode:           0=False, 1=True
  - count_include_pad:   0=False, 1=True

Golden 实现与 op_kernel ProcessOneElement 逻辑严格对齐（float32 累加 + 除以 divisor）。
"""

import sys
import os
import numpy as np


def parse_str_to_shape_list(shape_str):
    shape_str = shape_str.strip("(").strip(")")
    shape_list = [int(x) for x in shape_str.split(",")]
    return tuple(shape_list)


def parse_pads(pads_str):
    parts = [int(x) for x in pads_str.split(",")]
    if len(parts) != 2:
        raise ValueError(f"pads must have 2 elements, got {len(parts)}")
    return parts[0], parts[1]


def compute_l_out(L, ksize, strides, pad_left, pad_right, ceil_mode):
    """SE §5.2 / MDE §3.2 ComputeLOut — 与 op_host tiling.cpp 一致"""
    if L == 0:
        return 0
    L_padded = L + pad_left + pad_right
    if ceil_mode:
        l_out = (L_padded - ksize + strides - 1) // strides + 1
    else:
        l_out = (L_padded - ksize) // strides + 1
    if pad_left > 0 and (l_out - 1) * strides >= L + pad_left:
        l_out -= 1
    return max(l_out, 0)


def avg_pool1_d_golden_numpy(
    x, ksize, strides, pad_left, pad_right, ceil_mode, count_include_pad
):
    """
    纯 numpy golden 实现，与 kernel ProcessOneElement 逻辑一致。
    count_include_pad:
      True  -> end = min(end, L_padded); divisor = end - start; sum 含 padding(0)
      False -> start = max(start, pad_left); end = min(end, L+pad_left); divisor = end - start
    累加在 float32 精度下进行（与 kernel 一致）。
    """
    orig_ndim = x.ndim
    if orig_ndim == 2:
        x = x[np.newaxis, ...]
    elif orig_ndim > 3:
        front_shape = list(x.shape[:-1])
        x = x.reshape(-1, 1, x.shape[-1])

    N, C, L = x.shape
    L_padded = L + pad_left + pad_right
    L_out = compute_l_out(L, ksize, strides, pad_left, pad_right, ceil_mode)

    if L_out == 0:
        y_shape = list(x.shape)
        y_shape[-1] = 0
        y = np.zeros(y_shape, dtype=x.dtype)
        if orig_ndim == 2:
            y = y[0]
        elif orig_ndim > 3:
            y = y.reshape(*front_shape, 0)
        return y

    # 构建 padded 输入（float32 精度，padding 区为 0）
    x_f32 = x.astype(np.float32)
    x_padded = np.zeros((N, C, L_padded), dtype=np.float32)
    x_padded[:, :, pad_left : pad_left + L] = x_f32

    y_f32 = np.zeros((N, C, L_out), dtype=np.float32)
    for w in range(L_out):
        start = strides * w
        end = start + ksize
        if count_include_pad:
            if end > L_padded:
                end = L_padded
        else:
            if start < pad_left:
                start = pad_left
            valid_end = L + pad_left
            if end > valid_end:
                end = valid_end
        divisor = end - start
        if divisor <= 0:
            divisor = 1
        window = x_padded[:, :, start:end]
        sum_val = window.sum(axis=-1)
        y_f32[:, :, w] = sum_val / float(divisor)

    y = y_f32.astype(x.dtype)
    if orig_ndim == 2:
        y = y[0]
    elif orig_ndim > 3:
        y = y.reshape(*front_shape, L_out)
    return y


def gen_data_and_golden(
    shape_str, d_type, ksize, strides, pads_str, ceil_mode, count_include_pad
):
    d_type_dict = {"float32": np.float32, "float16": np.float16}
    np_type = d_type_dict[d_type]
    shape = parse_str_to_shape_list(shape_str)
    size = int(np.prod(shape))

    # 随机数据 [-1, 1] 范围，适合 avg_pool1_d 除法运算
    tmp_input = np.random.uniform(-1.0, 1.0, size=size).reshape(shape).astype(np_type)

    pad_left, pad_right = parse_pads(pads_str)
    tmp_golden = avg_pool1_d_golden_numpy(
        tmp_input,
        int(ksize),
        int(strides),
        pad_left,
        pad_right,
        bool(int(ceil_mode)),
        bool(int(count_include_pad)),
    )

    tmp_input.astype(np_type).tofile(f"{d_type}_input_avg_pool1_d.bin")
    tmp_golden.astype(np_type).tofile(f"{d_type}_golden_avg_pool1_d.bin")


if __name__ == "__main__":
    if len(sys.argv) != 8:
        print(
            "Param num must be 8: shape dtype ksize strides pads ceil_mode count_include_pad"
        )
        exit(1)
    os.system("rm -rf *.bin")
    gen_data_and_golden(
        sys.argv[1],
        sys.argv[2],
        sys.argv[3],
        sys.argv[4],
        sys.argv[5],
        sys.argv[6],
        sys.argv[7],
    )
