/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

/*!
 * \file avg_pool1_d_infershape.cpp
 * \brief infer shape for avg_pool1_d (SE §6.4)
 */
#include "register/op_impl_registry.h"
#include "log/log.h"
#include "util/shape_util.h"
#include <string>

using namespace ge;

namespace ops {

constexpr int32_t IDX_X = 0;
constexpr int32_t IDX_Y = 0;
constexpr int64_t UNKNOWN_DIM = -1;
constexpr int64_t MIN_RANK = 3;     // SE §5.4: x rank >= 3
constexpr int64_t MAX_RANK = 8;     // ND 格式维度上限 8D
constexpr size_t PAD_LIST_SIZE = 2; // SE §2.4: pads 长度必须为 2

static int64_t ComputeLOut(int64_t L, int64_t ksize, int64_t strides, int64_t padLeft, int64_t padRight, bool ceilMode)
{
    if (L == 0) {
        return 0;
    }
    int64_t LOut;
    if (ceilMode) {
        LOut = (L + padLeft + padRight - ksize + strides - 1) / strides + 1;
    } else {
        LOut = (L + padLeft + padRight - ksize) / strides + 1;
    }
    if (padLeft > 0 && (LOut - 1) * strides >= L + padLeft) {
        LOut -= 1;
    }
    if (LOut < 0) {
        LOut = 0;
    }
    return LOut;
}

static ge::graphStatus InferShapeAvgPool1D(gert::InferShapeContext* context)
{
    OP_LOGD(context->GetNodeName(), "Begin to do InferShapeAvgPool1D");

    const gert::Shape* xShape = context->GetInputShape(IDX_X);
    OP_CHECK_NULL_WITH_CONTEXT(context, xShape);
    gert::Shape* yShape = context->GetOutputShape(IDX_Y);
    OP_CHECK_NULL_WITH_CONTEXT(context, yShape);

    // Unknown rank: 输出也为 unknown rank
    if (Ops::Base::IsUnknownRank(*xShape)) {
        Ops::Base::SetUnknownRank(*yShape);
        return ge::GRAPH_SUCCESS;
    }

    int64_t dimNum = static_cast<int64_t>(xShape->GetDimNum());
    // SE §5.4 ND改造: 维度 >= 3（3D 输入 (N, C, L)）
    OP_CHECK_IF(dimNum < MIN_RANK,
                OP_LOGE_FOR_INVALID_SHAPEDIMS_WITH_REASON(context->GetNodeName(), "x", std::to_string(dimNum).c_str(),
                                                          "rank must be >= 3"),
                return ge::GRAPH_FAILED);
    // ND 格式维度上限 8D
    OP_CHECK_IF(dimNum > MAX_RANK,
                OP_LOGE_FOR_INVALID_SHAPEDIMS_WITH_REASON(context->GetNodeName(), "x", std::to_string(dimNum).c_str(),
                                                          "rank must be <= 8 for ND format"),
                return ge::GRAPH_FAILED);

    // 获取属性
    auto attrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, attrs);
    const auto* ksizePtr = attrs->GetAttrPointer<int64_t>(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, ksizePtr);
    int64_t ksize = *ksizePtr;
    const auto* stridesPtr = attrs->GetAttrPointer<int64_t>(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, stridesPtr);
    int64_t strides = *stridesPtr;
    const auto* padsVec = attrs->GetAttrPointer<gert::ContinuousVector>(2);
    OP_CHECK_NULL_WITH_CONTEXT(context, padsVec);
    // SE §2.4: pads 长度必须为 2
    OP_CHECK_IF(
        padsVec->GetSize() != PAD_LIST_SIZE,
        OP_LOGE_FOR_INVALID_LISTSIZE(context->GetNodeName(), "pads", std::to_string(padsVec->GetSize()).c_str(), "2"),
        return ge::GRAPH_FAILED);
    const int64_t* pads = static_cast<const int64_t*>(padsVec->GetData());
    OP_CHECK_NULL_WITH_CONTEXT(context, pads);
    int64_t padLeft = pads[0];
    int64_t padRight = pads[1];

    const auto* ceilModePtr = attrs->GetAttrPointer<bool>(3);
    bool ceilMode = (ceilModePtr != nullptr) ? *ceilModePtr : false;

    // 校验属性值域（SE §2.4 / §6.3）
    OP_CHECK_IF(ksize < 1,
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "ksize", std::to_string(ksize).c_str(), ">= 1"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(strides < 1,
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "strides", std::to_string(strides).c_str(), ">= 1"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(padLeft < 0 || padRight < 0,
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(
                    context->GetNodeName(), "pads",
                    ("[" + std::to_string(padLeft) + ", " + std::to_string(padRight) + "]").c_str(),
                    "pads elements must be >= 0"),
                return ge::GRAPH_FAILED);

    // 计算 L_out（SE §6.4 公式）
    // 注意：infershape 阶段 L 可能是 UNKNOWN_DIM(-1)，不校验 L 值
    int64_t L = xShape->GetDim(static_cast<size_t>(dimNum - 1));
    int64_t LOut = ComputeLOut(L, ksize, strides, padLeft, padRight, ceilMode);

    // 设置输出 shape：与输入相同，仅最后一维替换为 L_out
    yShape->SetDimNum(static_cast<size_t>(dimNum));
    for (int64_t i = 0; i < dimNum; i++) {
        int64_t srcDim = xShape->GetDim(static_cast<size_t>(i));
        if (i == dimNum - 1) {
            yShape->SetDim(static_cast<size_t>(i), (srcDim == UNKNOWN_DIM) ? UNKNOWN_DIM : LOut);
        } else {
            yShape->SetDim(static_cast<size_t>(i), srcDim);
        }
    }

    OP_LOGD(context->GetNodeName(), "End to do InferShapeAvgPool1D, L_out=%ld", LOut);
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_INFERSHAPE(AvgPool1D).InferShape(InferShapeAvgPool1D);
} // namespace ops
