/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#ifndef OPS_BUILT_IN_OP_PROTO_INC_INPLACE_APPLY_PROXIMAL_ADAGRAD_H_
#define OPS_BUILT_IN_OP_PROTO_INC_INPLACE_APPLY_PROXIMAL_ADAGRAD_H_

#include "graph/operator_reg.h"
namespace ge {
/**
 *@brief Inplace update "var" and "accum" according to FOBOS (Forward-Backward Splitting)
 *   with Adagrad learning rate. \n
 * @code{.c}
 *   accum_new = accum + grad * grad
 *   eta = lr / sqrt(accum_new)
 *   prox = var - eta * grad
 *   if l1 > 0:
 *       var_new = sign(prox) * max(|prox| - eta * l1, 0) / (1 + eta * l2)
 *   else:
 *       var_new = prox / (1 + eta * l2)
 *   var = var_new
 *   accum = accum_new
 * @endcode
 *
 *@par Inputs:
 *Six inputs, including:
 * @li var: A mutable tensor. Must be one of FLOAT32/FLOAT16/BF16. ND format.
 *    Should be from a Variable().
 * @li accum: A mutable tensor. Has the same type and shape as "var". ND format.
 *    Should be from a Variable().
 * @li lr: A scalar tensor. Has the same type as "var". ND format.
 *    Learning rate scaling factor.
 * @li l1: A scalar tensor. Has the same type as "var". ND format.
 *    L1 regularization strength.
 * @li l2: A scalar tensor. Has the same type as "var". ND format.
 *    L2 regularization strength.
 * @li grad: A tensor for the gradient. Has the same type and shape as "var". ND format. \n

 *@par Attributes:
 * @li use_locking: An optional bool. Defaults to "False".
 *    If "True", updating of the "var" and "accum" tensors will be protected by a lock;
 *    otherwise the behavior is undefined, but may exhibit less contention. \n

 *@par Outputs:
 *Two outputs, including:
 * @li var: A mutable tensor. Has the same type and shape as input "var".
 *    Inplace alias of input var. ND format.
 * @li accum: A mutable tensor. Has the same type and shape as input "accum".
 *    Inplace alias of input accum. ND format. \n

 *@attention Constraints:
 * @li The input tensors var/accum/grad must have the same shape.
 * @li All input tensors (var/accum/lr/l1/l2/grad) must have the same data type.
 *
 *@par Third-party framework compatibility
 *Compatible with the TensorFlow operator ApplyProximalAdagrad.
 */
REG_OP(InplaceApplyProximalAdagrad)
    .INPUT(var, TensorType({DT_FLOAT, DT_FLOAT16, DT_BF16}))
    .INPUT(accum, TensorType({DT_FLOAT, DT_FLOAT16, DT_BF16}))
    .INPUT(lr, TensorType({DT_FLOAT, DT_FLOAT16, DT_BF16}))
    .INPUT(l1, TensorType({DT_FLOAT, DT_FLOAT16, DT_BF16}))
    .INPUT(l2, TensorType({DT_FLOAT, DT_FLOAT16, DT_BF16}))
    .INPUT(grad, TensorType({DT_FLOAT, DT_FLOAT16, DT_BF16}))
    .OUTPUT(var, TensorType({DT_FLOAT, DT_FLOAT16, DT_BF16}))
    .OUTPUT(accum, TensorType({DT_FLOAT, DT_FLOAT16, DT_BF16}))
    .ATTR(use_locking, Bool, false)
    .OP_END_FACTORY_REG(InplaceApplyProximalAdagrad)
} // namespace ge
#endif
