name: compile_action

on:
  workflow_call:
    inputs:
      task_name:
        required: true
        type: string
      image_version:
        required: true
        type: string
      package_name:
        required: false
        type: string
        default: ''
      arch:
        required: false
        type: string
        default: 'x64'
    outputs:
      arm_run_url:
        value: ${{jobs.JOB_compile.outputs.primary-url}}
      arm_run_key:
        value: ${{jobs.JOB_compile.outputs.primary-key}}
      package_name:
        value: ${{jobs.JOB_compile.outputs.package_name}}

jobs:
  JOB_compile:
    name: compile
    steps:
      -
        name: Checkout
        identifier: process_checkout
        uses: checkout
        with:
          ref: ${{ atomgit.event.pull_request.merge_commit_sha || atomgit.sha }}
          token: ${{secrets.GIT_TOKEN}}
      -
        name: download
        uses: obs-download
        with:
          endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
          bucket: "ascend-ci"
          access-key: ${{ secrets.AK }}
          secret-key: ${{ secrets.SK }}
          key: |
            ${{ env.obs_path }}/pr_filelist.txt
            ${{ env.obs_path }}/pr_filelist_mod.txt
            ${{ env.obs_path }}/update_file_detail.txt
            ${{ env.obs_path }}/compile.sh
          path: ${{ steps.process_checkout.outputs.path }}
      -
        name: compile_acc
        identifier: compile
        uses: build-accelerate
        with:
          command: |
            export WORKSPACE=${{ steps.process_checkout.outputs.path }}
            cd ${{ steps.process_checkout.outputs.path }}
            export task_name=${{ inputs.task_name }}
            export TARGET_BRANCH=${{ env.TARGET_BRANCH }}
            BuildAccelerate bash compile.sh
          AC_SERVER_IP: ${{ vars.AC_SERVER_IP }}
      -
        name: rename_package
        if: ${{ inputs.package_name != '' }}
        run: |
          mkdir -p "${{ steps.process_checkout.outputs.path }}/build_out"
          cd "${{ steps.process_checkout.outputs.path }}/build_out"
          if [[ "${{ inputs.task_name }}" == compile_single ]]; then
              mv ../single.tar.gz ${{ inputs.package_name }}
              echo "mv: ../single.tar.gz -> ${{ inputs.package_name }}"
          else
              for f in *.run; do
                  [ -f "$f" ] || continue
                  [ "$f" = "${{ inputs.package_name }}" ] && continue
                  mv "$f" "${{ inputs.package_name }}"
                  echo "Renamed: $f -> ${{ inputs.package_name }}"
                  break
              done
          fi
      -
        name: api-check
        identifier: api-check
        uses: cann/.gitcode/actions/api-check@master
        with:
          org_name: ${{ env.org_name }}
          mode: ${{ steps.compile.outputs.api-check }}
          repo_name: ${{ env.repo_name }}
          merge_id: ${{ env.MERGE_ID }}
          workspace: ${{ steps.process_checkout.outputs.path }}
          source_branch: ${{ env.SOURCE_BRANCH }}
          target_branch: ${{ env.TARGET_BRANCH }}
      -
        name: verify_package
        uses: cann/.gitcode/actions/verify-package@master
        if: ${{ inputs.task_name != 'compile_single_ubuntu24' && inputs.task_name != 'compile_single' }}
        with:
          workspace: ${{ steps.process_checkout.outputs.path }}
      - name: upload
        uses: obs-upload
        with:
          endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
          bucket: "ascend-ci"
          access-key: ${{ secrets.AK }}
          secret-key: ${{ secrets.SK }}
          artifact-path: "${{ steps.process_checkout.outputs.path }}/build_out/*"
          object-prefix: ${{ env.obs_path }}/
    if: "${{ default() }}"
    runs-on:
      - self-hosted
      - arch=${{ inputs.arch }}
      - spec=xlarge
    container:
      image: swr.cn-north-4.myhuaweicloud.com/ci_cann/${{ inputs.image_version }}
