/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file max_pool_v3_grad_tiling_key.h
 * \brief Tiling key declare for max_pool_v3_grad operator
 *
 * TilingKey 编码场景模式（overlapMode），dtype 由 DTYPE_ORIG_INPUT 宏自动实例化。
 *
 *   schMode = 0 (NON_OVERLAP_NCHW): stride>=kernel, NCHW 4D 布局
 *   schMode = 1 (NON_OVERLAP_NHWC): stride>=kernel, NHWC 4D 布局
 *   schMode = 2 (OVERLAP_NCHW):     stride<kernel,  NCHW 4D 布局（ForwardPass + GatherPass）
 *   schMode = 3 (OVERLAP_NHWC):     stride<kernel,  NHWC 4D 布局（ForwardPass + GatherPass）
 */

#ifndef MAX_POOL_V3_GRAD_TILING_KEY_H_
#define MAX_POOL_V3_GRAD_TILING_KEY_H_

#include "ascendc/host_api/tiling/template_argument.h"

// schMode 编码：bit0=overlapMode, bit1=inputFormat
#define MAX_POOL_V3_GRAD_TPL_MODE_NON_OVERLAP_NCHW 0
#define MAX_POOL_V3_GRAD_TPL_MODE_NON_OVERLAP_NHWC 1
#define MAX_POOL_V3_GRAD_TPL_MODE_OVERLAP_NCHW 2
#define MAX_POOL_V3_GRAD_TPL_MODE_OVERLAP_NHWC 3

ASCENDC_TPL_ARGS_DECL(MaxPoolV3Grad,
                      ASCENDC_TPL_UINT_DECL(schMode, 2, ASCENDC_TPL_UI_LIST, MAX_POOL_V3_GRAD_TPL_MODE_NON_OVERLAP_NCHW,
                                            MAX_POOL_V3_GRAD_TPL_MODE_NON_OVERLAP_NHWC,
                                            MAX_POOL_V3_GRAD_TPL_MODE_OVERLAP_NCHW,
                                            MAX_POOL_V3_GRAD_TPL_MODE_OVERLAP_NHWC));

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, MAX_POOL_V3_GRAD_TPL_MODE_NON_OVERLAP_NCHW),
                         ASCENDC_TPL_TILING_STRUCT_SEL(MaxPoolV3GradTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, MAX_POOL_V3_GRAD_TPL_MODE_NON_OVERLAP_NHWC),
                         ASCENDC_TPL_TILING_STRUCT_SEL(MaxPoolV3GradTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, MAX_POOL_V3_GRAD_TPL_MODE_OVERLAP_NCHW),
                         ASCENDC_TPL_TILING_STRUCT_SEL(MaxPoolV3GradTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, MAX_POOL_V3_GRAD_TPL_MODE_OVERLAP_NHWC),
                         ASCENDC_TPL_TILING_STRUCT_SEL(MaxPoolV3GradTilingData)));

#endif // MAX_POOL_V3_GRAD_TILING_KEY_H_
