/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file max_pool_v3_grad_simt.h
 * \brief SIMT kernel implementation for max_pool_v3_grad (4D NCHW/NHWC format)
 *
 *   - 逐输出位置 (n, c, ho, wo) Grid-Stride 扫描，first-wins 策略
 *   - outPos 统一编号: n*C*HoWo + c*HoWo + ho*Wo + wo（与格式无关）
 *   - GM 地址按 inputFormat 区分:
 *       NCHW(0): outAddr=outPos, inAddr=nC*HW + hi*W + wi
 *       NHWC(1): outAddr=(n*HoWo+hoWo)*C + c, inAddr=(n*HW+hi*W+wi)*C + c
 *   - 非重叠路径 (OVERLAP_MODE=0): InitPass(0) → SyncAll → direct write
 *   - 重叠路径 (OVERLAP_MODE=1):
 *       ForwardPass(存 argmax, first-wins) → SyncAll → GatherPass(寄存器 FP32 累加, 直接写 out_grad)
 */

#ifndef MAX_POOL_V3_GRAD_SIMT_H_
#define MAX_POOL_V3_GRAD_SIMT_H_

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "simt_api/common_functions.h"
#include "simt_api/asc_simt.h"
#include "simt_api/asc_fp16.h"
#include "max_pool_v3_grad_tiling_data.h"
#include "max_pool_v3_grad_tiling_key.h"

namespace NsMaxPoolV3Grad {
using namespace AscendC;

template <typename IDX_T>
static constexpr uint32_t THREADS = (sizeof(IDX_T) == 4) ? 1024 : 512;

// poolParams UB 打包 — 21 个 int64_t 常量通过 __ubuf__ 指针传递给 VF
// [0-6] 池化常量, [7-20] magic/shift 快除参数
constexpr int32_t POOL_PARAMS_COUNT = 21;

// UB 偏移索引
constexpr int32_t IDX_KH = 0;
constexpr int32_t IDX_KW = 1;
constexpr int32_t IDX_SH = 2;
constexpr int32_t IDX_SW = 3;
constexpr int32_t IDX_PAD_TOP = 4;
constexpr int32_t IDX_PAD_LEFT = 5;
constexpr int32_t IDX_FORMAT = 6;
constexpr int32_t IDX_MAGIC_HOWO = 7;
constexpr int32_t IDX_SHIFT_HOWO = 8;
constexpr int32_t IDX_MAGIC_WO = 9;
constexpr int32_t IDX_SHIFT_WO = 10;
constexpr int32_t IDX_MAGIC_C = 11;
constexpr int32_t IDX_SHIFT_C = 12;
constexpr int32_t IDX_MAGIC_HW = 13;
constexpr int32_t IDX_SHIFT_HW = 14;
constexpr int32_t IDX_MAGIC_W = 15;
constexpr int32_t IDX_SHIFT_W = 16;
constexpr int32_t IDX_MAGIC_SH = 17;
constexpr int32_t IDX_SHIFT_SH = 18;
constexpr int32_t IDX_MAGIC_SW = 19;
constexpr int32_t IDX_SHIFT_SW = 20;

// ============================================================================
// RouteGrad: 梯度路由（非重叠路径专用，直接写入 out_grad，无冲突）
// ============================================================================
template <typename T>
__simt_callee__ inline void RouteGrad(int64_t inAddr, int64_t outAddr, __gm__ T* grad, __gm__ volatile T* outGrad)
{
    // 非重叠路径：直接赋值 (stride >= kernel，窗口不重叠，无写入冲突)
    // outGrad 使用 volatile，防止 InitPass 写0的 DCache 脏数据覆盖 grad 写入
    outGrad[inAddr] = grad[outAddr];
}

// ============================================================================
// ComputeOutAddr: 计算 orig_output/grad 的 GM 地址
//   NCHW(0): outAddr = outPos
//   NHWC(1): outAddr = (n*HoWo + hoWo)*C + c
// ============================================================================
template <int32_t INPUT_FORMAT>
__simt_callee__ inline int64_t ComputeOutAddr(int64_t nC, int64_t n, int64_t hoWo, int64_t c, int64_t C, int64_t HoWo,
                                              int64_t outPos)
{
    if constexpr (INPUT_FORMAT == 0) {
        return outPos; // NCHW
    }
    // NHWC: ((n*Ho + ho)*Wo + wo)*C + c = (n*HoWo + hoWo)*C + c
    return n * HoWo * C + hoWo * C + c;
}

// ============================================================================
// ComputeInAddr: 计算 orig_input/out_grad 的 GM 地址
//   NCHW(0): inAddr = nC*HW + hi*W + wi
//   NHWC(1): inAddr = (n*HW + hi*W + wi)*C + c
// ============================================================================
template <int32_t INPUT_FORMAT>
__simt_callee__ inline int64_t ComputeInAddr(int64_t nC, int64_t n, int64_t hi, int64_t wi, int64_t c, int64_t C,
                                             int64_t HW, int64_t W)
{
    if constexpr (INPUT_FORMAT == 0) {
        // NCHW: ((n*C + c)*H + hi)*W + wi = nC*HW + hi*W + wi
        return nC * HW + hi * W + wi;
    }
    // NHWC: ((n*H + hi)*W + wi)*C + c = (n*HW + hi*W + wi)*C + c
    return (n * HW + hi * W + wi) * C + c;
}

// ============================================================================
// PStartGradFast: 反向映射——输入位置 size 被覆盖的最小输出索引
//   size+pad < kernel 时返回 0（输入位置不被任何窗口覆盖）
// ============================================================================
template <typename IDX_T, typename DIV_T>
__simt_callee__ inline IDX_T PStartGradFast(IDX_T size, IDX_T pad, IDX_T kernel, DIV_T magicStride, DIV_T shiftStride)
{
    if (size + pad < kernel) {
        return 0;
    }
    IDX_T phStart = size + pad - kernel;
    phStart = static_cast<IDX_T>(Simt::UintDiv(static_cast<DIV_T>(phStart), magicStride, shiftStride));
    phStart += 1;
    return phStart;
}

// ============================================================================
// PEndGradFast: 反向映射——输入位置 size 被覆盖的最大输出索引 + 1（半开区间）
//   poolSize 为 Ho 或 Wo（输出尺寸），防止 pEnd 越界
// ============================================================================
template <typename IDX_T, typename DIV_T>
__simt_callee__ inline IDX_T PEndGradFast(IDX_T size, IDX_T pad, IDX_T poolSize, DIV_T magicStride, DIV_T shiftStride)
{
    IDX_T pEnd = size + pad;
    pEnd = static_cast<IDX_T>(Simt::UintDiv(static_cast<DIV_T>(pEnd), magicStride, shiftStride));
    pEnd += 1;
    return (pEnd > poolSize) ? poolSize : pEnd;
}

// ============================================================================
// ProcessOneOutputPos: 处理单个输出位置（非重叠路径）
//   first-wins 策略扫描 kh×kw 窗口，首匹配位置路由梯度
//   poolParams 通过 UB 传递池化常量 + magic/shift 快除参数
// ============================================================================
template <typename T, typename IDX_T, int32_t INPUT_FORMAT>
__simt_callee__ inline void ProcessOneOutputPos(IDX_T outPos, int64_t HoWo, int64_t Wo, int64_t C, int64_t HW,
                                                int64_t W, int64_t H, __ubuf__ const int64_t* poolParams,
                                                __gm__ T* origInput, __gm__ T* origOutput, __gm__ T* grad,
                                                __gm__ volatile T* outGrad)
{
    int64_t kh = poolParams[IDX_KH];
    int64_t kw = poolParams[IDX_KW];
    int64_t sh = poolParams[IDX_SH];
    int64_t sw = poolParams[IDX_SW];
    int64_t padTop = poolParams[IDX_PAD_TOP];
    int64_t padLeft = poolParams[IDX_PAD_LEFT];
    int64_t nC = outPos / HoWo;
    int64_t hoWo = outPos % HoWo;
    int64_t ho = hoWo / Wo;
    int64_t wo = hoWo % Wo;
    int64_t n = nC / C;
    int64_t c = nC % C;
    int64_t outAddr = ComputeOutAddr<INPUT_FORMAT>(nC, n, hoWo, c, C, HoWo, outPos);
    T outVal = origOutput[outAddr];
    bool matched = false;
    int64_t hStart = ho * sh - padTop;
    int64_t wStart = wo * sw - padLeft;
    for (int64_t ki = 0; ki < kh && !matched; ki++) {
        int64_t hi = hStart + ki;
        if (hi < 0 || hi >= H) {
            continue;
        }
        for (int64_t kj = 0; kj < kw && !matched; kj++) {
            int64_t wi = wStart + kj;
            if (wi < 0 || wi >= W) {
                continue;
            }
            int64_t inAddr = ComputeInAddr<INPUT_FORMAT>(nC, n, hi, wi, c, C, HW, W);
            T inVal = origInput[inAddr];
            if (inVal == outVal) {
                matched = true;
                RouteGrad<T>(inAddr, outAddr, grad, outGrad);
            }
        }
    }
}

// MaxPoolV3GradSimt: 非重叠路径核心 VF — Grid-Stride 循环逐输出位置处理
template <typename T, typename IDX_T, int32_t INPUT_FORMAT>
__simt_vf__ __aicore__ __launch_bounds__(THREADS<IDX_T>) inline void MaxPoolV3GradSimt(
    IDX_T totalOutputPos, int64_t HoWo, int64_t Wo, int64_t C, int64_t HW, int64_t W,
    __ubuf__ const int64_t* poolParams, __gm__ T* origInput, __gm__ T* origOutput, __gm__ T* grad,
    __gm__ volatile T* outGrad)
{
    using DIV_T = typename std::conditional<std::is_same_v<IDX_T, int32_t>, uint32_t, uint64_t>::type;
    int64_t H = (W > 0) ? (HW / W) : 0;
    // 从 UB 读取 magic/shift（int64_t 存储，static_cast 到 DIV_T 使用）
    DIV_T magicHoWo = static_cast<DIV_T>(poolParams[IDX_MAGIC_HOWO]);
    DIV_T shiftHoWo = static_cast<DIV_T>(poolParams[IDX_SHIFT_HOWO]);
    DIV_T magicWo = static_cast<DIV_T>(poolParams[IDX_MAGIC_WO]);
    DIV_T shiftWo = static_cast<DIV_T>(poolParams[IDX_SHIFT_WO]);
    DIV_T magicC = static_cast<DIV_T>(poolParams[IDX_MAGIC_C]);
    DIV_T shiftC = static_cast<DIV_T>(poolParams[IDX_SHIFT_C]);

    IDX_T stride = static_cast<IDX_T>(blockDim.x) * static_cast<IDX_T>(gridDim.x);
    for (IDX_T outPos =
             static_cast<IDX_T>(blockIdx.x) * static_cast<IDX_T>(blockDim.x) + static_cast<IDX_T>(threadIdx.x);
         outPos < totalOutputPos; outPos += stride) {
        ProcessOneOutputPos<T, IDX_T, INPUT_FORMAT>(outPos, HoWo, Wo, C, HW, W, H, poolParams, origInput, origOutput,
                                                    grad, outGrad);
    }
}

// ============================================================================
// MaxPoolV3ForwardSimt: 重叠路径 Pass 1 — ForwardPass 存 argmax (first-wins)
//   argmax 使用 __gm__ volatile 修饰，确保写入直接到 GM（绕过 DCache）
// ============================================================================
template <typename T, typename IDX_T, int32_t INPUT_FORMAT>
__simt_vf__ __aicore__ __launch_bounds__(THREADS<IDX_T>) inline void MaxPoolV3ForwardSimt(
    IDX_T totalOutputPos, int64_t HoWo, int64_t Wo, int64_t C, int64_t HW, int64_t W,
    __ubuf__ const int64_t* poolParams, __gm__ T* origInput, __gm__ T* origOutput, __gm__ volatile int32_t* argmax)
{
    using DIV_T = typename std::conditional<std::is_same_v<IDX_T, int32_t>, uint32_t, uint64_t>::type;
    int64_t kh = poolParams[IDX_KH];
    int64_t kw = poolParams[IDX_KW];
    int64_t sh = poolParams[IDX_SH];
    int64_t sw = poolParams[IDX_SW];
    int64_t padTop = poolParams[IDX_PAD_TOP];
    int64_t padLeft = poolParams[IDX_PAD_LEFT];
    int64_t H = (W > 0) ? (HW / W) : 0;
    DIV_T magicHoWo = static_cast<DIV_T>(poolParams[IDX_MAGIC_HOWO]);
    DIV_T shiftHoWo = static_cast<DIV_T>(poolParams[IDX_SHIFT_HOWO]);
    DIV_T magicWo = static_cast<DIV_T>(poolParams[IDX_MAGIC_WO]);
    DIV_T shiftWo = static_cast<DIV_T>(poolParams[IDX_SHIFT_WO]);
    DIV_T magicC = static_cast<DIV_T>(poolParams[IDX_MAGIC_C]);
    DIV_T shiftC = static_cast<DIV_T>(poolParams[IDX_SHIFT_C]);

    IDX_T stride = static_cast<IDX_T>(blockDim.x) * static_cast<IDX_T>(gridDim.x);
    for (IDX_T outPos =
             static_cast<IDX_T>(blockIdx.x) * static_cast<IDX_T>(blockDim.x) + static_cast<IDX_T>(threadIdx.x);
         outPos < totalOutputPos; outPos += stride) {
        IDX_T nC = static_cast<IDX_T>(Simt::UintDiv(static_cast<DIV_T>(outPos), magicHoWo, shiftHoWo));
        IDX_T hoWo = outPos - nC * static_cast<IDX_T>(HoWo);
        IDX_T ho = static_cast<IDX_T>(Simt::UintDiv(static_cast<DIV_T>(hoWo), magicWo, shiftWo));
        IDX_T wo = hoWo - ho * static_cast<IDX_T>(Wo);
        IDX_T n = static_cast<IDX_T>(Simt::UintDiv(static_cast<DIV_T>(nC), magicC, shiftC));
        IDX_T c = nC - n * static_cast<IDX_T>(C);
        int64_t outAddr = ComputeOutAddr<INPUT_FORMAT>(nC, n, hoWo, c, C, HoWo, outPos);
        T outVal = origOutput[outAddr];
        int64_t hStart = ho * sh - padTop;
        int64_t wStart = wo * sw - padLeft;
        int32_t maxIdx = -1;
        bool matched = false;
        for (int64_t ki = 0; ki < kh && !matched; ki++) {
            int64_t hi = hStart + ki;
            if (hi < 0 || hi >= H) {
                continue;
            }
            for (int64_t kj = 0; kj < kw && !matched; kj++) {
                int64_t wi = wStart + kj;
                if (wi < 0 || wi >= W) {
                    continue;
                }
                int64_t inAddr = ComputeInAddr<INPUT_FORMAT>(nC, n, hi, wi, c, C, HW, W);
                if (origInput[inAddr] == outVal) {
                    maxIdx = static_cast<int32_t>(hi * W + wi);
                    matched = true;
                }
            }
        }
        argmax[outPos] = maxIdx;
    }
}

// ============================================================================
// MaxPoolV3GradGatherSimt: 重叠路径 Pass 2 — GatherPass 寄存器累加（确定）
//   argmax 使用普通 __gm__ 读取（走 DCache 加速）
//   outGrad 使用 __gm__ volatile 写入（VF 标量写 GM 需 volatile 确保落 GM，不走 DCache）
// ============================================================================
template <typename T, typename IDX_T, int32_t INPUT_FORMAT>
__simt_vf__ __aicore__ __launch_bounds__(THREADS<IDX_T>) inline void MaxPoolV3GradGatherSimt(
    IDX_T totalInputPos, int64_t HoWo, int64_t Wo, int64_t C, int64_t HW, int64_t W, __ubuf__ const int64_t* poolParams,
    __gm__ T* grad, __gm__ int32_t* argmax, __gm__ volatile T* outGrad)
{
    using DIV_T = typename std::conditional<std::is_same_v<IDX_T, int32_t>, uint32_t, uint64_t>::type;
    int64_t kh = poolParams[IDX_KH];
    int64_t kw = poolParams[IDX_KW];
    int64_t sh = poolParams[IDX_SH];
    int64_t sw = poolParams[IDX_SW];
    int64_t padTop = poolParams[IDX_PAD_TOP];
    int64_t padLeft = poolParams[IDX_PAD_LEFT];
    int64_t H = (W > 0) ? (HW / W) : 0;
    int64_t Ho = (Wo > 0) ? (HoWo / Wo) : 0;
    DIV_T magicHW = static_cast<DIV_T>(poolParams[IDX_MAGIC_HW]);
    DIV_T shiftHW = static_cast<DIV_T>(poolParams[IDX_SHIFT_HW]);
    DIV_T magicW = static_cast<DIV_T>(poolParams[IDX_MAGIC_W]);
    DIV_T shiftW = static_cast<DIV_T>(poolParams[IDX_SHIFT_W]);
    DIV_T magicC = static_cast<DIV_T>(poolParams[IDX_MAGIC_C]);
    DIV_T shiftC = static_cast<DIV_T>(poolParams[IDX_SHIFT_C]);
    DIV_T magicSh = static_cast<DIV_T>(poolParams[IDX_MAGIC_SH]);
    DIV_T shiftSh = static_cast<DIV_T>(poolParams[IDX_SHIFT_SH]);
    DIV_T magicSw = static_cast<DIV_T>(poolParams[IDX_MAGIC_SW]);
    DIV_T shiftSw = static_cast<DIV_T>(poolParams[IDX_SHIFT_SW]);

    IDX_T stride = static_cast<IDX_T>(blockDim.x) * static_cast<IDX_T>(gridDim.x);
    for (IDX_T inPos =
             static_cast<IDX_T>(blockIdx.x) * static_cast<IDX_T>(blockDim.x) + static_cast<IDX_T>(threadIdx.x);
         inPos < totalInputPos; inPos += stride) {
        IDX_T nC = static_cast<IDX_T>(Simt::UintDiv(static_cast<DIV_T>(inPos), magicHW, shiftHW));
        IDX_T hiWi = inPos - nC * static_cast<IDX_T>(HW);
        IDX_T hi = static_cast<IDX_T>(Simt::UintDiv(static_cast<DIV_T>(hiWi), magicW, shiftW));
        IDX_T wi = hiWi - hi * static_cast<IDX_T>(W);
        IDX_T n = static_cast<IDX_T>(Simt::UintDiv(static_cast<DIV_T>(nC), magicC, shiftC));
        IDX_T c = nC - n * static_cast<IDX_T>(C);
        IDX_T phStart = PStartGradFast<IDX_T, DIV_T>(hi, static_cast<IDX_T>(padTop), static_cast<IDX_T>(kh), magicSh,
                                                     shiftSh);
        IDX_T phEnd = PEndGradFast<IDX_T, DIV_T>(hi, static_cast<IDX_T>(padTop), static_cast<IDX_T>(Ho), magicSh,
                                                 shiftSh);
        IDX_T pwStart = PStartGradFast<IDX_T, DIV_T>(wi, static_cast<IDX_T>(padLeft), static_cast<IDX_T>(kw), magicSw,
                                                     shiftSw);
        IDX_T pwEnd = PEndGradFast<IDX_T, DIV_T>(wi, static_cast<IDX_T>(padLeft), static_cast<IDX_T>(Wo), magicSw,
                                                 shiftSw);
        int32_t spatialOffset = static_cast<int32_t>(hi * W + wi);
        float gradient = 0.0f;
        for (IDX_T ph = phStart; ph < phEnd; ++ph) {
            for (IDX_T pw = pwStart; pw < pwEnd; ++pw) {
                IDX_T hoWo = ph * static_cast<IDX_T>(Wo) + pw;
                IDX_T outPos = nC * static_cast<IDX_T>(HoWo) + hoWo;
                if (argmax[outPos] == spatialOffset) {
                    int64_t outAddr = ComputeOutAddr<INPUT_FORMAT>(nC, n, hoWo, c, C, HoWo, outPos);
                    if constexpr (std::is_same_v<T, half>) {
                        gradient += __half2float(grad[outAddr]);
                    } else {
                        gradient += static_cast<float>(grad[outAddr]);
                    }
                }
            }
        }
        int64_t inAddr = ComputeInAddr<INPUT_FORMAT>(nC, n, hi, wi, c, C, HW, W);
        if constexpr (std::is_same_v<T, half>) {
            outGrad[inAddr] = __float2half(gradient);
        } else {
            outGrad[inAddr] = static_cast<T>(gradient);
        }
    }
}

// ============================================================================
// InitPass: 初始化 pass — 将 ptr 指向的 totalElements 个元素置 0
//   ptr 使用 __gm__ volatile，确保写0直接到 GM（绕过 DCache）
// ============================================================================
template <typename T, typename IDX_T>
__simt_vf__ __aicore__ __launch_bounds__(THREADS<IDX_T>) inline void InitPass(IDX_T totalElements,
                                                                              __gm__ volatile T* ptr)
{
    IDX_T stride = static_cast<IDX_T>(blockDim.x) * static_cast<IDX_T>(gridDim.x);
    for (IDX_T idx = static_cast<IDX_T>(blockIdx.x) * static_cast<IDX_T>(blockDim.x) + static_cast<IDX_T>(threadIdx.x);
         idx < totalElements; idx += stride) {
        ptr[idx] = static_cast<T>(0);
    }
}

// ============================================================================
// RunWithIdxType: 按索引位宽启动 VF 的辅助函数
// ============================================================================
template <typename T, int32_t OVERLAP_MODE, int32_t INPUT_FORMAT, typename IDX_T>
__aicore__ inline void RunWithIdxType(int64_t totalOutputPos, int64_t totalInputElements, int64_t HoWo, int64_t Wo,
                                      int64_t C, int64_t HW, int64_t W, int64_t kh, int64_t kw, int64_t sh, int64_t sw,
                                      int64_t padTop, int64_t padLeft, int64_t inputFormat, __gm__ T* origInputGm,
                                      __gm__ T* origOutputGm, __gm__ T* gradGm, __gm__ volatile T* outGradGm,
                                      __gm__ volatile int32_t* argmaxGm)
{
    using DIV_T = typename std::conditional<std::is_same_v<IDX_T, int32_t>, uint32_t, uint64_t>::type;

    TPipe pipe;
    TBuf<TPosition::VECCALC> poolParamsTBuf;
    constexpr int32_t POOL_PARAMS_BYTES = ((POOL_PARAMS_COUNT * sizeof(int64_t) + 31) / 32) * 32;
    pipe.InitBuffer(poolParamsTBuf, POOL_PARAMS_BYTES);
    LocalTensor<int64_t> poolParamsTensor = poolParamsTBuf.Get<int64_t>();
    // 池化常量
    poolParamsTensor.SetValue(IDX_KH, kh);
    poolParamsTensor.SetValue(IDX_KW, kw);
    poolParamsTensor.SetValue(IDX_SH, sh);
    poolParamsTensor.SetValue(IDX_SW, sw);
    poolParamsTensor.SetValue(IDX_PAD_TOP, padTop);
    poolParamsTensor.SetValue(IDX_PAD_LEFT, padLeft);
    poolParamsTensor.SetValue(IDX_FORMAT, inputFormat);
    // 用 DIV_T 版本，确保 magic 值在对应位宽范围内，VF 内 static_cast<DIV_T> 不截断
    DIV_T magicHoWo = 0, shiftHoWo = 0;
    DIV_T magicWo = 0, shiftWo = 0;
    DIV_T magicC = 0, shiftC = 0;
    DIV_T magicHW = 0, shiftHW = 0;
    DIV_T magicW = 0, shiftW = 0;
    DIV_T magicSh = 0, shiftSh = 0;
    DIV_T magicSw = 0, shiftSw = 0;
    GetUintDivMagicAndShift(magicHoWo, shiftHoWo, static_cast<DIV_T>(HoWo));
    GetUintDivMagicAndShift(magicWo, shiftWo, static_cast<DIV_T>(Wo));
    GetUintDivMagicAndShift(magicC, shiftC, static_cast<DIV_T>(C));
    GetUintDivMagicAndShift(magicHW, shiftHW, static_cast<DIV_T>(HW));
    GetUintDivMagicAndShift(magicW, shiftW, static_cast<DIV_T>(W));
    GetUintDivMagicAndShift(magicSh, shiftSh, static_cast<DIV_T>(sh));
    GetUintDivMagicAndShift(magicSw, shiftSw, static_cast<DIV_T>(sw));
    poolParamsTensor.SetValue(IDX_MAGIC_HOWO, static_cast<int64_t>(magicHoWo));
    poolParamsTensor.SetValue(IDX_SHIFT_HOWO, static_cast<int64_t>(shiftHoWo));
    poolParamsTensor.SetValue(IDX_MAGIC_WO, static_cast<int64_t>(magicWo));
    poolParamsTensor.SetValue(IDX_SHIFT_WO, static_cast<int64_t>(shiftWo));
    poolParamsTensor.SetValue(IDX_MAGIC_C, static_cast<int64_t>(magicC));
    poolParamsTensor.SetValue(IDX_SHIFT_C, static_cast<int64_t>(shiftC));
    poolParamsTensor.SetValue(IDX_MAGIC_HW, static_cast<int64_t>(magicHW));
    poolParamsTensor.SetValue(IDX_SHIFT_HW, static_cast<int64_t>(shiftHW));
    poolParamsTensor.SetValue(IDX_MAGIC_W, static_cast<int64_t>(magicW));
    poolParamsTensor.SetValue(IDX_SHIFT_W, static_cast<int64_t>(shiftW));
    poolParamsTensor.SetValue(IDX_MAGIC_SH, static_cast<int64_t>(magicSh));
    poolParamsTensor.SetValue(IDX_SHIFT_SH, static_cast<int64_t>(shiftSh));
    poolParamsTensor.SetValue(IDX_MAGIC_SW, static_cast<int64_t>(magicSw));
    poolParamsTensor.SetValue(IDX_SHIFT_SW, static_cast<int64_t>(shiftSw));
    __ubuf__ const int64_t* poolParams = (__ubuf__ const int64_t*)poolParamsTensor.GetPhyAddr();
    DataSyncBarrier<MemDsbT::UB>();

    IDX_T iTotalOutputPos = static_cast<IDX_T>(totalOutputPos);
    IDX_T iTotalInputElements = static_cast<IDX_T>(totalInputElements);
    if constexpr (OVERLAP_MODE == 0) {
        // ===== 非重叠路径：InitPass(out_grad, 0) → SyncAll → direct write =====
        asc_vf_call<InitPass<T, IDX_T>>(dim3(THREADS<IDX_T>), iTotalInputElements, outGradGm);
        SyncAll();
        asc_vf_call<MaxPoolV3GradSimt<T, IDX_T, INPUT_FORMAT>>(dim3(THREADS<IDX_T>), iTotalOutputPos, HoWo, Wo, C, HW,
                                                               W, poolParams, origInputGm, origOutputGm, gradGm,
                                                               outGradGm);
    } else {
        // ===== 重叠路径：ForwardPass(存 argmax) → SyncAll → GatherPass(寄存器累加) =====
        asc_vf_call<MaxPoolV3ForwardSimt<T, IDX_T, INPUT_FORMAT>>(
            dim3(THREADS<IDX_T>), iTotalOutputPos, HoWo, Wo, C, HW, W, poolParams, origInputGm, origOutputGm, argmaxGm);
        SyncAll();
        // GatherPass 读 argmax 走 DCache 加速（ForwardPass volatile 写不进 DCache）
        // outGrad 保持 volatile: VF 标量写 GM 需 volatile 确保落 GM
        asc_vf_call<MaxPoolV3GradGatherSimt<T, IDX_T, INPUT_FORMAT>>(dim3(THREADS<IDX_T>), iTotalInputElements, HoWo,
                                                                     Wo, C, HW, W, poolParams, gradGm,
                                                                     (__gm__ int32_t*)argmaxGm, outGradGm);
    }
}

// ============================================================================
// Process: 调度入口
// ============================================================================
template <typename T, int32_t OVERLAP_MODE, int32_t INPUT_FORMAT>
__aicore__ inline void Process(GM_ADDR orig_input, GM_ADDR orig_output, GM_ADDR grad, GM_ADDR out_grad,
                               GM_ADDR workspace, const MaxPoolV3GradTilingData* tilingData)
{
    __gm__ T* origInputGm = (__gm__ T*)orig_input;
    __gm__ T* origOutputGm = (__gm__ T*)orig_output;
    __gm__ T* gradGm = (__gm__ T*)grad;
    __gm__ volatile T* outGradGm = (__gm__ volatile T*)out_grad;
    __gm__ volatile int32_t* argmaxGm = (__gm__ volatile int32_t*)workspace;

    int64_t totalOutputPos = tilingData->totalOutputPos;
    int64_t totalInputElements = tilingData->totalInputElements;
    int64_t HoWo = tilingData->HoWo;
    int64_t Wo = tilingData->Wo;
    int64_t C = tilingData->C;
    int64_t HW = tilingData->HW;
    int64_t W = tilingData->W;
    int64_t inputFormat = tilingData->inputFormat;
    int64_t kh = tilingData->kh;
    int64_t kw = tilingData->kw;
    int64_t sh = tilingData->sh;
    int64_t sw = tilingData->sw;
    int64_t padTop = tilingData->padTop;
    int64_t padLeft = tilingData->padLeft;

    int64_t maxElements = (totalOutputPos > totalInputElements) ? totalOutputPos : totalInputElements;
    if (maxElements <= static_cast<int64_t>(INT32_MAX)) {
        // 32 位路径：uint32_t 快除 + 1024 线程
        RunWithIdxType<T, OVERLAP_MODE, INPUT_FORMAT, int32_t>(totalOutputPos, totalInputElements, HoWo, Wo, C, HW, W,
                                                               kh, kw, sh, sw, padTop, padLeft, inputFormat,
                                                               origInputGm, origOutputGm, gradGm, outGradGm, argmaxGm);
    } else {
        // 64 位路径：uint64_t 快除 + 512 线程
        RunWithIdxType<T, OVERLAP_MODE, INPUT_FORMAT, int64_t>(totalOutputPos, totalInputElements, HoWo, Wo, C, HW, W,
                                                               kh, kw, sh, sw, padTop, padLeft, inputFormat,
                                                               origInputGm, origOutputGm, gradGm, outGradGm, argmaxGm);
    }
}
} // namespace NsMaxPoolV3Grad
#endif // MAX_POOL_V3_GRAD_SIMT_H_
