/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

#include <gtest/gtest.h>
#include <iostream>
#include "register/op_impl_registry.h"
#include "kernel_run_context_facker.h"
#include "exe_graph/runtime/storage_format.h"
#include "exe_graph/runtime/storage_shape.h"

class AvgPool1dInfershape : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "AvgPool1dInfershape SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "AvgPool1dInfershape TearDown" << std::endl; }
};

namespace {
struct InferShapeCaseInput {
    std::vector<int64_t> xShape;
    ge::DataType dt;
    int64_t ksize;
    int64_t strides;
    std::vector<int64_t> pads;
    bool ceilMode;
    bool countIncludePad;
};

struct InferShapeCaseExpect {
    bool expectSuccess;
    std::vector<int64_t> expectOutputShape;
};

static gert::Shape MakeShape(const std::vector<int64_t>& dims)
{
    gert::Shape s;
    for (auto d : dims) {
        s.AppendDim(d);
    }
    return s;
}

static void DoInferShapeCase(const InferShapeCaseInput& in, const InferShapeCaseExpect& exp)
{
    auto func = gert::OpImplRegistry::GetInstance().GetOpImpl("AvgPool1D")->infer_shape;
    ASSERT_NE(func, nullptr);

    gert::Shape x = MakeShape(in.xShape);
    auto holder = gert::InferShapeContextFaker()
                      .NodeIoNum(1, 1)
                      .IrInstanceNum({1})
                      .InputShapes({&x})
                      .NodeAttrs({{"ksize", Ops::NN::AnyValue::CreateFrom<int64_t>(in.ksize)},
                                  {"strides", Ops::NN::AnyValue::CreateFrom<int64_t>(in.strides)},
                                  {"pads", Ops::NN::AnyValue::CreateFrom<std::vector<int64_t>>(in.pads)},
                                  {"ceil_mode", Ops::NN::AnyValue::CreateFrom<bool>(in.ceilMode)},
                                  {"count_include_pad", Ops::NN::AnyValue::CreateFrom<bool>(in.countIncludePad)}})
                      .Build();
    auto* ctx = holder.GetContext<gert::InferShapeContext>();
    if (exp.expectSuccess) {
        EXPECT_EQ(func(ctx), ge::GRAPH_SUCCESS);
        if (!exp.expectOutputShape.empty()) {
            const auto* outShape = ctx->GetOutputShape(0);
            ASSERT_NE(outShape, nullptr);
            EXPECT_EQ(outShape->GetDimNum(), exp.expectOutputShape.size());
            for (size_t i = 0; i < exp.expectOutputShape.size(); i++) {
                EXPECT_EQ(outShape->GetDim(i), exp.expectOutputShape[i]);
            }
        }
    } else {
        EXPECT_NE(func(ctx), ge::GRAPH_SUCCESS);
    }
}
} // namespace

// Scenario: floor mode, (1,1,8), ksize=3, strides=2, pads=[1,1]
// L_out = (8+1+1-3)/2+1 = 4
TEST_F(AvgPool1dInfershape, avg_pool1_d_floor_basic)
{
    DoInferShapeCase({.xShape = {1, 1, 8},
                      .dt = ge::DT_FLOAT16,
                      .ksize = 3,
                      .strides = 2,
                      .pads = {1, 1},
                      .ceilMode = false,
                      .countIncludePad = false},
                     {.expectSuccess = true, .expectOutputShape = {1, 1, 4}});
}

// Scenario: ceil mode, (1,2,10), ksize=3, strides=2, pads=[1,1], ceil_mode=true
// L_out = (10+1+1-3+2-1)/2+1 = 6
TEST_F(AvgPool1dInfershape, avg_pool1_d_ceil_mode)
{
    DoInferShapeCase({.xShape = {1, 2, 10},
                      .dt = ge::DT_FLOAT16,
                      .ksize = 3,
                      .strides = 2,
                      .pads = {1, 1},
                      .ceilMode = true,
                      .countIncludePad = false},
                     {.expectSuccess = true, .expectOutputShape = {1, 2, 6}});
}

// Scenario: asymmetric padding pads=[0,2], (1,1,7), ksize=3, strides=1
// L_out = (7+0+2-3)/1+1 = 7
TEST_F(AvgPool1dInfershape, avg_pool1_d_asymmetric_pad)
{
    DoInferShapeCase({.xShape = {1, 1, 7},
                      .dt = ge::DT_FLOAT,
                      .ksize = 3,
                      .strides = 1,
                      .pads = {0, 2},
                      .ceilMode = false,
                      .countIncludePad = false},
                     {.expectSuccess = true, .expectOutputShape = {1, 1, 7}});
}

// Scenario: symmetric padding pads=[3,3], (1,1,5), ksize=4, strides=1
// L_out = (5+3+3-4)/1+1 = 8
TEST_F(AvgPool1dInfershape, avg_pool1_d_symmetric_pad)
{
    DoInferShapeCase({.xShape = {1, 1, 5},
                      .dt = ge::DT_FLOAT16,
                      .ksize = 4,
                      .strides = 1,
                      .pads = {3, 3},
                      .ceilMode = false,
                      .countIncludePad = false},
                     {.expectSuccess = true, .expectOutputShape = {1, 1, 8}});
}

// Scenario: empty tensor L=0, (1,1,0), ksize=3, strides=1, pads=[0,0]
// L_out = 0
TEST_F(AvgPool1dInfershape, avg_pool1_d_empty_tensor)
{
    DoInferShapeCase({.xShape = {1, 1, 0},
                      .dt = ge::DT_FLOAT16,
                      .ksize = 3,
                      .strides = 1,
                      .pads = {0, 0},
                      .ceilMode = false,
                      .countIncludePad = false},
                     {.expectSuccess = true, .expectOutputShape = {1, 1, 0}});
}

// Scenario: 4D input (N,C,H,L), (2,3,4,10), ksize=2, strides=2, pads=[0,0]
// L_out = (10+0+0-2)/2+1 = 5
TEST_F(AvgPool1dInfershape, avg_pool1_d_4d_input)
{
    DoInferShapeCase({.xShape = {2, 3, 4, 10},
                      .dt = ge::DT_FLOAT,
                      .ksize = 2,
                      .strides = 2,
                      .pads = {0, 0},
                      .ceilMode = false,
                      .countIncludePad = false},
                     {.expectSuccess = true, .expectOutputShape = {2, 3, 4, 5}});
}

// Scenario: unknown dim (-1) in non-last dimension, (2, -1, 8), ksize=3, strides=2, pads=[1,1]
// L_out = 4, unknown dim preserved
TEST_F(AvgPool1dInfershape, avg_pool1_d_unknown_dim)
{
    DoInferShapeCase({.xShape = {2, -1, 8},
                      .dt = ge::DT_FLOAT16,
                      .ksize = 3,
                      .strides = 2,
                      .pads = {1, 1},
                      .ceilMode = false,
                      .countIncludePad = false},
                     {.expectSuccess = true, .expectOutputShape = {2, -1, 4}});
}

// Scenario: rank < 3 (1D input), expect infershape to fail
TEST_F(AvgPool1dInfershape, avg_pool1_d_rank_lt_3_fail)
{
    DoInferShapeCase({.xShape = {8},
                      .dt = ge::DT_FLOAT16,
                      .ksize = 3,
                      .strides = 1,
                      .pads = {0, 0},
                      .ceilMode = false,
                      .countIncludePad = false},
                     {.expectSuccess = false, .expectOutputShape = {}});
}

// Scenario: invalid ksize < 1, expect infershape to fail
TEST_F(AvgPool1dInfershape, avg_pool1_d_invalid_ksize_fail)
{
    DoInferShapeCase({.xShape = {1, 1, 8},
                      .dt = ge::DT_FLOAT16,
                      .ksize = 0,
                      .strides = 1,
                      .pads = {0, 0},
                      .ceilMode = false,
                      .countIncludePad = false},
                     {.expectSuccess = false, .expectOutputShape = {}});
}

// Scenario: negative pads, expect infershape to fail
TEST_F(AvgPool1dInfershape, avg_pool1_d_negative_pads_fail)
{
    DoInferShapeCase({.xShape = {1, 1, 8},
                      .dt = ge::DT_FLOAT16,
                      .ksize = 3,
                      .strides = 1,
                      .pads = {-1, 0},
                      .ceilMode = false,
                      .countIncludePad = false},
                     {.expectSuccess = false, .expectOutputShape = {}});
}
