/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <iostream>
#include <map>
#include <gtest/gtest.h>

#include "log/log.h"
#include "kernel_run_context_facker.h"
#include "test_cube_util.h"
#include "exe_graph/runtime/storage_format.h"
#include "exe_graph/runtime/storage_shape.h"
#include "platform/platform_infos_def.h"
#include "ut_op_util.h"

using namespace ut_util;
using namespace std;
using namespace ge;

namespace {
const std::string OP_TYPE = "InplaceUpdate";
const std::string COMPILE_INFO_JSON = R"({
      "hardware_info": {
        "BT_SIZE": 0, "load3d_constraints": "1",
        "Intrinsic_fix_pipe_l0c2out": false, "Intrinsic_data_move_l12ub": true,
        "Intrinsic_data_move_l0c2ub": true, "Intrinsic_data_move_out2l1_nd2nz": false,
        "UB_SIZE": 245760, "L2_SIZE": 33554432, "L1_SIZE": 524288,
        "L0A_SIZE": 65536, "L0B_SIZE": 65536, "L0C_SIZE": 131072, "CORE_NUM": 64
      }
    })";

struct InplaceUpdateCompileInfoStub {
} g_compileInfo;
} // namespace

class InplaceUpdateTilingTest : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "InplaceUpdateTilingTest SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "InplaceUpdateTilingTest TearDown" << std::endl; }
};

// Run a single tiling case. Each dtype is passed separately so that reject
// cases can vary a single operand's dtype while keeping the others legal.
// Returns the tiling function status so callers can assert SUCCESS or FAILED.
static ge::graphStatus RunTiling(ge::DataType xDtype, ge::DataType indicesDtype, ge::DataType vDtype,
                                 ge::DataType yDtype, gert::StorageShape& xShape, gert::StorageShape& indicesShape,
                                 gert::StorageShape& vShape, gert::StorageShape& yShape)
{
    std::map<std::string, std::string> soc_infos;
    std::map<std::string, std::string> aicore_spec;
    std::map<std::string, std::string> intrinsics;
    GetPlatFormInfos(COMPILE_INFO_JSON.c_str(), soc_infos, aicore_spec, intrinsics);

    fe::PlatFormInfos platform_info;
    platform_info.Init();

    auto tiling_func = gert::OpImplRegistry::GetInstance().GetOpImpl(OP_TYPE.c_str())->tiling;
    auto tiling_parse_func = gert::OpImplRegistry::GetInstance().GetOpImpl(OP_TYPE.c_str())->tiling_parse;

    auto kernel_holder = gert::KernelRunContextFaker()
                             .KernelIONum(2, 1)
                             .Inputs({const_cast<char*>(COMPILE_INFO_JSON.c_str()),
                                      reinterpret_cast<void*>(&platform_info)})
                             .Outputs({&g_compileInfo})
                             .Build();
    EXPECT_TRUE(kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->Init());
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("SoCInfo", soc_infos);
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("AICoreSpec", aicore_spec);
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetCoreNumByCoreType("AICore");
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("AICoreintrinsicDtypeMap",
                                                                                            intrinsics);
    EXPECT_EQ(tiling_parse_func(kernel_holder.GetContext<gert::KernelContext>()), ge::GRAPH_SUCCESS);

    auto param = gert::TilingData::CreateCap(4096);
    auto workspace_size_holder = gert::ContinuousVector::Create<size_t>(4096);
    auto ws_size = reinterpret_cast<gert::ContinuousVector*>(workspace_size_holder.get());
    EXPECT_NE(param, nullptr);

    auto holder = gert::TilingContextFaker()
                      .SetOpType(OP_TYPE)
                      .NodeIoNum(3, 1)
                      .IrInstanceNum({1, 1, 1})
                      .InputShapes({&xShape, &indicesShape, &vShape})
                      .OutputShapes({&yShape})
                      .CompileInfo(&g_compileInfo)
                      .PlatformInfo(reinterpret_cast<char*>(&platform_info))
                      .NodeInputTd(0, xDtype, ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeInputTd(1, indicesDtype, ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeInputTd(2, vDtype, ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeOutputTd(0, yDtype, ge::FORMAT_ND, ge::FORMAT_ND)
                      .TilingData(param.get())
                      .Workspace(ws_size)
                      .Build();

    auto tilingContext = holder.GetContext<gert::TilingContext>();
    EXPECT_NE(tilingContext->GetPlatformInfo(), nullptr);
    tilingContext->GetPlatformInfo()->SetPlatformRes("SoCInfo", soc_infos);
    tilingContext->GetPlatformInfo()->SetPlatformRes("AICoreSpec", aicore_spec);
    tilingContext->GetPlatformInfo()->SetCoreNumByCoreType("AICore");
    tilingContext->GetPlatformInfo()->SetPlatformRes("AICoreintrinsicDtypeMap", intrinsics);

    return tiling_func(tilingContext);
}

// Convenience wrapper: x / v / y share the same dtype, indices is int32.
static ge::graphStatus RunTiling(ge::DataType dtype, gert::StorageShape& xShape, gert::StorageShape& indicesShape,
                                 gert::StorageShape& vShape, gert::StorageShape& yShape)
{
    return RunTiling(dtype, ge::DT_INT32, dtype, dtype, xShape, indicesShape, vShape, yShape);
}

TEST_F(InplaceUpdateTilingTest, tiling_1d_fp16)
{
    gert::StorageShape x = {{45}, {45}};
    gert::StorageShape idx = {{28}, {28}};
    gert::StorageShape v = {{28}, {28}};
    gert::StorageShape y = {{45}, {45}};
    EXPECT_EQ(RunTiling(ge::DT_FLOAT16, x, idx, v, y), ge::GRAPH_SUCCESS);
}

TEST_F(InplaceUpdateTilingTest, tiling_2d_fp32)
{
    gert::StorageShape x = {{10, 4}, {10, 4}};
    gert::StorageShape idx = {{3}, {3}};
    gert::StorageShape v = {{3, 4}, {3, 4}};
    gert::StorageShape y = {{10, 4}, {10, 4}};
    EXPECT_EQ(RunTiling(ge::DT_FLOAT, x, idx, v, y), ge::GRAPH_SUCCESS);
}

// 8 dims is the maximum supported rank.
TEST_F(InplaceUpdateTilingTest, max_dim_num_fp32)
{
    gert::StorageShape x = {{2, 1, 1, 1, 1, 1, 1, 2}, {2, 1, 1, 1, 1, 1, 1, 2}};
    gert::StorageShape idx = {{2}, {2}};
    gert::StorageShape v = {{2, 1, 1, 1, 1, 1, 1, 2}, {2, 1, 1, 1, 1, 1, 1, 2}};
    gert::StorageShape y = {{2, 1, 1, 1, 1, 1, 1, 2}, {2, 1, 1, 1, 1, 1, 1, 2}};
    EXPECT_EQ(RunTiling(ge::DT_FLOAT, x, idx, v, y), ge::GRAPH_SUCCESS);
}

// Reject case: x has 9 dims. v is a 1-D legal shape, so the only thing wrong
// with this case is the rank of x.
TEST_F(InplaceUpdateTilingTest, x_over_max_dim_num_reject)
{
    gert::StorageShape x = {{2, 1, 1, 1, 1, 1, 1, 1, 2}, {2, 1, 1, 1, 1, 1, 1, 1, 2}};
    gert::StorageShape idx = {{2}, {2}};
    gert::StorageShape v = {{2}, {2}};
    gert::StorageShape y = {{2, 1, 1, 1, 1, 1, 1, 1, 2}, {2, 1, 1, 1, 1, 1, 1, 1, 2}};
    EXPECT_EQ(RunTiling(ge::DT_FLOAT, x, idx, v, y), ge::GRAPH_FAILED);
}

// Reject case: v has 9 dims. x is a 1-D legal shape, so the only thing wrong
// with this case is the rank of v.
TEST_F(InplaceUpdateTilingTest, v_over_max_dim_num_reject)
{
    gert::StorageShape x = {{4}, {4}};
    gert::StorageShape idx = {{2}, {2}};
    gert::StorageShape v = {{2, 1, 1, 1, 1, 1, 1, 1, 2}, {2, 1, 1, 1, 1, 1, 1, 1, 2}};
    gert::StorageShape y = {{4}, {4}};
    EXPECT_EQ(RunTiling(ge::DT_FLOAT, x, idx, v, y), ge::GRAPH_FAILED);
}

// Reject case: x dtype int32 not in supported list [float16, float32].
TEST_F(InplaceUpdateTilingTest, x_unsupported_dtype_reject)
{
    gert::StorageShape x = {{10, 4}, {10, 4}};
    gert::StorageShape idx = {{3}, {3}};
    gert::StorageShape v = {{3, 4}, {3, 4}};
    gert::StorageShape y = {{10, 4}, {10, 4}};
    EXPECT_EQ(RunTiling(ge::DT_INT32, ge::DT_INT32, ge::DT_INT32, ge::DT_INT32, x, idx, v, y), ge::GRAPH_FAILED);
}

// Reject case: indices dtype float32 instead of int32.
TEST_F(InplaceUpdateTilingTest, indices_not_int32_reject)
{
    gert::StorageShape x = {{10, 4}, {10, 4}};
    gert::StorageShape idx = {{3}, {3}};
    gert::StorageShape v = {{3, 4}, {3, 4}};
    gert::StorageShape y = {{10, 4}, {10, 4}};
    EXPECT_EQ(RunTiling(ge::DT_FLOAT, ge::DT_FLOAT, ge::DT_FLOAT, ge::DT_FLOAT, x, idx, v, y), ge::GRAPH_FAILED);
}

// Reject case: v dtype float32 differs from x dtype float16.
TEST_F(InplaceUpdateTilingTest, v_dtype_mismatch_reject)
{
    gert::StorageShape x = {{10, 4}, {10, 4}};
    gert::StorageShape idx = {{3}, {3}};
    gert::StorageShape v = {{3, 4}, {3, 4}};
    gert::StorageShape y = {{10, 4}, {10, 4}};
    EXPECT_EQ(RunTiling(ge::DT_FLOAT16, ge::DT_INT32, ge::DT_FLOAT, ge::DT_FLOAT16, x, idx, v, y), ge::GRAPH_FAILED);
}

// Reject case: y dtype float32 differs from x dtype float16.
TEST_F(InplaceUpdateTilingTest, y_dtype_mismatch_reject)
{
    gert::StorageShape x = {{10, 4}, {10, 4}};
    gert::StorageShape idx = {{3}, {3}};
    gert::StorageShape v = {{3, 4}, {3, 4}};
    gert::StorageShape y = {{10, 4}, {10, 4}};
    EXPECT_EQ(RunTiling(ge::DT_FLOAT16, ge::DT_INT32, ge::DT_FLOAT16, ge::DT_FLOAT, x, idx, v, y), ge::GRAPH_FAILED);
}
