/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* !
 * \file reverse_sequence_tiling_key.h
 * \brief
 */
#ifndef REVERSE_SEQUENCE_TILING_KEY_H_
#define REVERSE_SEQUENCE_TILING_KEY_H_

#include "ascendc/host_api/tiling/template_argument.h"

#define TPL_MODE_ADDR_INT32 0
#define TPL_MODE_ADDR_INT64 1
#define TPL_MODE_DTYPE_B8  1
#define TPL_MODE_DTYPE_B16 2
#define TPL_MODE_DTYPE_B32 4
#define TPL_MODE_DTYPE_B64 8
#define TPL_MODE_TEMPLATE_SIMT  9
#define TPL_MODE_TEMPLATE_BSA 1
#define TPL_MODE_TEMPLATE_BAS 2
#define TPL_MODE_TEMPLATE_BS 3
#define TPL_MODE_TEMPLATE_SBA 4

namespace ReverseSequence {
ASCENDC_TPL_ARGS_DECL(
    ReverseSequence,
    ASCENDC_TPL_UINT_DECL(TEMPLATE_MODE, 4, ASCENDC_TPL_UI_LIST, TPL_MODE_TEMPLATE_SIMT, TPL_MODE_TEMPLATE_BSA, TPL_MODE_TEMPLATE_BAS, TPL_MODE_TEMPLATE_BS, TPL_MODE_TEMPLATE_SBA),
    ASCENDC_TPL_UINT_DECL(DYTPE_MODE, 2, ASCENDC_TPL_UI_LIST, TPL_MODE_DTYPE_B8, TPL_MODE_DTYPE_B16, TPL_MODE_DTYPE_B32, TPL_MODE_DTYPE_B64),
    ASCENDC_TPL_UINT_DECL(ADDR_MODE, 1, ASCENDC_TPL_UI_LIST, TPL_MODE_ADDR_INT32, TPL_MODE_ADDR_INT64)
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_TEMPLATE_SIMT),
        ASCENDC_TPL_UINT_SEL(DYTPE_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_DTYPE_B8, TPL_MODE_DTYPE_B16, TPL_MODE_DTYPE_B32, TPL_MODE_DTYPE_B64),
        ASCENDC_TPL_UINT_SEL(ADDR_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_ADDR_INT32, TPL_MODE_ADDR_INT64),
        ASCENDC_TPL_TILING_STRUCT_SEL(ReverseSequenceSimtTilingData4RegBase)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_TEMPLATE_BSA),
        ASCENDC_TPL_UINT_SEL(DYTPE_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_DTYPE_B8, TPL_MODE_DTYPE_B16, TPL_MODE_DTYPE_B32, TPL_MODE_DTYPE_B64),
        ASCENDC_TPL_UINT_SEL(ADDR_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_ADDR_INT64),
        ASCENDC_TPL_TILING_STRUCT_SEL(ReverseSequenceBSATilingData)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_TEMPLATE_BAS),
        ASCENDC_TPL_UINT_SEL(DYTPE_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_DTYPE_B8, TPL_MODE_DTYPE_B16, TPL_MODE_DTYPE_B32, TPL_MODE_DTYPE_B64),
        ASCENDC_TPL_UINT_SEL(ADDR_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_ADDR_INT64),
        ASCENDC_TPL_TILING_STRUCT_SEL(ReverseSequenceBASTilingData)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_TEMPLATE_BS),
        ASCENDC_TPL_UINT_SEL(DYTPE_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_DTYPE_B8, TPL_MODE_DTYPE_B16, TPL_MODE_DTYPE_B32, TPL_MODE_DTYPE_B64),
        ASCENDC_TPL_UINT_SEL(ADDR_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_ADDR_INT32, TPL_MODE_ADDR_INT64),
        ASCENDC_TPL_TILING_STRUCT_SEL(ReverseSequenceBSTilingData)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_TEMPLATE_SBA),
        ASCENDC_TPL_UINT_SEL(DYTPE_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_DTYPE_B8, TPL_MODE_DTYPE_B16, TPL_MODE_DTYPE_B32, TPL_MODE_DTYPE_B64),
        ASCENDC_TPL_UINT_SEL(ADDR_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_ADDR_INT32, TPL_MODE_ADDR_INT64),
        ASCENDC_TPL_TILING_STRUCT_SEL(ReverseSequenceA1SBATilingData)
    )
);

} // namespace ReverseSequence

#endif // REVERSE_SEQUENCE_TILING_KEY_H_