/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

/*!
 * \file fused_mul_apply_momentum_def.cpp
 * \brief FusedMulApplyMomentum 算子定义（6 输入 / 2 输出 + use_nesterov 属性）
 *
 * 将梯度缩放（mul）与动量更新（apply_momentum）融合为一个算子。
 *
 * dtype scope：2 dtype 通路（FP16/FP32），dtype 组合按各输入 DataType 列表逐列对应：
 *   列0 FP16 通路：所有输入/输出均为 FP16（内部计算提升至 FP32）
 *   列1 FP32 通路：所有输入/输出均为 FP32
 * inplace：var_out↔var、accum_out↔accum（GM 地址复用）。
 *
 * 公式（标准动量，use_nesterov=false）：
 *   grad      = x1 * x2
 *   accum_new = accum * momentum + grad
 *   var_new   = var - accum_new * lr
 *
 * 公式（Nesterov 动量，use_nesterov=true）：
 *   grad      = x1 * x2
 *   accum_new = accum * momentum + grad
 *   var_new   = var - (accum_new * momentum * lr + grad * lr)
 */
#include "register/op_def_registry.h"

namespace ops {
class FusedMulApplyMomentum : public OpDef {
public:
    explicit FusedMulApplyMomentum(const char* name) : OpDef(name)
    {
        // 输入 var：待更新的模型权重
        this->Input("var")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT16, ge::DT_FLOAT})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND});
        // 输入 accum：动量缓冲（与 var 同 shape）
        this->Input("accum")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT16, ge::DT_FLOAT})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND});
        // 输入 lr：学习率标量
        this->Input("lr")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT16, ge::DT_FLOAT})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND});
        // 输入 x1：梯度分量，与 x2 相乘得到 grad
        this->Input("x1")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT16, ge::DT_FLOAT})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND});
        // 输入 momentum：动量系数标量
        this->Input("momentum")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT16, ge::DT_FLOAT})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND});
        // 输入 x2：梯度缩放因子（如 LossScale reciprocal），与 x1 相乘得到 grad
        this->Input("x2")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT16, ge::DT_FLOAT})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND});

        // 输出 var：更新后的权重（inplace 复用输入 var）
        this->Output("var")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT16, ge::DT_FLOAT})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND});
        // 输出 accum：更新后的动量缓冲（inplace 复用输入 accum）
        this->Output("accum")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT16, ge::DT_FLOAT})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND});

        // 属性 use_nesterov：false=标准动量, true=Nesterov 动量
        this->Attr("use_nesterov").AttrType(OPTIONAL).Bool(false);

        OpAICoreConfig aiCoreConfig;
        aiCoreConfig.DynamicCompileStaticFlag(true)
            .DynamicFormatFlag(false)
            .DynamicRankSupportFlag(true)
            .DynamicShapeSupportFlag(true)
            .NeedCheckSupportFlag(false)
            .PrecisionReduceFlag(true)
            .ExtendCfgInfo("opFile.value", "fused_mul_apply_momentum");
        this->AICore().AddConfig("ascend950", aiCoreConfig);
    }
};

OP_ADD(FusedMulApplyMomentum);
} // namespace ops
