/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file add_row_ranges_proto.h
 * \brief
 */
#ifndef OPS_OP_PROTO_INC_ADD_ROW_RANGES_H_
#define OPS_OP_PROTO_INC_ADD_ROW_RANGES_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
 *@brief For each row r of x, sum src rows in range [indices[r,0], indices[r,1])
 *       and add the sum to x(r, :).
 *@par Inputs:
 *Three inputs, including:
 * @li x: A 2D ND Tensor. Must be one of the following types: float32, float16.
 * @li src: A 2D ND Tensor. Must be one of the following types: float32, float16.
 *        src.shape[1] must equal x.shape[1].
 * @li indices: A 2D ND Tensor of shape (M, 2). Must be of type int32.
 *        indices[r, 0] is start row, indices[r, 1] is end row (exclusive).
 *        (-1, -1) or start >= end means empty range (skip). \n

 *@par Outputs:
 *x: A 2D ND Tensor. Same shape and dtype as input x.
 *@par Third-party framework compatibility
 *Compatible with the Kaldi operator AddRowRanges.
 */
#ifndef OPS_PROTO_DEF_ADDROWRANGES
#define OPS_PROTO_DEF_ADDROWRANGES
REG_OP(AddRowRanges)
    .INPUT(x, TensorType({DT_FLOAT, DT_FLOAT16}))
    .INPUT(src, TensorType({DT_FLOAT, DT_FLOAT16}))
    .INPUT(indices, TensorType({DT_INT32}))
    .OUTPUT(x, TensorType({DT_FLOAT, DT_FLOAT16}))
    .OP_END_FACTORY_REG(AddRowRanges)
#endif
} // namespace ge

#endif // OPS_OP_PROTO_INC_ADD_ROW_RANGES_H_
