/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot - Iter2 */

/*!
 * \file bn_infer_grad_def.cpp
 * \brief BNInferGrad 算子定义，声明输入输出、属性和算子配置
 *
 * 3 输入（grads, scale, batch_variance）+ 1 属性（epsilon, float）→ 1 输出（x_backprop）
 *
 * dtype 策略：OpDef 声明并由Kernel直接支持fp16/fp32/bf16。
 *
 * dtype 约束（spec.yaml）:
 *   - grads / x_backprop: float16/float32/bfloat16
 *   - scale / batch_variance: 固定 float32
 *   - epsilon: float 标量，默认 0.0001
 *
 * format 约束：grads / x_backprop 使用 NCHW 或 NHWC；scale / batch_variance 为一维 ND。
 * prototype 的 grads / x_backprop 还声明 NC1HWC0，但不在 Ascend950 Vector 分支能力集内。
 */
#include "register/op_def_registry.h"

namespace ops {
class BNInferGrad : public OpDef {
public:
    explicit BNInferGrad(const char* name) : OpDef(name)
    {
        this->Input("grads") // 输入0：上游梯度；C 轴由 NCHW/NHWC 逻辑格式决定
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT16, ge::DT_FLOAT, ge::DT_BF16, ge::DT_FLOAT16, ge::DT_FLOAT, ge::DT_BF16})
            .Format(
                {ge::FORMAT_NCHW, ge::FORMAT_NCHW, ge::FORMAT_NCHW, ge::FORMAT_NHWC, ge::FORMAT_NHWC, ge::FORMAT_NHWC})
            .UnknownShapeFormat(
                {ge::FORMAT_NCHW, ge::FORMAT_NCHW, ge::FORMAT_NCHW, ge::FORMAT_NHWC, ge::FORMAT_NHWC, ge::FORMAT_NHWC})
            .AutoContiguous();
        this->Input("scale") // 输入1：BN 缩放参数 [C]
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT, ge::DT_FLOAT, ge::DT_FLOAT, ge::DT_FLOAT, ge::DT_FLOAT, ge::DT_FLOAT})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat(
                {ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();
        this->Input("batch_variance") // 输入2：运行时方差 [C]
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT, ge::DT_FLOAT, ge::DT_FLOAT, ge::DT_FLOAT, ge::DT_FLOAT, ge::DT_FLOAT})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat(
                {ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();
        this->Output("x_backprop") // 输出0：shape、dtype 和逻辑格式均与 grads 一致
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT16, ge::DT_FLOAT, ge::DT_BF16, ge::DT_FLOAT16, ge::DT_FLOAT, ge::DT_BF16})
            .Format(
                {ge::FORMAT_NCHW, ge::FORMAT_NCHW, ge::FORMAT_NCHW, ge::FORMAT_NHWC, ge::FORMAT_NHWC, ge::FORMAT_NHWC})
            .UnknownShapeFormat(
                {ge::FORMAT_NCHW, ge::FORMAT_NCHW, ge::FORMAT_NCHW, ge::FORMAT_NHWC, ge::FORMAT_NHWC, ge::FORMAT_NHWC})
            .AutoContiguous();

        this->Attr("epsilon").AttrType(OPTIONAL).Float(0.0001f); // 防除零常数，默认 1e-4

        OpAICoreConfig aiCoreConfig;
        aiCoreConfig.DynamicCompileStaticFlag(true)
            .DynamicFormatFlag(true)
            .DynamicRankSupportFlag(true)
            .DynamicShapeSupportFlag(true)
            .NeedCheckSupportFlag(false)
            .PrecisionReduceFlag(true)
            .ExtendCfgInfo("opFile.value", "bn_infer_grad");
        this->AICore().AddConfig("ascend950", aiCoreConfig);
    }
};
OP_ADD(BNInferGrad);
} // namespace ops
