/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file softsign_tiling_arch35.cpp
 * \brief Softsign 算子 Host Tiling 实现（atvoss 框架 - Elewise 模式, arch35）
 *
 * dtype 由 def 驱动展开，Tiling 仅负责计算 TilingData，不编码 dtype 到 TilingKey。
 */

#include "register/op_def_registry.h"
#include "op_common/log/log.h"
#include "atvoss/elewise/elewise_tiling.h"
#include "../../op_kernel/arch35/softsign_dag.h"
#include "../../op_kernel/arch35/softsign_struct.h"
#include "../../op_kernel/arch35/softsign_tiling_key.h"

namespace optiling {

using namespace ge;
using Ops::Base::bfloat16_t;
using Ops::Base::ElewiseBaseTiling;
using Ops::Base::half;

static constexpr size_t MAX_INPUT_RANK = 8;

template <typename OpDag>
static ge::graphStatus RunEleTiling(gert::TilingContext* context, SoftsignTilingData* tilingData)
{
    ElewiseBaseTiling eleTiling(context);
    ge::graphStatus ret = eleTiling.DoTiling<OpDag>(tilingData->baseTiling);
    OP_CHECK_IF(ret != ge::GRAPH_SUCCESS, OP_LOGE(context, "Softsign: DoTiling failed, ret=%d", static_cast<int>(ret)),
                return ret);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus DoTilingByDtype(gert::TilingContext* context, ge::DataType dtype, SoftsignTilingData* tilingData)
{
    if (dtype == ge::DT_FLOAT) {
        return RunEleTiling<SoftsignOp::GraphSoftsignByDtype<float>::OpDag>(context, tilingData);
    } else if (dtype == ge::DT_FLOAT16) {
        return RunEleTiling<SoftsignOp::GraphSoftsignByDtype<half>::OpDag>(context, tilingData);
    } else if (dtype == ge::DT_BF16) {
        return RunEleTiling<SoftsignOp::GraphSoftsignByDtype<bfloat16_t>::OpDag>(context, tilingData);
    }
    OP_LOGE(context, "Softsign: unsupported dtype=%d", static_cast<int>(dtype));
    return ge::GRAPH_FAILED;
}

static ge::graphStatus PrepareWorkspace(gert::TilingContext* context)
{
    constexpr uint64_t WORKSPACE_RESERVE_BYTE = 16UL * 1024 * 1024;
    size_t* currentWorkspace = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = WORKSPACE_RESERVE_BYTE;
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus SoftsignTilingFunc(gert::TilingContext* context)
{
    auto inputDesc = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
    ge::DataType dtype = inputDesc->GetDataType();

    auto inputShape = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputShape);
    auto storageShape = inputShape->GetStorageShape();
    const int64_t unknownRankDim = -2;
    const size_t inputRank = storageShape.GetDimNum();

    bool isUnknownRank = (inputRank == 1 && storageShape.GetDim(0) == unknownRankDim);
    if (!isUnknownRank) {
        OP_CHECK_IF(inputRank > MAX_INPUT_RANK,
                    OP_LOGE(context, "Softsign: input x rank must be no greater than %zu, but got %zu.", MAX_INPUT_RANK,
                            inputRank),
                    return ge::GRAPH_FAILED);
    }

    // 标量(rank==0)与空 tensor(totalNum==0)统一放行：SetBlockDim(1) + return SUCCESS，
    // 与 relu6/selu/hard_shrink 等 15 个同类 arch35 elementwise 算子一致
    if (!isUnknownRank && storageShape.GetShapeSize() == 0) {
        context->SetBlockDim(1);
        uint32_t schMode = static_cast<uint32_t>(SOFTSIGN_SCH_MODE_DEFAULT);
        ASCENDC_TPL_SEL_PARAM(context, schMode);
        return ge::GRAPH_SUCCESS;
    }

    OP_CHECK_IF(PrepareWorkspace(context) != ge::GRAPH_SUCCESS, OP_LOGE(context, "Softsign: PrepareWorkspace failed"),
                return ge::GRAPH_FAILED);

    auto tilingData = context->GetTilingData<SoftsignTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tilingData);
    auto ret = DoTilingByDtype(context, dtype, tilingData);
    OP_CHECK_IF(ret != ge::GRAPH_SUCCESS, OP_LOGE(context, "Softsign: DoTilingByDtype failed"), return ret);

    uint32_t schMode = static_cast<uint32_t>(SOFTSIGN_SCH_MODE_DEFAULT);
    ASCENDC_TPL_SEL_PARAM(context, schMode);
    context->SetBlockDim(tilingData->baseTiling.blockNum);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForSoftsign([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

struct SoftsignCompileInfo {};

IMPL_OP_OPTILING(Softsign).Tiling(SoftsignTilingFunc).TilingParse<SoftsignCompileInfo>(TilingParseForSoftsign);

} // namespace optiling
