/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

/*!
 * \file avg_pool1_d_tiling_key.h
 * \brief tiling key declare for avg_pool1_d — single default scene mode (MDE §3.2)
 *        dtype 不枚举，由 DTYPE_ 宏自动实例化
 */

#ifndef AVG_POOL1D_TILING_KEY_H
#define AVG_POOL1D_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

// 单一默认场景模式，不枚举 dtype
#define AVG_POOL1D_SCH_MODE_DEFAULT 0

ASCENDC_TPL_ARGS_DECL(AvgPool1D, ASCENDC_TPL_UINT_DECL(schMode, 1, ASCENDC_TPL_UI_LIST, AVG_POOL1D_SCH_MODE_DEFAULT));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                                     ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, AVG_POOL1D_SCH_MODE_DEFAULT),
                                     ASCENDC_TPL_TILING_STRUCT_SEL(AvgPool1dTilingData)));

#endif // AVG_POOL1D_TILING_KEY_H
