/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file sparse_apply_adadelta_proto.h
 * \brief Proto definition for SparseApplyAdadelta operator
 */
#ifndef OPS_OP_PROTO_INC_SPARSE_APPLY_ADADELTA_H_
#define OPS_OP_PROTO_INC_SPARSE_APPLY_ADADELTA_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
 *@brief Applies sparse AdaDelta optimization to update variable, accumulator,
 *       and accumulator-update tensors for the rows specified by indices.
 *@par Inputs:
 *Eight inputs, including:
 * @li var: A Tensor of type float32. The variable to be updated.
 * @li accum: A Tensor of type float32. Gradient squared accumulator, same shape as var.
 * @li accum_update: A Tensor of type float32. Update squared accumulator, same shape as var.
 * @li lr: A Tensor of type float32. Learning rate scalar.
 * @li rho: A Tensor of type float32. Decay rate scalar.
 * @li epsilon: A Tensor of type float32. Numerical stability scalar.
 * @li grad: A Tensor of type float32. Gradient tensor, first dim equals indices length.
 * @li indices: A Tensor of type int32 or int64. Row indices to update, values must be unique.
 *
 *@par Outputs:
 *Three outputs, including:
 * @li var: A Tensor of type float32. Updated variable, same shape as input var.
 * @li accum: A Tensor of type float32. Updated gradient squared accumulator.
 * @li accum_update: A Tensor of type float32. Updated update squared accumulator.
 *
 *@par Attributes:
 * @li use_locking: An optional bool. Defaults to false. If true, use locks for variable update.
 *
 *@par Third-party framework compatibility
 *Compatible with the TensorFlow operator SparseApplyAdadelta.
 */
#ifndef OPS_PROTO_DEF_SPARSEAPPLYADADELTA
#define OPS_PROTO_DEF_SPARSEAPPLYADADELTA
REG_OP(SparseApplyAdadelta)
    .INPUT(var, TensorType({DT_FLOAT}))
    .INPUT(accum, TensorType({DT_FLOAT}))
    .INPUT(accum_update, TensorType({DT_FLOAT}))
    .INPUT(lr, TensorType({DT_FLOAT}))
    .INPUT(rho, TensorType({DT_FLOAT}))
    .INPUT(epsilon, TensorType({DT_FLOAT}))
    .INPUT(grad, TensorType({DT_FLOAT}))
    .INPUT(indices, TensorType({DT_INT32, DT_INT64}))
    .OUTPUT(var, TensorType({DT_FLOAT}))
    .OUTPUT(accum, TensorType({DT_FLOAT}))
    .OUTPUT(accum_update, TensorType({DT_FLOAT}))
    .ATTR(use_locking, Bool, false)
    .OP_END_FACTORY_REG(SparseApplyAdadelta)
#endif
} // namespace ge

#endif // OPS_OP_PROTO_INC_SPARSE_APPLY_ADADELTA_H_
