#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.

# Generated By CANNBot

"""
avg_pool1d Golden script (TestSpec __spec__ mode).

Registration: Kernel/GEIR only (name "avg_pool1_d").
  - SE section 6.6 aclnn interface is reserved only, no implementation, no ACLNN path.
  - No PyTorch adaptation, no E2E path.

Golden source: SE doc chapter 7, using PyTorch competitor API
torch.nn.functional.avg_pool1d, following section 5.2 formula.

Asymmetric padding: PyTorch avg_pool1d padding only supports single int (symmetric),
but our REG_OP pads is ListInt(2) (asymmetric).
Strategy:
  - pads[0]==pads[1]: use PyTorch directly;
  - pads[0]!=pads[1]: manual pad + PyTorch(padding=0);
  - Output length by SE section 5.2 formula (with ceil_mode fix), truncate PyTorch output
    (PyTorch padding=0 does not do ceil_mode fix, may output 1 extra window);
  - count_include_pad=False + asymmetric: first get sum/divisor_padded via cip=True,
    then fix denominator by valid element count.


float16: no unconditional promote in Golden. cross_check auto Promote
contract: TTK promotes dtype before calling Golden (float16->float32),
Golden and _torch_compute preserve input dtype, no cast back.
"""

import numpy as np
import torch
import torch.nn.functional as F

# __spec__: TestSpec registry.
# TTK Test framework looks up operator name via this dict "avg_pool1_d" corresponding TestSpec class,
# then calls TestSpec.golden() method to get CPU reference result,with NPU output for precision comparison.
__spec__ = {
    "avg_pool1_d": "AvgPool1DTestSpec",
}


def _torch_compute(
    x, ksize, strides, pad_left, pad_right, ceil_mode, count_include_pad
):
    """
    shared Torch compute core(Tensor -> Tensor).

    Golden wrapper with ThirdPartyImpl , avg_pool1d computation.
    Constraints (golden.md section 0.2/section 0.6):
      - No numpy/CPU side effects: no .cpu()/.numpy()/detach()
      - No hardcoded float32; new tensors inherit input x dtype/device
      - No dtype cast back (Promote handled by TTK)

    parameters:
        x: torch.Tensor, shape (N, C, L) or (C, L) or >3D(for 3D)
        ksize / strides / pad_left / pad_right: int(by wrapper handle)
        ceil_mode / count_include_pad: bool(by wrapper handle)

    returns:
        y: torch.Tensor, with x  dtype/device, ndim forwith x
    """
    orig_ndim = x.ndim
    orig_shape = list(x.shape)

    # avg_pool1d input(L)onPyTorch 3D input (N, C, L)
    # - >3D: beforefor Nin C=1after L not
    # - 2D: inbefore N=1 (1, C, L)
    if orig_ndim > 3:
        front_shape = orig_shape[:-1]
        x = x.reshape(-1, 1, x.shape[-1])
    elif orig_ndim == 2:
        x = x.unsqueeze(0)

    L = x.shape[-1]

    if L == 0:
        # @constraint: SE section 1.4 boundary: L==0 returns L_out=0
        # PyTorch avg_pool1d does not support L=0, return empty tensor early
        y_shape = list(x.shape)
        y_shape[-1] = 0
        y = x.new_zeros(y_shape)
    elif pad_left == pad_right and pad_left <= ksize / 2:
        # ===== paddingpad_left == pad_right=====
        # padding PyTorch avg_pool1d
        # PyTorch padding parameters int
        # Matches this scenario. PyTorch behavior is consistent with SE section 5.2 formula,
        #
        y = F.avg_pool1d(
            x,
            kernel_size=ksize,
            stride=strides,
            padding=pad_left,
            ceil_mode=ceil_mode,
            count_include_pad=count_include_pad,
        )
    else:
        # ===== not paddingpad_left != pad_right=====
        # PyTorch avg_pool1d padding parameters int
        # not paddingstrategy
        # 1. F.pad ininput 0to padded input
        # 2. PyTorch avg_pool1dpadding=0in padded inputoncompute
        x_padded = F.pad(x, (pad_left, pad_right), mode="constant", value=0)
        L_padded = L + pad_left + pad_right

        # Compute L_out by SE section 5.2 formula (with ceil_mode fix).
        # PyTorch avg_pool1d in padding=0 not ceil_mode not
        # in padding after SE output 1
        # SE compute L_out PyTorch output
        if ceil_mode:
            L_out = (L_padded - ksize + strides - 1) // strides + 1
        else:
            L_out = (L_padded - ksize) // strides + 1
        if pad_left > 0 and (L_out - 1) * strides >= L + pad_left:
            L_out -= 1
        L_out = max(L_out, 0)

        if count_include_pad:
            # ----- 2acount_include_pad=True -----
            # "count_include_pad=True" divisor padding
            # divisor = in padded incount
            # PyTorch in count_include_pad=True forwith SE section 5.2
            # resulttobeforecompute L_out
            y = F.avg_pool1d(
                x_padded,
                kernel_size=ksize,
                stride=strides,
                padding=0,
                ceil_mode=ceil_mode,
                count_include_pad=True,
            )
            y = y[..., :L_out]
        else:
            # ----- 2bcount_include_pad=False -----
            # "count_include_pad=False" divisornot padding
            # divisor = intersection of window and original data region
            #
            # inon padding PyTorch in padding=0
            # iscountis 0not
            # count_include_pad=False result
            #
            #
            # 1. count_include_pad=True to y_with_pad = sum / divisor_padded
            # 2. sum = y_with_pad * divisor_padded
            # 3. divisor_valid result = sum / divisor_valid
            #
            # ceil_mode=True downafter padded
            # divisor_padded < ksizenotfor ksize
            # compute divisor_padded and divisor_valid
            y_with_pad = F.avg_pool1d(
                x_padded,
                kernel_size=ksize,
                stride=strides,
                padding=0,
                ceil_mode=ceil_mode,
                count_include_pad=True,
            )
            y_with_pad = y_with_pad[..., :L_out]

            # Tensorw = [0, 1, ..., L_out-1]compute
            # input x dtype/device float32Golden
            w = torch.arange(L_out, device=x.device).to(x.dtype)
            win_start = strides * w  # in padded
            win_end = win_start + ksize  # in padded ()
            # divisor_padded: divisor for cip=True = intersection of window and padded space
            # (ceil_mode: last window may exceed padded right boundary, need clamp)
            padded_end = torch.clamp(win_end, max=float(L_padded))
            divisor_padded = padded_end - win_start
            # divisor_valid: count_include_pad=False = intersection of window and original data region
            # original data region in padded space is [pad_left, pad_left + L)
            valid_start = torch.clamp(win_start, min=float(pad_left))
            valid_end = torch.clamp(win_end, max=float(pad_left + L))
            divisor_valid = torch.clamp(
                valid_end - valid_start, min=1.0
            )  # at least 1, avoid division by zero
            # result = sum / divisor_valid
            # where sum = y_with_pad * divisor_padded (reverse from cip=True result)
            # .view(1, 1, -1) reshapes 1D index to (1, 1, L_out) for broadcasting
            y = (
                y_with_pad
                * divisor_padded.view(1, 1, -1)
                / divisor_valid.view(1, 1, -1)
            )

    # Restore original ndim: reshape back to original shape
    if orig_ndim > 3:
        y = y.reshape(*front_shape, y.shape[-1])
    elif orig_ndim == 2:
        y = y.squeeze(0)

    return y


class AvgPool1DTestSpec:
    """avg_pool1d TestSpec, shared by Kernel and GEIR."""

    def golden(
        x, *, ksize, strides, pads, ceil_mode=False, count_include_pad=False, **kwargs
    ):
        """
        Golden function for avg_pool1_d (Kernel/GEIR path).

        Parameter names and order follow @avg_pool1_d_def.cpp (excluding Output):
          Input: x (REQUIRED)
          Attr:  ksize (REQUIRED), strides (REQUIRED), pads (REQUIRED ListInt),
                 ceil_mode (OPTIONAL Bool false), count_include_pad (OPTIONAL Bool false)

        Args:
            x: numpy.ndarray, shape (N, C, L) or (C, L) or >3D, dtype float16/float32
            ksize/strides/pads/ceil_mode/count_include_pad: operator attributes
            **kwargs: {input,output}_{dtypes,ori_shapes,formats,ori_formats},
                      full_soc_version, short_soc_version, testcase_name, golden_mode

        Returns:
            list[numpy.ndarray]: output y,shape (..., L_out), dtype withinput
            (Promote down dtype forafter dtype,by TTK with NPU output)
        """
        # ===== numpy -> torch -> numpy conversion =====
        # TTK passes x as numpy.ndarray, Golden uses PyTorch.
        # Three-step conversion:
        #   1. numpy -> torch: ascontiguousarray + from_numpy;
        #   2. torch compute: call _torch_compute;
        #   3. torch -> numpy: detach().cpu().numpy().
        # Return list[ndarray], even for single output (TTK convention).

        x_t = torch.from_numpy(np.ascontiguousarray(x))
        result = _torch_compute(
            x_t,
            int(ksize),
            int(strides),
            int(pads[0]),
            int(pads[1]),
            bool(ceil_mode),
            bool(count_include_pad),
        )
        return [result.detach().cpu().numpy()]

    class ThirdPartyImpl:
        """torch provider third-party implementation.

        __init__ Attribute preprocessing (int/bool conversion, pads split);
        __call__ Call _torch_compute, receive provider Tensor, no downgrade.
        """

        # ===== __init__attributeshandle=====
        # Convert and split attributes from provider,
        # store as instance attributes for __call__.
        #   - int()/bool(): Ensure correct types (provider may pass numpy scalars)
        #   - pads split: ListInt [pad_left, pad_right] -> two ints
        def __init__(
            self,
            ksize,
            strides,
            pads,
            ceil_mode=False,
            count_include_pad=False,
            **kwargs,
        ):
            self.ksize = int(ksize)
            self.strides = int(strides)
            self.pad_left = int(pads[0])
            self.pad_right = int(pads[1])
            self.ceil_mode = bool(ceil_mode)
            self.count_include_pad = bool(count_include_pad)

        # ===== __call__:Execute computation (called each forward)=====
        # provider torch.Tensor numpy
        # _torch_compute not numpy
        # with golden
        # - golden: inputis numpy -> -> output numpy TTK
        # - __call__: inputis torch.Tensor -> compute -> output torch.Tensor E2E
        # shared _torch_compute count
        def __call__(self, x, **kwargs):
            return [
                _torch_compute(
                    x,
                    self.ksize,
                    self.strides,
                    self.pad_left,
                    self.pad_right,
                    self.ceil_mode,
                    self.count_include_pad,
                )
            ]

    # third_party: key "torch" PyTorch provider
    # TTK in E2E to ThirdPartyImpl class
    third_party = {"torch": ThirdPartyImpl}

    # tolerance: config
    # "standard": "cross_check" -
    # not atol/rtol valueis NPU operatoroutputwithPyTorch
    # outputmethod golden
    # withoutputoperator
    # "level": "L1" - L1
    tolerance = {
        "float16": {"standard": "cross_check", "level": "L1"},
        "float32": {"standard": "cross_check", "level": "L1"},
    }
