/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef MAX_POOL3_D_TILING_KEY_H_
#define MAX_POOL3_D_TILING_KEY_H_

#include "ascendc/host_api/tiling/template_argument.h"
#include "max_pool3_d_tiling_data.h"

#define MAX_POOL3_D_TPL_SCH_MODE_GENERAL 0
#define MAX_POOL3_D_TPL_SCH_MODE_NCDHW_STRIDE2 1
#define MAX_POOL3_D_TPL_SCH_MODE_NDHWC_STRIDE2 2
#define MAX_POOL3_D_TPL_SCH_MODE_NDC1HWC0 3
#define MAX_POOL3_D_TPL_SCH_MODE_TINY_K3 4
#define MAX_POOL3_D_TPL_SCH_MODE_NCDHW_SMALL_DEPTH_STRIDE2 5
#define MAX_POOL3_D_TPL_SCH_MODE_DILATED_W_FEATURE 6
#define MAX_POOL3_D_TPL_SCH_MODE_K1_WIDE_FEATURE 7
#define MAX_POOL3_D_TPL_SCH_MODE_POOL2_DEPTH_HEAVY 8
#define MAX_POOL3_D_TPL_SCH_MODE_K1_COMPACT_FEATURE 9
#define MAX_POOL3_D_TPL_SCH_MODE_H_ONLY_FEATURE 10
#define MAX_POOL3_D_TPL_SCH_MODE_POOL2_MULTI_BATCH_FEATURE 11
#define MAX_POOL3_D_TPL_SCH_MODE_D3W3_FEATURE 12
#define MAX_POOL3_D_TPL_SCH_MODE_POOL2_CHANNEL_HEAVY 13
#define MAX_POOL3_D_TPL_SCH_MODE_TINY_K3_HALF_GROUPED 14
#define MAX_POOL3_D_TPL_SCH_MODE_POOL2_HALF_WIDE_CHANNEL 15
#define MAX_POOL3_D_TPL_SCH_MODE_POOL2_BALANCED_CHANNEL 16
#define MAX_POOL3_D_TPL_SCH_MODE_K1_COMPACT_LOGICAL 17
#define MAX_POOL3_D_TPL_SCH_MODE_D3H3_PHYSICAL_FEATURE 18
#define MAX_POOL3_D_TPL_SCH_MODE_D2H3W2_PHYSICAL_FEATURE 19
#define MAX_POOL3_D_TPL_SCH_MODE_NCDHW_POOL2_FEATURE 20
#define MAX_POOL3_D_TPL_SCH_MODE_K1_WIDE_FLOAT_PHYSICAL_FEATURE 21
#define MAX_POOL3_D_TPL_SCH_MODE_H_ONLY_HALF_NDHWC_FEATURE 22
#define MAX_POOL3_D_TPL_SCH_MODE_POOL2_MULTI_BATCH_HALF_NDHWC_FEATURE 23
#define MAX_POOL3_D_TPL_SCH_MODE_DILATED_W_FLOAT_NCDHW_FEATURE 24
#define MAX_POOL3_D_TPL_SCH_MODE_LIST                                                                                 \
    MAX_POOL3_D_TPL_SCH_MODE_GENERAL, MAX_POOL3_D_TPL_SCH_MODE_NCDHW_STRIDE2, MAX_POOL3_D_TPL_SCH_MODE_NDHWC_STRIDE2, \
        MAX_POOL3_D_TPL_SCH_MODE_NDC1HWC0, MAX_POOL3_D_TPL_SCH_MODE_TINY_K3,                                          \
        MAX_POOL3_D_TPL_SCH_MODE_NCDHW_SMALL_DEPTH_STRIDE2, MAX_POOL3_D_TPL_SCH_MODE_DILATED_W_FEATURE,               \
        MAX_POOL3_D_TPL_SCH_MODE_K1_WIDE_FEATURE, MAX_POOL3_D_TPL_SCH_MODE_POOL2_DEPTH_HEAVY,                         \
        MAX_POOL3_D_TPL_SCH_MODE_K1_COMPACT_FEATURE, MAX_POOL3_D_TPL_SCH_MODE_H_ONLY_FEATURE,                         \
        MAX_POOL3_D_TPL_SCH_MODE_POOL2_MULTI_BATCH_FEATURE, MAX_POOL3_D_TPL_SCH_MODE_D3W3_FEATURE,                    \
        MAX_POOL3_D_TPL_SCH_MODE_POOL2_CHANNEL_HEAVY, MAX_POOL3_D_TPL_SCH_MODE_TINY_K3_HALF_GROUPED,                  \
        MAX_POOL3_D_TPL_SCH_MODE_POOL2_HALF_WIDE_CHANNEL, MAX_POOL3_D_TPL_SCH_MODE_POOL2_BALANCED_CHANNEL,            \
        MAX_POOL3_D_TPL_SCH_MODE_K1_COMPACT_LOGICAL, MAX_POOL3_D_TPL_SCH_MODE_D3H3_PHYSICAL_FEATURE,                  \
        MAX_POOL3_D_TPL_SCH_MODE_D2H3W2_PHYSICAL_FEATURE, MAX_POOL3_D_TPL_SCH_MODE_NCDHW_POOL2_FEATURE,               \
        MAX_POOL3_D_TPL_SCH_MODE_K1_WIDE_FLOAT_PHYSICAL_FEATURE, MAX_POOL3_D_TPL_SCH_MODE_H_ONLY_HALF_NDHWC_FEATURE,  \
        MAX_POOL3_D_TPL_SCH_MODE_POOL2_MULTI_BATCH_HALF_NDHWC_FEATURE,                                                \
        MAX_POOL3_D_TPL_SCH_MODE_DILATED_W_FLOAT_NCDHW_FEATURE

ASCENDC_TPL_ARGS_DECL(MaxPool3D,
                      ASCENDC_TPL_UINT_DECL(schMode, 16, ASCENDC_TPL_UI_LIST, MAX_POOL3_D_TPL_SCH_MODE_LIST));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                                     ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, MAX_POOL3_D_TPL_SCH_MODE_LIST),
                                     ASCENDC_TPL_TILING_STRUCT_SEL(MaxPool3DTilingData)));

#endif // MAX_POOL3_D_TILING_KEY_H_
