/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License")
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

 /*!
 * \file index_fill_tiling_key.h
 * \brief
 */
#ifndef INDEX_FILL_TILING_KEY_H_
#define INDEX_FILL_TILING_KEY_H_

#include "ascendc/host_api/tiling/template_argument.h"

#define TPL_MODE_TEMPLATE_SIMD  0
#define TPL_MODE_TEMPLATE_SIMT  1
#define TPL_MODE_TEMPLATE_EMPTY 2
#define TPL_MODE_DTYPE_B32      4
#define TPL_MODE_DTYPE_B64      8

namespace IndexFill {
ASCENDC_TPL_ARGS_DECL(IndexFill,
    ASCENDC_TPL_UINT_DECL(TEMPLATE_MODE, 2, ASCENDC_TPL_UI_LIST, TPL_MODE_TEMPLATE_SIMD, TPL_MODE_TEMPLATE_SIMT, TPL_MODE_TEMPLATE_EMPTY),
    ASCENDC_TPL_DTYPE_DECL(DYTPE_MODE, TPL_MODE_DTYPE_B32, TPL_MODE_DTYPE_B64)
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_TEMPLATE_SIMD),
        ASCENDC_TPL_DTYPE_SEL(DYTPE_MODE, TPL_MODE_DTYPE_B32)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_TEMPLATE_SIMD),
        ASCENDC_TPL_DTYPE_SEL(DYTPE_MODE, TPL_MODE_DTYPE_B64)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_TEMPLATE_SIMT),
        ASCENDC_TPL_DTYPE_SEL(DYTPE_MODE, TPL_MODE_DTYPE_B32)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_TEMPLATE_SIMT),
        ASCENDC_TPL_DTYPE_SEL(DYTPE_MODE, TPL_MODE_DTYPE_B64)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_TEMPLATE_EMPTY),
        ASCENDC_TPL_DTYPE_SEL(DYTPE_MODE, TPL_MODE_DTYPE_B32)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, TPL_MODE_TEMPLATE_EMPTY),
        ASCENDC_TPL_DTYPE_SEL(DYTPE_MODE, TPL_MODE_DTYPE_B64)
    )
);

} // namespace IndexFill

#endif // INDEX_FILL_TILING_KEY_H_