/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file inplace_update_tiling_arch35.cpp
 * \brief tiling implementation for InplaceUpdate
 */

#include "log/log.h"
#include "register/op_impl_registry.h"
#include "platform/platform_ascendc.h"
#include "util/math_util.h"
#include "util/platform_util.h"
#include "op_host/tiling_util.h"
#include "op_host/tiling_templates_registry.h"
#include "../../op_kernel/arch35/inplace_update_tiling_data.h"
#include "../../op_kernel/arch35/inplace_update_tiling_key.h"

namespace optiling {

using namespace Ops::NN::OpTiling;

constexpr uint32_t DCACHE_SIZE = 128 * 1024;
constexpr uint32_t STATIC_UB_ESTIMATE = 0;
// 输入张量最多支持 8 维（参见 README 约束说明：支持 1D~8D）
static constexpr size_t MAX_INPUT_DIM_NUM = 8;

struct InplaceUpdateCompileInfo {};

static ge::graphStatus InplaceUpdateTilingFunc(gert::TilingContext* context)
{
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(context->GetPlatformInfo());
    int64_t coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);

    auto xShape = context->GetInputShape(0);
    auto indicesShape = context->GetInputShape(1);
    auto vShape = context->GetInputShape(2);
    OP_CHECK_NULL_WITH_CONTEXT(context, xShape);
    OP_CHECK_NULL_WITH_CONTEXT(context, indicesShape);
    OP_CHECK_NULL_WITH_CONTEXT(context, vShape);

    auto xStorageShape = xShape->GetStorageShape();
    auto indicesStorageShape = indicesShape->GetStorageShape();
    auto vStorageShape = vShape->GetStorageShape();

    OP_CHECK_IF(xStorageShape.GetDimNum() > MAX_INPUT_DIM_NUM,
                OP_LOGE(context, "input x dim num %zu not supported, max support %zu dims.", xStorageShape.GetDimNum(),
                        MAX_INPUT_DIM_NUM),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(vStorageShape.GetDimNum() > MAX_INPUT_DIM_NUM,
                OP_LOGE(context, "input v dim num %zu not supported, max support %zu dims.", vStorageShape.GetDimNum(),
                        MAX_INPUT_DIM_NUM),
                return ge::GRAPH_FAILED);

    int32_t n = static_cast<int32_t>(xStorageShape.GetDim(0));
    int32_t k = static_cast<int32_t>(indicesStorageShape.GetDim(0));
    int64_t innerSize = 1;
    for (size_t d = 1; d < xStorageShape.GetDimNum(); d++) {
        innerSize *= xStorageShape.GetDim(d);
    }

    OP_CHECK_IF(vStorageShape.GetDim(0) != k, OP_LOGE(context, "v.shape[0] must equal indices length K"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(xStorageShape.GetDimNum() != vStorageShape.GetDimNum(), OP_LOGE(context, "x.ndim must equal v.ndim"),
                return ge::GRAPH_FAILED);
    for (size_t d = 1; d < xStorageShape.GetDimNum(); d++) {
        OP_CHECK_IF(xStorageShape.GetDim(d) != vStorageShape.GetDim(d),
                    OP_LOGE(context, "x.shape[d] must equal v.shape[d] for d >= 1"), return ge::GRAPH_FAILED);
    }

    auto xDesc = context->GetInputDesc(0);
    auto indicesDesc = context->GetInputDesc(1);
    auto vDesc = context->GetInputDesc(2);
    auto yDesc = context->GetOutputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, xDesc);
    OP_CHECK_NULL_WITH_CONTEXT(context, indicesDesc);
    OP_CHECK_NULL_WITH_CONTEXT(context, vDesc);
    OP_CHECK_NULL_WITH_CONTEXT(context, yDesc);
    ge::DataType xDtype = xDesc->GetDataType();
    OP_CHECK_IF(xDtype != ge::DT_FLOAT16 && xDtype != ge::DT_FLOAT,
                OP_LOGE(context, "input x dtype not supported, only support [float16, float32]"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(indicesDesc->GetDataType() != ge::DT_INT32, OP_LOGE(context, "indices dtype must be int32"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(vDesc->GetDataType() != xDtype, OP_LOGE(context, "v.dtype must equal x.dtype"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(yDesc->GetDataType() != xDtype, OP_LOGE(context, "y.dtype must equal x.dtype"),
                return ge::GRAPH_FAILED);

    int32_t perCoreN;
    int32_t needCoreNum;
    if (n == 0) {
        perCoreN = 0;
        needCoreNum = 1;
    } else {
        perCoreN = static_cast<int32_t>(Ops::Base::CeilDiv(static_cast<int64_t>(n), coreNum));
        needCoreNum = static_cast<int32_t>(Ops::Base::CeilDiv(static_cast<int64_t>(n), static_cast<int64_t>(perCoreN)));
    }

    InplaceUpdateTilingData* tiling = context->GetTilingData<InplaceUpdateTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    auto ret = memset_s(tiling, sizeof(InplaceUpdateTilingData), 0, sizeof(InplaceUpdateTilingData));
    OP_CHECK_IF(ret != EOK, OP_LOGE(context, "memset_s tiling data error"), return ge::GRAPH_FAILED);
    tiling->n = n;
    tiling->k = k;
    tiling->innerSize = innerSize;
    tiling->perCoreN = perCoreN;
    tiling->needCoreNum = needCoreNum;

    context->SetBlockDim(needCoreNum);
    uint64_t tilingKey = GET_TPL_TILING_KEY(INPLACE_UPDATE_TPL_SCH_MODE_0);
    context->SetTilingKey(tilingKey);

    uint64_t ubSize;
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    OP_CHECK_IF((ubSize <= DCACHE_SIZE + STATIC_UB_ESTIMATE),
                OP_LOGE(context, "ubSize <= DCACHE_SIZE + STATIC_UB_ESTIMATE"), return ge::GRAPH_FAILED);
    context->SetLocalMemorySize(static_cast<uint32_t>(ubSize - DCACHE_SIZE - STATIC_UB_ESTIMATE));
    uint64_t sysWorkspaceSize = ascendcPlatform.GetLibApiWorkSpaceSize();
    size_t* ws = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, ws);
    ws[0] = static_cast<size_t>(sysWorkspaceSize);

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForInplaceUpdate([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(InplaceUpdate)
    .Tiling(InplaceUpdateTilingFunc)
    .TilingParse<InplaceUpdateCompileInfo>(TilingParseForInplaceUpdate);

} // namespace optiling
