/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file apply_ftrl_v2_tiling_arch35.cpp
 * \brief ApplyFtrlV2 Host 侧 Tiling 实现 (arch35 / Ascend950)
 *
 * TilingKey 编码：0 = FP32 直算, 1 = FP16/BF16 升精度
 * dtype 由 def 文件驱动（DTYPE_X 宏），tiling_key 仅编码计算路径
 */

#include "register/op_def_registry.h"
#include <graph/utils/type_utils.h>
#include "op_common/log/log.h"
#include "op_common/op_host/util/math_util.h"
#include "op_common/op_host/util/platform_util.h"
#include "../../op_kernel/arch35/apply_ftrl_v2_tiling_data.h"

namespace optiling {

using Ops::Base::CeilAlign;
using Ops::Base::CeilDiv;
using Ops::Base::FloorAlign;
using Ops::Base::FloorDiv;

constexpr uint32_t WS_SYS_SIZE = 0U;
constexpr size_t WORKSPACE_NUM = 1;
constexpr uint32_t ELEM_ALIGN_FACTOR = 512;             // 多核切分元素对齐因子
constexpr uint32_t BITS_PER_BYTE = 8;                   // 每字节的比特数
constexpr uint32_t BITS_PER_FP32 = 32;                  // FP32 元素位宽
constexpr uint32_t BITS_PER_HALF = 16;                  // FP16/BF16 元素位宽
constexpr uint32_t BYTES_PER_FP32 = 4;                  // FP32 元素字节数
constexpr uint32_t BYTES_PER_HALF = 2;                  // FP16/BF16 元素字节数
constexpr uint32_t UB_ALIGN_BITS = 256 * BITS_PER_BYTE; // 256B 对齐（bits）
constexpr size_t MAX_TENSOR_RANK = 8;                   // Tensor 最大支持维数（0-8 维，9D+ 拒绝）

// UB 容量估算参数（与 kernel Init 中 buffer 规划一一对应，详见 apply_ftrl_v2.h）
constexpr uint32_t FP32_BUF_COUNT = 8;         // 4 TQue 输入 + 4 TBuf 计算
constexpr uint32_t HALF_IN_BUF_COUNT = 4;      // FP16/BF16 路径输入 half buffer
constexpr uint32_t HALF_OUT_BUF_COUNT = 3;     // FP16/BF16 路径输出 half buffer
constexpr uint32_t POWER_TMP_BUF_COUNT = 1;    // tmpPowerBuf（FP32）
constexpr uint32_t CMP_MASK_BITS_PER_ELEM = 1; // bit-packed 比较掩码：每元素 1 bit

constexpr uint32_t UB_UTILIZATION_NUM = 90; // UB 利用率上限分子（90%）
constexpr uint32_t UB_UTILIZATION_DEN = 100;
constexpr uint64_t UB_SIZE_FALLBACK = 192 * 1024; // UB 大小兜底值（192KB）

static const gert::Shape g_vec_1_shape = {1};

static inline const gert::Shape EnsureNotScalar(const gert::Shape& in_shape)
{
    if (in_shape.GetDimNum() == 0) {
        return g_vec_1_shape;
    }
    return in_shape;
}

// 获取平台信息
static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t* ubSize, int64_t* coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    *coreNum = ascendcPlatform.GetCoreNumAiv();
    // 兜底：部分环境 GetCoreNumAiv 返回 0，使用 AIC 核数或默认值
    if (*coreNum == 0) {
        *coreNum = ascendcPlatform.GetCoreNumAic();
    }
    if (*coreNum == 0) {
        *coreNum = 1; // 最终兜底：单核执行
        OP_LOGW(context, "GetCoreNumAiv/Aic both 0, fallback to coreNum=1");
    }
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, *ubSize);
    if (*ubSize == 0) {
        *ubSize = UB_SIZE_FALLBACK;
        OP_LOGW(context, "ubSize is 0, fallback to 192KB");
    }
    return ge::GRAPH_SUCCESS;
}

// 获取 shape/dtype 信息
static ge::graphStatus GetShapeAttrsInfo(gert::TilingContext* context, int64_t* totalElements, ge::DataType* dataType)
{
    auto inputVar = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputVar);
    OP_CHECK_IF(inputVar->GetStorageShape().GetDimNum() > MAX_TENSOR_RANK,
                OP_LOGE(context, "ApplyFtrlV2: var rank=%zu exceeds max supported rank %zu",
                        inputVar->GetStorageShape().GetDimNum(), MAX_TENSOR_RANK),
                return ge::GRAPH_FAILED);
    auto varShape = EnsureNotScalar(inputVar->GetStorageShape());
    *totalElements = varShape.GetShapeSize();

    auto inputDesc = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
    *dataType = inputDesc->GetDataType();

    const std::set<ge::DataType> supportedDtypes = {ge::DT_FLOAT, ge::DT_FLOAT16, ge::DT_BF16};
    OP_CHECK_IF(supportedDtypes.count(*dataType) == 0, OP_LOGE(context, "Unsupported dtype"), return ge::GRAPH_FAILED);

    // 检查输入 dtype 一致性（var/accum/linear/grad/lr/l1/l2/l2_shrinkage/lr_power 必须同 dtype）
    for (size_t i = 1; i < 9; i++) {
        auto desc = context->GetInputDesc(i);
        OP_CHECK_NULL_WITH_CONTEXT(context, desc);
        auto dt = desc->GetDataType();
        OP_CHECK_IF(dt != *dataType,
                    OP_LOGE(context, "ApplyFtrlV2: dtype mismatch, var=%s, input%zu=%s",
                            ge::TypeUtils::DataTypeToSerialString(*dataType).c_str(), i,
                            ge::TypeUtils::DataTypeToSerialString(dt).c_str()),
                    return ge::GRAPH_FAILED);
    }

    // 检查 var/accum/linear/grad shape 一致性
    auto varOriginShape = inputVar->GetStorageShape();
    for (size_t i = 1; i < 4; i++) {
        auto inputShape = context->GetInputShape(i);
        OP_CHECK_NULL_WITH_CONTEXT(context, inputShape);
        OP_CHECK_IF(inputShape->GetStorageShape().GetDimNum() > MAX_TENSOR_RANK,
                    OP_LOGE(context, "ApplyFtrlV2: input%zu rank=%zu exceeds max supported rank %zu", i,
                            inputShape->GetStorageShape().GetDimNum(), MAX_TENSOR_RANK),
                    return ge::GRAPH_FAILED);
        auto& s = inputShape->GetStorageShape();
        OP_CHECK_IF(s.GetDimNum() != varOriginShape.GetDimNum() || s.GetShapeSize() != varOriginShape.GetShapeSize(),
                    OP_LOGE(context, "ApplyFtrlV2: shape mismatch, var and input%zu", i), return ge::GRAPH_FAILED);
    }

    // 检查 lr/l1/l2/l2_shrinkage/lr_power 为 scalar（0-d 或 shapeSize<=1）
    for (size_t i = 4; i < 9; i++) {
        auto inputShape = context->GetInputShape(i);
        OP_CHECK_NULL_WITH_CONTEXT(context, inputShape);
        auto& s = inputShape->GetStorageShape();
        OP_CHECK_IF(s.GetShapeSize() > 1,
                    OP_LOGE(context, "ApplyFtrlV2: input%zu must be scalar, but shapeSize=%ld", i,
                            static_cast<int64_t>(s.GetShapeSize())),
                    return ge::GRAPH_FAILED);
    }

    return ge::GRAPH_SUCCESS;
}

// Workspace 声明
static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    size_t* currentWorkspace = context->GetWorkspaceSizes(WORKSPACE_NUM);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = WS_SYS_SIZE;
    return ge::GRAPH_SUCCESS;
}

// UB 切分：计算 tileLength / ubFormer（先于多核切分，用于限制 blockFormer 上限）
static void CalcUbTiling(uint64_t ubSize, uint32_t minDtypeBits, ge::DataType dataType, ApplyFtrlV2TilingData* tiling,
                         gert::TilingContext* context)
{
    // Buffer 数量与 kernel Init 一一对应（详见 apply_ftrl_v2.h Buffer 规划）
    uint32_t halfInBufCount = (dataType == ge::DT_FLOAT) ? 0 : HALF_IN_BUF_COUNT;
    uint32_t halfOutBufCount = (dataType == ge::DT_FLOAT) ? 0 : HALF_OUT_BUF_COUNT;
    uint32_t bitsPerElem = FP32_BUF_COUNT * BITS_PER_FP32 + halfInBufCount * BITS_PER_HALF +
                           halfOutBufCount * BITS_PER_HALF + POWER_TMP_BUF_COUNT * BITS_PER_FP32 +
                           CMP_MASK_BITS_PER_ELEM;

    uint32_t maxElemNum = static_cast<uint32_t>((ubSize * BITS_PER_BYTE) / bitsPerElem);
    maxElemNum = maxElemNum * UB_UTILIZATION_NUM / UB_UTILIZATION_DEN;
    uint32_t alignFactor = (minDtypeBits == 0) ? 1 : (UB_ALIGN_BITS / minDtypeBits);
    if (alignFactor == 0)
        alignFactor = 1;
    tiling->tileLength = (maxElemNum / alignFactor) * alignFactor;
    if (tiling->tileLength == 0) {
        tiling->tileLength = alignFactor;
        OP_LOGW(context, "tileLength clamped to alignFactor=%u", alignFactor);
    }
    tiling->ubFormer = tiling->tileLength;
}

// 多核切分：计算 blockFormer / blockNum / blockDim（blockFormer 上限 = tileLength，确保单 UB 循环）
static void CalcBlockTiling(int64_t totalElements, uint32_t minDtypeBits, int64_t coreNum,
                            ApplyFtrlV2TilingData* tiling)
{
    constexpr uint64_t MIN_TILING_BITS = 32768;
    uint64_t totalBits = static_cast<uint64_t>(totalElements) * static_cast<uint64_t>(minDtypeBits);
    uint32_t calcCoreNum = static_cast<uint32_t>((totalBits + MIN_TILING_BITS - 1) / MIN_TILING_BITS);
    calcCoreNum = std::min(calcCoreNum, static_cast<uint32_t>(coreNum));
    if (calcCoreNum == 0)
        calcCoreNum = 1;

    tiling->blockFormer = CeilAlign(
        static_cast<int64_t>(CeilDiv(static_cast<int64_t>(totalElements), static_cast<int64_t>(calcCoreNum))),
        static_cast<int64_t>(ELEM_ALIGN_FACTOR));
    if (tiling->blockFormer > tiling->tileLength) {
        tiling->blockFormer = (tiling->tileLength / ELEM_ALIGN_FACTOR) * ELEM_ALIGN_FACTOR;
        if (tiling->blockFormer == 0)
            tiling->blockFormer = ELEM_ALIGN_FACTOR;
    }
    tiling->blockNum = static_cast<uint32_t>(
        CeilDiv(static_cast<int64_t>(totalElements), static_cast<int64_t>(tiling->blockFormer)));
    tiling->blockDim = tiling->blockNum;
}

// 循环次数计算：ubLoop / ubTail（former block & tail block）
static void CalcUbLoops(int64_t totalElements, ApplyFtrlV2TilingData* tiling)
{
    tiling->ubLoopOfFormerBlock = CeilDiv(static_cast<int64_t>(tiling->blockFormer),
                                          static_cast<int64_t>(tiling->ubFormer));
    tiling->ubTailOfFormerBlock = tiling->blockFormer - (tiling->ubLoopOfFormerBlock - 1) * tiling->ubFormer;

    uint32_t blockTail = static_cast<uint32_t>(totalElements) - (tiling->blockNum - 1) * tiling->blockFormer;
    tiling->ubLoopOfTailBlock = CeilDiv(static_cast<int64_t>(blockTail), static_cast<int64_t>(tiling->ubFormer));
    tiling->ubTailOfTailBlock = blockTail - (tiling->ubLoopOfTailBlock - 1) * tiling->ubFormer;
}

// Tiling 分发入口
static ge::graphStatus ApplyFtrlV2TilingFunc(gert::TilingContext* context)
{
    OP_LOGI(context->GetNodeName(), "Enter ApplyFtrlV2TilingFunc");
    // 1. 获取平台信息
    uint64_t ubSize;
    int64_t coreNum;
    OP_CHECK_IF(GetPlatformInfo(context, &ubSize, &coreNum) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetPlatformInfo error"), return ge::GRAPH_FAILED);

    // 2. 获取 shape/dtype
    int64_t totalElements;
    ge::DataType dataType;
    OP_CHECK_IF(GetShapeAttrsInfo(context, &totalElements, &dataType) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetShapeAttrsInfo error"), return ge::GRAPH_FAILED);

    // 3. Workspace
    OP_CHECK_IF(GetWorkspaceSize(context) != ge::GRAPH_SUCCESS, OP_LOGE(context, "GetWorkspaceSize error"),
                return ge::GRAPH_FAILED);

    // 4. 初始化 TilingData
    ApplyFtrlV2TilingData* tiling = context->GetTilingData<ApplyFtrlV2TilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(memset_s(tiling, sizeof(ApplyFtrlV2TilingData), 0, sizeof(ApplyFtrlV2TilingData)) != EOK,
                OP_LOGE(context, "memset tiling error"), return ge::GRAPH_FAILED);

    // 5. dtype 相关参数
    uint32_t dtypeSize = (dataType == ge::DT_FLOAT) ? BYTES_PER_FP32 : BYTES_PER_HALF;
    uint32_t minDtypeBits = dtypeSize * BITS_PER_BYTE;

    // 空 Tensor 快速返回
    if (totalElements == 0) {
        tiling->totalElements = 0;
        context->SetBlockDim(1);
        return ge::GRAPH_SUCCESS;
    }

    // 6. UB 切分
    CalcUbTiling(ubSize, minDtypeBits, dataType, tiling, context);

    // 7. 多核切分
    CalcBlockTiling(totalElements, minDtypeBits, coreNum, tiling);

    // 8. 循环次数计算
    CalcUbLoops(totalElements, tiling);

    // 9. 标量参数（lr/l1/l2/l2_shrinkage/lr_power 由 kernel 从 GM_ADDR 读取，
    //    tiling data 中保留字段但置 0，避免 tiling 阶段无法读 0-d tensor 数据）
    tiling->totalElements = static_cast<uint32_t>(totalElements);
    tiling->dtypeSize = static_cast<uint8_t>(dtypeSize);

    // 10. 设置 BlockDim 和 TilingKey
    context->SetBlockDim(tiling->blockDim);

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForApplyFtrlV2([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

struct ApplyFtrlV2CompileInfo {};

IMPL_OP_OPTILING(ApplyFtrlV2)
    .Tiling(ApplyFtrlV2TilingFunc)
    .TilingParse<ApplyFtrlV2CompileInfo>(TilingParseForApplyFtrlV2);

} // namespace optiling
