/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file max_pool_v3_grad_tiling.cpp
 * \brief Tiling implementation for max_pool_v3_grad operator
 *
 *   - 输入 shape 强制 4D (GetDimNum() == 4)
 *   - 动态 shape (-1) 拦截: infershape 放行后, tiling 阶段对 -1 维直接报错
 *   - data_format 属性实际影响 H/W/C 维索引:
 *       NCHW: h_dim=2, w_dim=3, c_dim=1
 *       NHWC: h_dim=1, w_dim=2, c_dim=3
 *   - ksize/strides 按 data_format 解析 H/W 维
 *   - totalOutputPos = N × C × Ho × Wo
 *   - totalInputElements = N × C × H × W
 *   - floor_div / ceil_div 对齐 Python // (向负无穷取整)，覆盖空 tensor 场景
 *   - Ho/Wo 钳位 max(Ho,0)/max(Wo,0)，对 VALID/SAME/CALCULATED 三种模式统一生效
 *   - SetScheduleMode(1) 无条件调用 (非重叠/重叠路径均需 SyncAll)
 *   - TilingKey 仅编码 overlapMode，dtype 由 DTYPE_ 宏自动实例化
 *   - GetWorkspaceSizes(1) 无条件调用 (含系统 workspace)
 *   - 属性校验: ksize/strides/pads 长度==4, ksize/strides N/C维==1, ksize[H,W]∈[1,255],
 *               strides[H,W]∈[1,63], pads≥0(CALCULATED), orig_output N/C维==orig_input,
 *               grad shape==orig_output
 *   - workspace: 重叠模式需要 int32 argmax 索引区 (totalOutputPos * sizeof(int32_t))
 */

#include <cstdint>

#include "log/log.h"
#include "platform/platform_ascendc.h"
#include "util/math_util.h"
#include "util/platform_util.h"
#include "op_host/tiling_util.h"
#include "op_host/tiling_templates_registry.h"
#include "../../op_kernel/arch35/max_pool_v3_grad_tiling_data.h"
#include "../../op_kernel/arch35/max_pool_v3_grad_tiling_key.h"

namespace optiling {

using namespace Ops::NN::OpTiling;

constexpr uint32_t DCACHE_SIZE = 128 * 1024;    // DCache 预留
constexpr uint32_t STATIC_UB_ESTIMATE = 0;      // 纯 GM 计算模式，无静态 UB 数组
constexpr int64_t PER_CORE_MIN_ELEMENTS = 1024; // 下限保护，对齐到 32
constexpr int32_t ALIGN_WARP = 32;              // warp 对齐粒度
constexpr int64_t UNKNOWN_DIM = -1LL;           // 动态 shape 的 unknown dim 值
constexpr int32_t ATTR_INDEX_KSIZE = 0;
constexpr int32_t ATTR_INDEX_STRIDES = 1;
constexpr int32_t ATTR_INDEX_PADDING_MODE = 2;
constexpr int32_t ATTR_INDEX_PADS = 3;
constexpr int32_t ATTR_INDEX_DATA_FORMAT = 4;
constexpr int32_t ATTR_INDEX_GLOBAL_POOLING = 5;
constexpr int32_t ATTR_INDEX_CEIL_MODE = 6;
constexpr int32_t ATTR_LIST_SIZE = 4;

struct MaxPoolV3GradCompileInfo {};

static int64_t FloorDiv(int64_t a, int64_t b)
{
    if (b == 0) {
        return 0;
    }
    int64_t q = a / b;
    int64_t r = a % b;
    return (r != 0 && r < 0) ? (q - 1) : q;
}

static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t& ubSize, int64_t& coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0,
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "coreNum",
                                                      std::to_string(coreNum).c_str(), "coreNum must not be 0"),
                return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0,
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "ubSize", std::to_string(ubSize).c_str(),
                                                      "ubSize must not be 0"),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// ValidateAttrs: 属性校验 (与 infershape 形成双重校验)。ksize/strides 按 data_format 解析 H/W 维。
static ge::graphStatus ValidateAttrs(gert::TilingContext* context, const char* paddingMode, const char* dataFormat,
                                     bool globalPooling, bool ceilMode, const int64_t* ksize, const int64_t* strides,
                                     const int64_t* pads)
{
    std::string paddingModeStr(paddingMode);
    std::string dataFormatStr(dataFormat);
    OP_CHECK_IF(dataFormatStr != "NCHW" && dataFormatStr != "NHWC",
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "data_format", dataFormatStr.c_str(),
                                                      "must be NCHW or NHWC"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(paddingModeStr != "SAME" && paddingModeStr != "VALID" && paddingModeStr != "CALCULATED",
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "padding_mode", paddingModeStr.c_str(),
                                                      "must be SAME, VALID or CALCULATED"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(
        globalPooling != false,
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "global_pooling", "true", "must be false"),
        return ge::GRAPH_FAILED);
    OP_CHECK_IF((paddingModeStr == "SAME" || paddingModeStr == "VALID") && ceilMode != false,
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "ceil_mode", "true",
                                                      "must be false under SAME/VALID"),
                return ge::GRAPH_FAILED);
    // N/C 维 ksize/strides 必须为 1 (与 canndev check_param 对齐)
    // NCHW: ksize[0]=N, ksize[1]=C; NHWC: ksize[0]=N, ksize[3]=C
    int32_t cIdx = (dataFormatStr == "NCHW") ? 1 : 3;
    OP_CHECK_IF(ksize[0] != 1 || ksize[cIdx] != 1,
                OP_LOGE_FOR_INVALID_VALUES_WITH_REASON(
                    context->GetNodeName(), "ksize[N], ksize[C]",
                    (std::to_string(ksize[0]) + ", " + std::to_string(ksize[cIdx])).c_str(), "ksize[N,C] must be 1"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(
        strides[0] != 1 || strides[cIdx] != 1,
        OP_LOGE_FOR_INVALID_VALUES_WITH_REASON(
            context->GetNodeName(), "strides[N], strides[C]",
            (std::to_string(strides[0]) + ", " + std::to_string(strides[cIdx])).c_str(), "strides[N,C] must be 1"),
        return ge::GRAPH_FAILED);
    // NCHW: ksize[2]/ksize[3], strides[2]/strides[3] 为 H/W 维
    // NHWC: ksize[1]/ksize[2], strides[1]/strides[2] 为 H/W 维
    int32_t hIdx = (dataFormatStr == "NCHW") ? 2 : 1;
    int32_t wIdx = (dataFormatStr == "NCHW") ? 3 : 2;
    OP_CHECK_IF(ksize[hIdx] < 1 || ksize[hIdx] > 255 || ksize[wIdx] < 1 || ksize[wIdx] > 255,
                OP_LOGE_FOR_INVALID_VALUES_WITH_REASON(
                    context->GetNodeName(), "ksize[H], ksize[W]",
                    (std::to_string(ksize[hIdx]) + ", " + std::to_string(ksize[wIdx])).c_str(),
                    "ksize[H,W] must be in [1,255]"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(strides[hIdx] < 1 || strides[hIdx] > 63 || strides[wIdx] < 1 || strides[wIdx] > 63,
                OP_LOGE_FOR_INVALID_VALUES_WITH_REASON(
                    context->GetNodeName(), "strides[H], strides[W]",
                    (std::to_string(strides[hIdx]) + ", " + std::to_string(strides[wIdx])).c_str(),
                    "strides[H,W] must be in [1,63]"),
                return ge::GRAPH_FAILED);
    if (paddingModeStr == "CALCULATED") {
        OP_CHECK_IF(
            pads[0] < 0 || pads[1] < 0 || pads[2] < 0 || pads[3] < 0,
            OP_LOGE_FOR_INVALID_VALUES_WITH_REASON(context->GetNodeName(), "pads",
                                                   (std::to_string(pads[0]) + ", " + std::to_string(pads[1]) + ", " +
                                                    std::to_string(pads[2]) + ", " + std::to_string(pads[3]))
                                                       .c_str(),
                                                   "pads must be >= 0 under CALCULATED"),
            return ge::GRAPH_FAILED);
    }
    return ge::GRAPH_SUCCESS;
}

// IsMulOverflow: 非负乘法溢出检查 (a, b 均 >= 0)。
// 维度值和元素计数恒非负，乘法溢出仅在此场景发生。
static bool IsMulOverflow(int64_t a, int64_t b) { return a > 0 && b > 0 && a > INT64_MAX / b; }

// ComputePoolParams: 计算 padding 和输出尺寸 (与 Golden _compute_pool_params 严格对齐)。
// Ho/Wo 钳位 max(Ho,0)/max(Wo,0)。
static void ComputePoolParams(int64_t H, int64_t W, int64_t kh, int64_t kw, int64_t sh, int64_t sw,
                              const char* paddingMode, const int64_t* pads, bool ceilMode, int64_t& padTop,
                              int64_t& padLeft, int64_t& Ho, int64_t& Wo)
{
    std::string mode(paddingMode);
    if (mode == "VALID") {
        Ho = Ops::Base::CeilDiv(H - kh + 1, sh);
        Wo = Ops::Base::CeilDiv(W - kw + 1, sw);
        padTop = 0;
        padLeft = 0;
    } else if (mode == "SAME") {
        Ho = Ops::Base::CeilDiv(H, sh);
        Wo = Ops::Base::CeilDiv(W, sw);
        int64_t padH = std::max((Ho - 1) * sh + kh - H, static_cast<int64_t>(0));
        int64_t padW = std::max((Wo - 1) * sw + kw - W, static_cast<int64_t>(0));
        padTop = padH / 2;
        padLeft = padW / 2;
    } else {
        // CALCULATED
        padTop = pads[0];
        padLeft = pads[2];
        int64_t padBottom = pads[1];
        int64_t padRight = pads[3];
        if (ceilMode) {
            Ho = Ops::Base::CeilDiv(H - kh + padTop + padBottom, sh) + 1;
            Wo = Ops::Base::CeilDiv(W - kw + padLeft + padRight, sw) + 1;
        } else {
            Ho = FloorDiv(H - kh + padTop + padBottom, sh) + 1;
            Wo = FloorDiv(W - kw + padLeft + padRight, sw) + 1;
        }
    }
    // 钳位为 0 后 totalOutputPos=0，kernel 内循环不执行，返回全 0 out_grad。
    Ho = std::max(Ho, static_cast<int64_t>(0));
    Wo = std::max(Wo, static_cast<int64_t>(0));
}

static ge::graphStatus MaxPoolV3GradTilingFunc(gert::TilingContext* context)
{
    // 1. 获取平台信息
    uint64_t ubSize = 0;
    int64_t coreNum = 0;
    OP_CHECK_IF(GetPlatformInfo(context, ubSize, coreNum) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetPlatformInfo error"), return ge::GRAPH_FAILED);

    // 2. 获取输入 shape (4D: NCHW 或 NHWC)
    auto origInputShapePtr = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, origInputShapePtr);
    auto origInputShape = origInputShapePtr->GetStorageShape();
    OP_CHECK_IF(origInputShape.GetDimNum() != 4,
                OP_LOGE_FOR_INVALID_SHAPEDIM_WITH_REASON(context->GetNodeName(), "orig_input",
                                                         std::to_string(origInputShape.GetDimNum()).c_str(),
                                                         "must be 4D (NCHW/NHWC)"),
                return ge::GRAPH_FAILED);
    // 动态 shape (-1) 拦截: tiling 阶段需要具体 H/W/C 值，不支持动态 shape
    for (size_t i = 0; i < origInputShape.GetDimNum(); ++i) {
        OP_CHECK_IF(origInputShape.GetDim(i) == UNKNOWN_DIM,
                    OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(context->GetNodeName(), "orig_input",
                                                           Ops::Base::ToString(origInputShape).c_str(),
                                                           "dynamic shape (-1) is not supported in tiling"),
                    return ge::GRAPH_FAILED);
    }
    int64_t N = origInputShape.GetDim(0);

    // 3. 获取属性
    auto attrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, attrs);

    // ksize: 先 null 检查 + 长度校验，再取 GetData()
    auto ksizePtr = attrs->GetListInt(ATTR_INDEX_KSIZE);
    OP_CHECK_NULL_WITH_CONTEXT(context, ksizePtr);
    OP_CHECK_IF(
        ksizePtr->GetSize() != ATTR_LIST_SIZE,
        OP_LOGE_FOR_INVALID_LISTSIZE(context->GetNodeName(), "ksize", std::to_string(ksizePtr->GetSize()).c_str(), "4"),
        return ge::GRAPH_FAILED);
    const int64_t* ksize = ksizePtr->GetData();

    // strides: 先 null 检查 + 长度校验，再取 GetData()
    auto stridesPtr = attrs->GetListInt(ATTR_INDEX_STRIDES);
    OP_CHECK_NULL_WITH_CONTEXT(context, stridesPtr);
    OP_CHECK_IF(stridesPtr->GetSize() != ATTR_LIST_SIZE,
                OP_LOGE_FOR_INVALID_LISTSIZE(context->GetNodeName(), "strides",
                                             std::to_string(stridesPtr->GetSize()).c_str(), "4"),
                return ge::GRAPH_FAILED);
    const int64_t* strides = stridesPtr->GetData();

    auto paddingMode = attrs->GetAttrPointer<char>(ATTR_INDEX_PADDING_MODE);
    OP_CHECK_NULL_WITH_CONTEXT(context, paddingMode);

    // pads: 先 null 检查 + 长度校验，再取 GetData()
    auto padsPtr = attrs->GetListInt(ATTR_INDEX_PADS);
    OP_CHECK_NULL_WITH_CONTEXT(context, padsPtr);
    OP_CHECK_IF(
        padsPtr->GetSize() != ATTR_LIST_SIZE,
        OP_LOGE_FOR_INVALID_LISTSIZE(context->GetNodeName(), "pads", std::to_string(padsPtr->GetSize()).c_str(), "4"),
        return ge::GRAPH_FAILED);
    const int64_t* pads = padsPtr->GetData();

    auto dataFormat = attrs->GetAttrPointer<char>(ATTR_INDEX_DATA_FORMAT);
    OP_CHECK_NULL_WITH_CONTEXT(context, dataFormat);
    auto globalPooling = attrs->GetAttrPointer<bool>(ATTR_INDEX_GLOBAL_POOLING);
    OP_CHECK_NULL_WITH_CONTEXT(context, globalPooling);
    auto ceilMode = attrs->GetAttrPointer<bool>(ATTR_INDEX_CEIL_MODE);
    OP_CHECK_NULL_WITH_CONTEXT(context, ceilMode);

    // 4. 属性校验
    OP_CHECK_IF(ValidateAttrs(context, paddingMode, dataFormat, *globalPooling, *ceilMode, ksize, strides, pads) !=
                    ge::GRAPH_SUCCESS,
                OP_LOGE(context, "ValidateAttrs failed"), return ge::GRAPH_FAILED);

    // 5. 根据 data_format 提取 N/C/H/W 维及 ksize/strides 的 H/W 维
    std::string dataFormatStr(dataFormat);
    int32_t inputFormat = 0;
    int64_t C = 0;
    int64_t H = 0;
    int64_t W = 0;
    int64_t kh = 0;
    int64_t kw = 0;
    int64_t sh = 0;
    int64_t sw = 0;
    if (dataFormatStr == "NCHW") {
        inputFormat = 0;
        C = origInputShape.GetDim(1);
        H = origInputShape.GetDim(2);
        W = origInputShape.GetDim(3);
        kh = ksize[2];
        kw = ksize[3];
        sh = strides[2];
        sw = strides[3];
    } else {
        // NHWC
        inputFormat = 1;
        H = origInputShape.GetDim(1);
        W = origInputShape.GetDim(2);
        C = origInputShape.GetDim(3);
        kh = ksize[1];
        kw = ksize[2];
        sh = strides[1];
        sw = strides[2];
    }

    // 6. 计算 padding 和输出尺寸
    int64_t padTop = 0;
    int64_t padLeft = 0;
    int64_t Ho = 0;
    int64_t Wo = 0;
    ComputePoolParams(H, W, kh, kw, sh, sw, paddingMode, pads, *ceilMode, padTop, padLeft, Ho, Wo);

    // 7. 校验 grad.shape == orig_output.shape (4D 逐维校验)
    auto gradShapePtr = context->GetInputShape(2);
    OP_CHECK_NULL_WITH_CONTEXT(context, gradShapePtr);
    auto gradShape = gradShapePtr->GetStorageShape();
    auto origOutputShapePtr = context->GetInputShape(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, origOutputShapePtr);
    auto origOutputShape = origOutputShapePtr->GetStorageShape();
    OP_CHECK_IF(gradShape.GetDimNum() != 4,
                OP_LOGE_FOR_INVALID_SHAPEDIM_WITH_REASON(context->GetNodeName(), "grad",
                                                         std::to_string(gradShape.GetDimNum()).c_str(), "must be 4D"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(
        origOutputShape.GetDimNum() != 4,
        OP_LOGE_FOR_INVALID_SHAPEDIM_WITH_REASON(context->GetNodeName(), "orig_output",
                                                 std::to_string(origOutputShape.GetDimNum()).c_str(), "must be 4D"),
        return ge::GRAPH_FAILED);
    // 动态 shape (-1) 拦截: tiling 阶段需要具体 shape 值，不支持动态 shape
    for (size_t i = 0; i < gradShape.GetDimNum(); ++i) {
        OP_CHECK_IF(gradShape.GetDim(i) == UNKNOWN_DIM,
                    OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(context->GetNodeName(), "grad",
                                                           Ops::Base::ToString(gradShape).c_str(),
                                                           "dynamic shape (-1) is not supported in tiling"),
                    return ge::GRAPH_FAILED);
    }
    for (size_t i = 0; i < origOutputShape.GetDimNum(); ++i) {
        OP_CHECK_IF(origOutputShape.GetDim(i) == UNKNOWN_DIM,
                    OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(context->GetNodeName(), "orig_output",
                                                           Ops::Base::ToString(origOutputShape).c_str(),
                                                           "dynamic shape (-1) is not supported in tiling"),
                    return ge::GRAPH_FAILED);
    }
    for (size_t i = 0; i < 4; i++) {
        OP_CHECK_IF(gradShape.GetDim(i) != origOutputShape.GetDim(i),
                    OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(
                        context->GetNodeName(), "grad, orig_output",
                        (Ops::Base::ToString(gradShape) + ", " + Ops::Base::ToString(origOutputShape)).c_str(),
                        "grad shape must be equal to orig_output shape"),
                    return ge::GRAPH_FAILED);
    }

    // 8. 校验 orig_output 的 N/C 维与 orig_input 一致 (与 canndev check_param 对齐)
    //    N/C 维在池化过程中不变，orig_output 和 orig_input 必须相同
    int32_t cIdxOut = (inputFormat == 0) ? 1 : 3;
    OP_CHECK_IF(
        origOutputShape.GetDim(0) != origInputShape.GetDim(0),
        OP_LOGE_FOR_INVALID_VALUES_WITH_REASON(
            context->GetNodeName(), "orig_output N, orig_input N",
            (std::to_string(origOutputShape.GetDim(0)) + ", " + std::to_string(origInputShape.GetDim(0))).c_str(),
            "orig_output N must be equal to orig_input N"),
        return ge::GRAPH_FAILED);
    OP_CHECK_IF(origOutputShape.GetDim(cIdxOut) != origInputShape.GetDim(cIdxOut),
                OP_LOGE_FOR_INVALID_VALUES_WITH_REASON(context->GetNodeName(), "orig_output C, orig_input C",
                                                       (std::to_string(origOutputShape.GetDim(cIdxOut)) + ", " +
                                                        std::to_string(origInputShape.GetDim(cIdxOut)))
                                                           .c_str(),
                                                       "orig_output C must be equal to orig_input C"),
                return ge::GRAPH_FAILED);
    bool overlap = (sh < kh) || (sw < kw);
    int32_t overlapMode = overlap ? 1 : 0;

    // 9. 核数切分: 物理核均分 -> 反推实际核数
    int64_t hoWo = Ho * Wo;
    int64_t hw = H * W;
    OP_CHECK_IF(IsMulOverflow(Ho, Wo),
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "Ho*Wo", std::to_string(hoWo).c_str(),
                                                      "multiplication overflow"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(IsMulOverflow(H, W),
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "H*W", std::to_string(hw).c_str(),
                                                      "multiplication overflow"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(IsMulOverflow(N, C),
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "N*C", std::to_string(N * C).c_str(),
                                                      "multiplication overflow"),
                return ge::GRAPH_FAILED);
    int64_t nc = N * C;
    OP_CHECK_IF(IsMulOverflow(nc, hoWo),
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "N*C*Ho*Wo",
                                                      std::to_string(nc * hoWo).c_str(), "multiplication overflow"),
                return ge::GRAPH_FAILED);
    int64_t totalOutputPos = nc * hoWo;
    OP_CHECK_IF(IsMulOverflow(nc, hw),
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "N*C*H*W",
                                                      std::to_string(nc * hw).c_str(), "multiplication overflow"),
                return ge::GRAPH_FAILED);
    int64_t totalInputElements = nc * hw;

    int64_t perCoreElements = (totalOutputPos > 0) ? Ops::Base::CeilDiv(totalOutputPos, coreNum) : 0;
    if (perCoreElements > 0 && perCoreElements < PER_CORE_MIN_ELEMENTS) {
        perCoreElements = std::min(PER_CORE_MIN_ELEMENTS, totalOutputPos);
    }
    if (perCoreElements > 0) {
        perCoreElements = Ops::Base::CeilAlign(perCoreElements, static_cast<int64_t>(ALIGN_WARP));
    }
    int32_t needCoreNum = (totalOutputPos > 0) ?
                              static_cast<int32_t>(Ops::Base::CeilDiv(totalOutputPos, perCoreElements)) :
                              1;

    // 10. Workspace 分配: 重叠模式需要 int32 argmax 索引区 (ForwardPass 存 argmax → GatherPass 累加)。
    //     非重叠路径不需要 workspace。
    int64_t userWorkspaceSize = 0;
    if (overlapMode == 1) {
        // argmax 存空间偏移 hi*W+wi（同一 n,c slice 内唯一），最大值 = H*W-1。
        userWorkspaceSize = totalOutputPos * static_cast<int64_t>(sizeof(int32_t));
    }
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(context->GetPlatformInfo());
    uint64_t sysWorkspaceSize = ascendcPlatform.GetLibApiWorkSpaceSize();
    size_t* ws = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, ws);
    ws[0] = static_cast<size_t>(userWorkspaceSize + static_cast<int64_t>(sysWorkspaceSize));

    // 11. 填充 TilingData (HoWo/Wo/C/HW/W/kh/kw/sh/sw/padTop/padLeft 为 int64_t，无需 static_cast)
    MaxPoolV3GradTilingData* tiling = context->GetTilingData<MaxPoolV3GradTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(memset_s(tiling, sizeof(MaxPoolV3GradTilingData), 0, sizeof(MaxPoolV3GradTilingData)) != EOK,
                OP_LOGE(context, "memset_s tiling data error"), return ge::GRAPH_FAILED);
    tiling->totalOutputPos = totalOutputPos;
    tiling->totalInputElements = totalInputElements;
    tiling->needCoreNum = needCoreNum;
    tiling->HoWo = hoWo;
    tiling->Wo = Wo;
    tiling->C = C;
    tiling->HW = hw;
    tiling->W = W;
    tiling->inputFormat = inputFormat;
    tiling->kh = kh;
    tiling->kw = kw;
    tiling->sh = sh;
    tiling->sw = sw;
    tiling->padTop = padTop;
    tiling->padLeft = padLeft;
    tiling->overlapMode = overlapMode;

    // 12. 设置 BlockDim / TilingKey / ScheduleMode / LocalMemory
    context->SetBlockDim(needCoreNum);
    // SetScheduleMode(1): 两条路径的 Process 均使用 SyncAll()，必须启用多核同步。
    context->SetScheduleMode(1);

    //   schMode = 0 (NON_OVERLAP_NCHW), 1 (NON_OVERLAP_NHWC)
    //   schMode = 2 (OVERLAP_NCHW),     3 (OVERLAP_NHWC)
    uint64_t tilingKey = 0;
    if (overlapMode == 0) {
        tilingKey = (inputFormat == 0) ? GET_TPL_TILING_KEY(MAX_POOL_V3_GRAD_TPL_MODE_NON_OVERLAP_NCHW) :
                                         GET_TPL_TILING_KEY(MAX_POOL_V3_GRAD_TPL_MODE_NON_OVERLAP_NHWC);
    } else {
        tilingKey = (inputFormat == 0) ? GET_TPL_TILING_KEY(MAX_POOL_V3_GRAD_TPL_MODE_OVERLAP_NCHW) :
                                         GET_TPL_TILING_KEY(MAX_POOL_V3_GRAD_TPL_MODE_OVERLAP_NHWC);
    }
    context->SetTilingKey(tilingKey);

    OP_CHECK_IF(ubSize <= DCACHE_SIZE + STATIC_UB_ESTIMATE,
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "ubSize", std::to_string(ubSize).c_str(),
                                                      "ubSize must be greater than DCACHE_SIZE + STATIC_UB"),
                return ge::GRAPH_FAILED);
    auto res = context->SetLocalMemorySize(static_cast<uint32_t>(ubSize - DCACHE_SIZE - STATIC_UB_ESTIMATE));
    OP_CHECK_IF(res != ge::GRAPH_SUCCESS, OP_LOGE(context, "SetLocalMemorySize failed, ubSize=%lu", ubSize),
                return ge::GRAPH_FAILED);

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForMaxPoolV3Grad([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(MaxPoolV3Grad)
    .Tiling(MaxPoolV3GradTilingFunc)
    .TilingParse<MaxPoolV3GradCompileInfo>(TilingParseForMaxPoolV3Grad);
} // namespace optiling
