/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file binary_cross_entropy_tiling_key.h
 * \brief binary_cross_entropy tiling key
 */

#ifndef ASCENDC_BINARY_CORSS_ENTROPY_TILING_KEY_H_
#define ASCENDC_BINARY_CORSS_ENTROPY_TILING_KEY_H_

#define BCE_TPL_FP16 10
#define BCE_TPL_FP32 20
#define BCE_TPL_BF16 30
#define BCE_NONE 0
#define BCE_SUM 1
#define BCE_HAS_WEIGHT 1
#define BCE_MEAN 2
#define REDUCTION_BIT_WIDTH 2
#define WEIGHT_BIT_WIDTH 1

#include "atvoss/reduce/reduce_tiling_key_decl.h"

ASCENDC_TPL_ARGS_DECL(BinaryCrossEntropy, REDUCE_TPL_KEY_DECL(),
    ASCENDC_TPL_UINT_DECL(Reduction, REDUCTION_BIT_WIDTH, ASCENDC_TPL_UI_LIST, BCE_NONE, BCE_SUM, BCE_MEAN),
    ASCENDC_TPL_UINT_DECL(HasWeight, WEIGHT_BIT_WIDTH, ASCENDC_TPL_UI_LIST, 0, BCE_HAS_WEIGHT),
    ASCENDC_TPL_UINT_DECL(DType, BIT_WIDTH, ASCENDC_TPL_UI_LIST, BCE_TPL_FP16, BCE_TPL_FP32, BCE_TPL_BF16)
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_EMPTY(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, BCE_NONE),
        ASCENDC_TPL_UINT_SEL(HasWeight, ASCENDC_TPL_UI_LIST, 0, BCE_HAS_WEIGHT),
        ASCENDC_TPL_UINT_SEL(DType, ASCENDC_TPL_UI_LIST, BCE_TPL_FP16)
    ),
    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_EMPTY(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, BCE_NONE),
        ASCENDC_TPL_UINT_SEL(HasWeight, ASCENDC_TPL_UI_LIST, 0, BCE_HAS_WEIGHT),
        ASCENDC_TPL_UINT_SEL(DType, ASCENDC_TPL_UI_LIST, BCE_TPL_BF16)
    ),
    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_EMPTY(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, BCE_NONE),
        ASCENDC_TPL_UINT_SEL(HasWeight, ASCENDC_TPL_UI_LIST, 0, BCE_HAS_WEIGHT),
        ASCENDC_TPL_UINT_SEL(DType, ASCENDC_TPL_UI_LIST, BCE_TPL_FP32)
    ),
    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_EMPTY(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, BCE_SUM, BCE_MEAN),
        ASCENDC_TPL_UINT_SEL(HasWeight, ASCENDC_TPL_UI_LIST, 0, BCE_HAS_WEIGHT),
        ASCENDC_TPL_UINT_SEL(DType, ASCENDC_TPL_UI_LIST, BCE_TPL_FP32)
    ),
    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_AR_NORMAL(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, BCE_SUM, BCE_MEAN),
        ASCENDC_TPL_UINT_SEL(HasWeight, ASCENDC_TPL_UI_LIST, 0, BCE_HAS_WEIGHT),
        ASCENDC_TPL_UINT_SEL(DType, ASCENDC_TPL_UI_LIST, BCE_TPL_FP32)
    ),
    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_AR_GROUP(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, BCE_SUM, BCE_MEAN),
        ASCENDC_TPL_UINT_SEL(HasWeight, ASCENDC_TPL_UI_LIST, 0, BCE_HAS_WEIGHT),
        ASCENDC_TPL_UINT_SEL(DType, ASCENDC_TPL_UI_LIST, BCE_TPL_FP32)
    ),
    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_A(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, BCE_SUM, BCE_MEAN),
        ASCENDC_TPL_UINT_SEL(HasWeight, ASCENDC_TPL_UI_LIST, 0, BCE_HAS_WEIGHT),
        ASCENDC_TPL_UINT_SEL(DType, ASCENDC_TPL_UI_LIST, BCE_TPL_FP32)
    ),
);

#endif