/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file test_inplace_apply_proximal_adagrad_tiling_arch35.cpp
 * \brief InplaceApplyProximalAdagrad Tiling (arch35) 独立逻辑测试
 *
 * 测试策略：从 inplace_apply_proximal_adagrad_tiling_arch35.cpp 复制 static 函数逻辑，
 * 不依赖 CANN faker 框架，使用独立编译验证 tiling 计算正确性。
 *
 * 测试覆盖：
 *   - ComputeMultiCoreSplit（blockFactor 多核均分 + ubBlockSize 对齐）
 *   - ComputeUbSplit（ubFactor = min(TILE_ELEM_NUM_TARGET, ubCapacityElem)）
 *   - 空 tensor 路径（totalElements=0 → SetBlockDim(1)）
 *   - EnsureNotScalar（标量→{1}）
 */

#include <gtest/gtest.h>
#include <cmath>
#include <cstdint>
#include <vector>
#include <string>
#include <algorithm>

// ===================== 常量定义（从源文件复制） =====================

enum LocalDataType {
    DT_FLOAT = 0,
    DT_FLOAT16 = 1,
    DT_BF16 = 27,
};

constexpr int64_t TILE_ELEM_NUM_TARGET = 2048;
constexpr int64_t UB_BUFFER_COUNT_FP32 = 14;
constexpr int64_t UB_BUFFER_COUNT_HALF = 12;
constexpr int64_t SIZE_FP32 = 4;
constexpr int64_t DEFAULT_UB_BLOCK_SIZE = 512;
constexpr int64_t DEFAULT_CORE_NUM = 28;
constexpr uint64_t DEFAULT_UB_SIZE = 256 * 1024;

// ===================== 辅助函数（从源文件复制） =====================

static int64_t CeilDiv(int64_t a, int64_t b) { return (a + b - 1) / b; }
static int64_t CeilAlign(int64_t a, int64_t align) { return CeilDiv(a, align) * align; }
static int64_t FloorDiv(int64_t a, int64_t b) { return a / b; }
static int64_t FloorAlign(int64_t a, int64_t align) { return (a / align) * align; }

using Shape = std::vector<int64_t>;
static const Shape g_vec_1_shape = {1};

static inline const Shape EnsureNotScalar(const Shape& in_shape)
{
    if (in_shape.empty()) {
        return g_vec_1_shape;
    }
    return in_shape;
}

// ===================== ComputeMultiCoreSplit（从源文件复制） =====================

struct MultiCoreResult {
    int64_t blockFactor;
    int64_t usedCoreNum;
};

static MultiCoreResult ComputeMultiCoreSplit(int64_t totalElements, int64_t coreNum, int64_t ubBlockSize)
{
    MultiCoreResult r;
    r.blockFactor = CeilAlign(CeilDiv(totalElements, coreNum), ubBlockSize);
    r.usedCoreNum = CeilDiv(totalElements, r.blockFactor);
    return r;
}

// ===================== ComputeUbSplit（从源文件复制） =====================

static int64_t ComputeUbSplit(uint64_t ubSize, int dataType, int64_t blockFactor, int64_t ubBlockSize)
{
    int64_t ubBufCount = (dataType == DT_FLOAT) ? UB_BUFFER_COUNT_FP32 : UB_BUFFER_COUNT_HALF;
    int64_t perElemBytes = SIZE_FP32;

    int64_t ubCapacityElem = FloorAlign(FloorDiv(static_cast<int64_t>(ubSize) / perElemBytes, ubBufCount), ubBlockSize);

    int64_t ubFactor = (TILE_ELEM_NUM_TARGET < ubCapacityElem) ? TILE_ELEM_NUM_TARGET : ubCapacityElem;

    if (ubFactor > blockFactor) {
        ubFactor = FloorAlign(blockFactor, ubBlockSize);
        if (ubFactor <= 0) {
            ubFactor = ubBlockSize;
        }
    }
    return ubFactor;
}

// ===================== 测试用例 =====================

TEST(InplaceApplyProximalAdagradTiling, empty_tensor)
{
    EXPECT_EQ(ComputeMultiCoreSplit(0, DEFAULT_CORE_NUM, DEFAULT_UB_BLOCK_SIZE).blockFactor, 0);
    EXPECT_EQ(ComputeMultiCoreSplit(0, DEFAULT_CORE_NUM, DEFAULT_UB_BLOCK_SIZE).usedCoreNum, 0);
}

TEST(InplaceApplyProximalAdagradTiling, multicore_fp32_basic)
{
    auto r = ComputeMultiCoreSplit(1024, DEFAULT_CORE_NUM, DEFAULT_UB_BLOCK_SIZE);
    EXPECT_GT(r.blockFactor, 0);
    EXPECT_GT(r.usedCoreNum, 0);
    EXPECT_LE(r.usedCoreNum, DEFAULT_CORE_NUM);
    EXPECT_EQ(r.blockFactor % DEFAULT_UB_BLOCK_SIZE, 0);
}

TEST(InplaceApplyProximalAdagradTiling, multicore_large)
{
    auto r = ComputeMultiCoreSplit(1024 * 2048, DEFAULT_CORE_NUM, DEFAULT_UB_BLOCK_SIZE);
    EXPECT_GT(r.blockFactor, 0);
    EXPECT_GT(r.usedCoreNum, 0);
    EXPECT_EQ(r.blockFactor % DEFAULT_UB_BLOCK_SIZE, 0);
}

TEST(InplaceApplyProximalAdagradTiling, multicore_single_element)
{
    auto r = ComputeMultiCoreSplit(1, DEFAULT_CORE_NUM, DEFAULT_UB_BLOCK_SIZE);
    EXPECT_EQ(r.blockFactor, DEFAULT_UB_BLOCK_SIZE);
    EXPECT_EQ(r.usedCoreNum, 1);
}

TEST(InplaceApplyProximalAdagradTiling, ubsplit_fp32)
{
    auto mc = ComputeMultiCoreSplit(100000, 1, DEFAULT_UB_BLOCK_SIZE);
    int64_t ubFactor = ComputeUbSplit(DEFAULT_UB_SIZE, DT_FLOAT, mc.blockFactor, DEFAULT_UB_BLOCK_SIZE);
    EXPECT_GT(ubFactor, 0);
    EXPECT_LE(ubFactor, TILE_ELEM_NUM_TARGET);
    EXPECT_EQ(ubFactor % DEFAULT_UB_BLOCK_SIZE, 0);
}

TEST(InplaceApplyProximalAdagradTiling, ubsplit_fp16)
{
    auto mc = ComputeMultiCoreSplit(100000, 1, DEFAULT_UB_BLOCK_SIZE);
    int64_t ubFactor = ComputeUbSplit(DEFAULT_UB_SIZE, DT_FLOAT16, mc.blockFactor, DEFAULT_UB_BLOCK_SIZE);
    EXPECT_GT(ubFactor, 0);
    EXPECT_LE(ubFactor, TILE_ELEM_NUM_TARGET);
}

TEST(InplaceApplyProximalAdagradTiling, ubsplit_bf16)
{
    auto mc = ComputeMultiCoreSplit(100000, 1, DEFAULT_UB_BLOCK_SIZE);
    int64_t ubFactor = ComputeUbSplit(DEFAULT_UB_SIZE, DT_BF16, mc.blockFactor, DEFAULT_UB_BLOCK_SIZE);
    EXPECT_GT(ubFactor, 0);
    EXPECT_LE(ubFactor, TILE_ELEM_NUM_TARGET);
}

TEST(InplaceApplyProximalAdagradTiling, ubsplit_small_block)
{
    auto mc = ComputeMultiCoreSplit(256, DEFAULT_CORE_NUM, DEFAULT_UB_BLOCK_SIZE);
    int64_t ubFactor = ComputeUbSplit(DEFAULT_UB_SIZE, DT_FLOAT, mc.blockFactor, DEFAULT_UB_BLOCK_SIZE);
    EXPECT_GT(ubFactor, 0);
    EXPECT_LE(ubFactor, mc.blockFactor);
}

TEST(InplaceApplyProximalAdagradTiling, ensure_not_scalar_0d)
{
    Shape scalarShape = {};
    Shape result = EnsureNotScalar(scalarShape);
    EXPECT_EQ(result.size(), 1u);
    EXPECT_EQ(result[0], 1);
}

TEST(InplaceApplyProximalAdagradTiling, ensure_not_scalar_1d)
{
    Shape shape1d = {8};
    Shape result = EnsureNotScalar(shape1d);
    EXPECT_EQ(result.size(), 1u);
    EXPECT_EQ(result[0], 8);
}

TEST(InplaceApplyProximalAdagradTiling, ensure_not_scalar_2d)
{
    Shape shape2d = {4, 4};
    Shape result = EnsureNotScalar(shape2d);
    EXPECT_EQ(result.size(), 2u);
    EXPECT_EQ(result[0], 4);
    EXPECT_EQ(result[1], 4);
}
