/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

#include <cstddef>
#include <iostream>
#include <gtest/gtest.h>
#include "kernel_run_context_facker.h"
#include "platform/platform_infos_def.h"
#include "register/op_impl_registry.h"
#include "exe_graph/runtime/storage_format.h"
#include "exe_graph/runtime/storage_shape.h"
#include "ut_op_util.h"
#include "test_cube_util.h"
#include "../../../../op_kernel/arch35/avg_pool1_d_tiling_data.h"

using namespace ut_util;

class AvgPool1dTiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "AvgPool1dTiling SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "AvgPool1dTiling TearDown" << std::endl; }
};

namespace {
struct AvgPool1DCompileInfo {
} compileInfo;

struct TilingCaseInput {
    std::vector<int64_t> xShape;
    ge::DataType dt;
    int64_t ksize;
    int64_t strides;
    std::vector<int64_t> pads;
    bool ceilMode;
    bool countIncludePad;
};

struct TilingCaseExpect {
    bool expectSuccess;
    int32_t expectCoreNum = 1;
    int64_t expectTotal = 0;
    int64_t expectL = 0;
    int64_t expectLOut = 0;
    int32_t expectKsize = 0;
    int32_t expectStrides = 0;
    int32_t expectPadLeft = 0;
    int32_t expectPadRight = 0;
    int32_t expectCip = 0;
};

static gert::StorageShape MakeStorageShape(const std::vector<int64_t>& dims)
{
    gert::StorageShape s;
    for (auto d : dims) {
        s.MutableOriginShape().AppendDim(d);
        s.MutableStorageShape().AppendDim(d);
    }
    return s;
}

// public tiling execution: set PlatformInfo + TilingParse + TilingContext + call tiling
static void DoTilingCase(const TilingCaseInput& in, const TilingCaseExpect& exp)
{
    // 1. set PlatformInfo
    fe::PlatFormInfos pf;
    std::map<std::string, std::string> soc, ai, intr;
    GetPlatFormInfos(R"({"hardware_info":{"UB_SIZE":253952,"CORE_NUM":64}})", soc, ai, intr);
    pf.Init();

    // 2. TilingParse (set CompileInfo)
    auto opType = std::string("AvgPool1D");
    auto tilingParseFn = gert::OpImplRegistry::GetInstance().GetOpImpl(opType.c_str())->tiling_parse;
    std::string ciStr = R"({"device_id":null})";
    auto kh = gert::KernelRunContextFaker()
                  .KernelIONum(2, 1)
                  .Inputs({const_cast<char*>(ciStr.c_str()), reinterpret_cast<void*>(&pf)})
                  .Outputs({&compileInfo})
                  .Build();
    kh.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->Init();
    kh.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("SoCInfo", soc);
    kh.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("AICoreSpec", ai);
    kh.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetCoreNumByCoreType("AICore");
    kh.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("AICoreintrinsicDtypeMap", intr);
    ASSERT_EQ(tilingParseFn(kh.GetContext<gert::KernelContext>()), ge::GRAPH_SUCCESS);

    // 3. build TilingContext
    gert::StorageShape xS = MakeStorageShape(in.xShape);
    auto yShape = in.xShape;
    // yShape last dim computed inside tiling, use placeholder here
    yShape.back() = exp.expectLOut;
    gert::StorageShape yS = MakeStorageShape(yShape);
    auto param = gert::TilingData::CreateCap(4096);
    auto wsh = gert::ContinuousVector::Create<size_t>(4096);
    auto th = gert::TilingContextFaker()
                  .NodeIoNum(1, 1)
                  .IrInstanceNum({1})
                  .InputShapes({&xS})
                  .OutputShapes({&yS})
                  .NodeAttrs({{"ksize", Ops::NN::AnyValue::CreateFrom<int64_t>(in.ksize)},
                              {"strides", Ops::NN::AnyValue::CreateFrom<int64_t>(in.strides)},
                              {"pads", Ops::NN::AnyValue::CreateFrom<std::vector<int64_t>>(in.pads)},
                              {"ceil_mode", Ops::NN::AnyValue::CreateFrom<bool>(in.ceilMode)},
                              {"count_include_pad", Ops::NN::AnyValue::CreateFrom<bool>(in.countIncludePad)}})
                  .CompileInfo(&compileInfo)
                  .PlatformInfo(reinterpret_cast<char*>(&pf))
                  .NodeInputTd(0, in.dt, ge::FORMAT_ND, ge::FORMAT_ND)
                  .NodeOutputTd(0, in.dt, ge::FORMAT_ND, ge::FORMAT_ND)
                  .TilingData(param.get())
                  .Workspace(reinterpret_cast<gert::ContinuousVector*>(wsh.get()))
                  .Build();
    auto* ctx = th.GetContext<gert::TilingContext>();
    ctx->GetPlatformInfo()->SetPlatformRes("SoCInfo", soc);
    ctx->GetPlatformInfo()->SetPlatformRes("AICoreSpec", ai);
    ctx->GetPlatformInfo()->SetCoreNumByCoreType("AICore");
    ctx->GetPlatformInfo()->SetPlatformRes("AICoreintrinsicDtypeMap", intr);

    // 4. call tiling function
    auto tilingFn = gert::OpImplRegistry::GetInstance().GetOpImpl(opType.c_str())->tiling;
    if (exp.expectSuccess) {
        EXPECT_EQ(tilingFn(ctx), ge::GRAPH_SUCCESS);
        auto* td = ctx->GetTilingData<AvgPool1dTilingData>();
        EXPECT_EQ(td->needCoreNum, exp.expectCoreNum);
        EXPECT_EQ(td->totalOutputElements, exp.expectTotal);
        EXPECT_EQ(td->L, exp.expectL);
        EXPECT_EQ(td->L_out, exp.expectLOut);
        EXPECT_EQ(td->ksize, exp.expectKsize);
        EXPECT_EQ(td->strides, exp.expectStrides);
        EXPECT_EQ(td->pad_left, exp.expectPadLeft);
        EXPECT_EQ(td->pad_right, exp.expectPadRight);
        EXPECT_EQ(td->count_include_pad, exp.expectCip);
    } else {
        EXPECT_NE(tilingFn(ctx), ge::GRAPH_SUCCESS);
    }
}
} // namespace

// Scenario: float16, (1,1,8), ksize=3, strides=2, pads=[1,1], floor mode
// L_out = (8+1+1-3)/2+1 = 4, no ceil correction, totalOutputElements=4, needCoreNum=1
TEST_F(AvgPool1dTiling, avg_pool1_d_fp16_floor_basic)
{
    DoTilingCase({.xShape = {1, 1, 8},
                  .dt = ge::DT_FLOAT16,
                  .ksize = 3,
                  .strides = 2,
                  .pads = {1, 1},
                  .ceilMode = false,
                  .countIncludePad = false},
                 {.expectSuccess = true,
                  .expectTotal = 4,
                  .expectL = 8,
                  .expectLOut = 4,
                  .expectKsize = 3,
                  .expectStrides = 2,
                  .expectPadLeft = 1,
                  .expectPadRight = 1,
                  .expectCip = 0});
}

// Scenario: float32, (2,3,16), ksize=4, strides=1, pads=[2,2], count_include_pad=true
// L_out = (16+2+2-4)/1+1 = 17, totalOutputElements=6*17=102, needCoreNum=1
TEST_F(AvgPool1dTiling, avg_pool1_d_fp32_count_include_pad)
{
    DoTilingCase({.xShape = {2, 3, 16},
                  .dt = ge::DT_FLOAT,
                  .ksize = 4,
                  .strides = 1,
                  .pads = {2, 2},
                  .ceilMode = false,
                  .countIncludePad = true},
                 {.expectSuccess = true,
                  .expectTotal = 102,
                  .expectL = 16,
                  .expectLOut = 17,
                  .expectKsize = 4,
                  .expectStrides = 1,
                  .expectPadLeft = 2,
                  .expectPadRight = 2,
                  .expectCip = 1});
}

// Scenario: float16, ceil_mode=true, (1,2,10), ksize=3, strides=2, pads=[1,1]
// L_out = (10+1+1-3+2-1)/2+1 = 6, totalOutputElements=2*6=12, needCoreNum=1
TEST_F(AvgPool1dTiling, avg_pool1_d_fp16_ceil_mode)
{
    DoTilingCase({.xShape = {1, 2, 10},
                  .dt = ge::DT_FLOAT16,
                  .ksize = 3,
                  .strides = 2,
                  .pads = {1, 1},
                  .ceilMode = true,
                  .countIncludePad = false},
                 {.expectSuccess = true,
                  .expectTotal = 12,
                  .expectL = 10,
                  .expectLOut = 6,
                  .expectKsize = 3,
                  .expectStrides = 2,
                  .expectPadLeft = 1,
                  .expectPadRight = 1,
                  .expectCip = 0});
}

// Scenario: float32, asymmetric padding pads=[0,2], (1,1,7), ksize=3, strides=1
// L_out = (7+0+2-3)/1+1 = 7, no pad_left correction (pad_left=0)
TEST_F(AvgPool1dTiling, avg_pool1_d_fp32_asymmetric_pad)
{
    DoTilingCase({.xShape = {1, 1, 7},
                  .dt = ge::DT_FLOAT,
                  .ksize = 3,
                  .strides = 1,
                  .pads = {0, 2},
                  .ceilMode = false,
                  .countIncludePad = false},
                 {.expectSuccess = true,
                  .expectTotal = 7,
                  .expectL = 7,
                  .expectLOut = 7,
                  .expectKsize = 3,
                  .expectStrides = 1,
                  .expectPadLeft = 0,
                  .expectPadRight = 2,
                  .expectCip = 0});
}

// Scenario: float16, empty tensor L=0, (1,1,0), ksize=3, strides=1, pads=[0,0]
// L_out=0, totalOutputElements=0, needCoreNum=1 (fallback for empty output)
TEST_F(AvgPool1dTiling, avg_pool1_d_fp16_empty_tensor)
{
    DoTilingCase({.xShape = {1, 1, 0},
                  .dt = ge::DT_FLOAT16,
                  .ksize = 3,
                  .strides = 1,
                  .pads = {0, 0},
                  .ceilMode = false,
                  .countIncludePad = false},
                 {.expectSuccess = true,
                  .expectTotal = 0,
                  .expectL = 0,
                  .expectLOut = 0,
                  .expectKsize = 3,
                  .expectStrides = 1,
                  .expectPadLeft = 0,
                  .expectPadRight = 0,
                  .expectCip = 0});
}

// Scenario: 4D input (N,C,H,L), float32, (2,3,4,10), ksize=2, strides=2, pads=[0,0]
// L_out = (10+0+0-2)/2+1 = 5, NC=2*3*4=24, totalOutputElements=24*5=120, needCoreNum=1
TEST_F(AvgPool1dTiling, avg_pool1_d_fp32_4d_input)
{
    DoTilingCase({.xShape = {2, 3, 4, 10},
                  .dt = ge::DT_FLOAT,
                  .ksize = 2,
                  .strides = 2,
                  .pads = {0, 0},
                  .ceilMode = false,
                  .countIncludePad = false},
                 {.expectSuccess = true,
                  .expectTotal = 120,
                  .expectL = 10,
                  .expectLOut = 5,
                  .expectKsize = 2,
                  .expectStrides = 2,
                  .expectPadLeft = 0,
                  .expectPadRight = 0,
                  .expectCip = 0});
}

// Scenario: rank < 3 (1D input), expect tiling to fail
TEST_F(AvgPool1dTiling, avg_pool1_d_rank_lt_3_fail)
{
    DoTilingCase({.xShape = {8},
                  .dt = ge::DT_FLOAT16,
                  .ksize = 3,
                  .strides = 1,
                  .pads = {0, 0},
                  .ceilMode = false,
                  .countIncludePad = false},
                 {.expectSuccess = false, .expectLOut = 0});
}

// Scenario: unsupported dtype (DT_INT32), expect tiling to fail
TEST_F(AvgPool1dTiling, avg_pool1_d_unsupported_dtype_fail)
{
    DoTilingCase({.xShape = {1, 1, 8},
                  .dt = ge::DT_INT32,
                  .ksize = 3,
                  .strides = 2,
                  .pads = {1, 1},
                  .ceilMode = false,
                  .countIncludePad = false},
                 {.expectSuccess = false, .expectLOut = 4});
}

// Scenario: invalid ksize < 1, expect tiling to fail
TEST_F(AvgPool1dTiling, avg_pool1_d_invalid_ksize_fail)
{
    DoTilingCase({.xShape = {1, 1, 8},
                  .dt = ge::DT_FLOAT16,
                  .ksize = 0,
                  .strides = 1,
                  .pads = {0, 0},
                  .ceilMode = false,
                  .countIncludePad = false},
                 {.expectSuccess = false, .expectLOut = 8});
}
