/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include "log/log.h"
#include "util/math_util.h"
#include "util/platform_util.h"
#include "op_host/tiling_util.h"
#include "op_host/tiling_templates_registry.h"
#include "../../op_kernel/arch35/scatter_non_aliasing_add_tiling_data.h"
#include "../../op_kernel/arch35/scatter_non_aliasing_add_tiling_key.h"

#include <cstring>

namespace optiling {

constexpr int64_t PER_CORE_MIN_ELEMENTS = 1024;
constexpr int64_t SLOT_ALIGN = 32;

struct ScatterNonAliasingAddCompileInfo {
    int64_t coreNum;
    uint64_t ubSize;
    uint64_t sysWorkspaceSize;
};

static ge::graphStatus ComputeScatterTilingParams(gert::TilingContext* context, int64_t coreNum, int64_t& totalElements,
                                                  int64_t& totalScatters, int64_t& updateDataNum, int32_t& K,
                                                  int64_t& maxIndice, int64_t* strides, int64_t& perCoreSlots,
                                                  int64_t& needCoreNum, int64_t& perCoreElements)
{
    auto xInput = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, xInput);
    auto indicesInput = context->GetInputShape(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, indicesInput);
    auto xShape = xInput->GetStorageShape();
    auto indicesShape = indicesInput->GetStorageShape();
    int32_t xRank = static_cast<int32_t>(xShape.GetDimNum());
    int32_t indicesRank = static_cast<int32_t>(indicesShape.GetDimNum());

    OP_CHECK_IF(
        indicesRank < 1,
        OP_LOGE_FOR_INVALID_SHAPEDIM_WITH_REASON(context->GetNodeName(), "indices", std::to_string(indicesRank).c_str(),
                                                 "The rank of indices must be >= 1"),
        return ge::GRAPH_FAILED);

    K = static_cast<int32_t>(indicesShape.GetDim(indicesRank - 1));

    OP_CHECK_IF(xRank > MAX_STRIDES,
                OP_LOGE_FOR_INVALID_SHAPEDIM_WITH_REASON(context->GetNodeName(), "x", std::to_string(xRank).c_str(),
                                                         "The rank of x must be <= 8"),
                return ge::GRAPH_FAILED);

    OP_CHECK_IF(K > xRank,
                OP_LOGE_FOR_INVALID_SHAPEDIM_WITH_REASON(context->GetNodeName(), "indices", std::to_string(K).c_str(),
                                                         "The last dim of indices (K) must be <= rank of x"),
                return ge::GRAPH_FAILED);

    auto updatesInput = context->GetInputShape(2);
    OP_CHECK_NULL_WITH_CONTEXT(context, updatesInput);
    auto updatesShape = updatesInput->GetStorageShape();
    int32_t updatesRank = static_cast<int32_t>(updatesShape.GetDimNum());
    int32_t expectedRank = (indicesRank - 1) + (xRank - K);
    bool updatesShapeMismatch = (updatesRank != expectedRank);
    for (int32_t i = 0; !updatesShapeMismatch && i < indicesRank - 1; i++) {
        updatesShapeMismatch = (updatesShape.GetDim(i) != indicesShape.GetDim(i));
    }
    for (int32_t i = 0; !updatesShapeMismatch && i < xRank - K; i++) {
        updatesShapeMismatch = (updatesShape.GetDim((indicesRank - 1) + i) != xShape.GetDim(K + i));
    }
    OP_CHECK_IF(
        updatesShapeMismatch,
        OP_LOGE_FOR_INVALID_SHAPE_WITH_REASON(context->GetNodeName(), "updates", "incorrect",
                                              "updates.shape must be equal to indices.shape[:-1] + x.shape[K:]"),
        return ge::GRAPH_FAILED);
    totalElements = xShape.GetShapeSize();
    totalScatters = 1;
    for (int32_t i = 0; i < indicesRank - 1; i++) {
        totalScatters *= indicesShape.GetDim(i);
    }
    updateDataNum = 1;
    for (int32_t k = K; k < xRank; k++) {
        updateDataNum *= xShape.GetDim(k);
    }
    maxIndice = (updateDataNum > 0) ? (totalElements / updateDataNum) : 0;
    for (int32_t k = 0; k < K && k < MAX_STRIDES; k++) {
        int64_t stride = 1;
        for (int32_t j = k + 1; j < xRank; j++) {
            stride *= xShape.GetDim(j);
        }
        strides[k] = stride;
    }
    perCoreSlots = (maxIndice > 0) ? Ops::Base::CeilDiv(maxIndice, coreNum) : 0;
    int64_t minSlots = (updateDataNum > 0) ? ((PER_CORE_MIN_ELEMENTS + updateDataNum - 1) / updateDataNum) : 1;
    if (perCoreSlots < minSlots) {
        perCoreSlots = minSlots;
    }
    perCoreSlots = Ops::Base::CeilAlign(perCoreSlots, SLOT_ALIGN);
    needCoreNum = (perCoreSlots > 0) ? ((maxIndice + perCoreSlots - 1) / perCoreSlots) : 1;
    needCoreNum = (needCoreNum < 1) ? 1 : needCoreNum;
    perCoreElements = perCoreSlots * updateDataNum;
    auto indicesDesc = context->GetInputDesc(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, indicesDesc);
    auto indicesDtype = indicesDesc->GetDataType();
    uint64_t tilingKey;
    if (indicesDtype == ge::DT_INT32) {
        tilingKey = GET_TPL_TILING_KEY(SCATTER_IDX_INT32);
    } else {
        tilingKey = GET_TPL_TILING_KEY(SCATTER_IDX_INT64);
    }
    context->SetTilingKey(tilingKey);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ScatterNonAliasingAddTilingFunc(gert::TilingContext* context)
{
    auto platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    int64_t coreNum = static_cast<int64_t>(ascendcPlatform.GetCoreNumAiv());
    OP_CHECK_IF(coreNum <= 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    uint64_t ubSize = 0;
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    uint64_t sysWorkspaceSize = ascendcPlatform.GetLibApiWorkSpaceSize();
    int64_t totalElements, totalScatters, updateDataNum, maxIndice;
    int64_t perCoreSlots, needCoreNum, perCoreElements;
    int32_t K;
    int64_t strides[MAX_STRIDES] = {0};
    OP_CHECK_IF(ComputeScatterTilingParams(context, coreNum, totalElements, totalScatters, updateDataNum, K, maxIndice,
                                           strides, perCoreSlots, needCoreNum, perCoreElements) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "ComputeScatterTilingParams failed"), return ge::GRAPH_FAILED);
    auto* tiling = context->GetTilingData<ScatterNonAliasingAddTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(
        memset_s(tiling, sizeof(ScatterNonAliasingAddTilingData), 0, sizeof(ScatterNonAliasingAddTilingData)) != EOK,
        OP_LOGE(context, "memset tiling data error"), return ge::GRAPH_FAILED);
    tiling->totalElements = totalElements;
    tiling->perCoreElements = perCoreElements;
    tiling->totalScatters = totalScatters;
    tiling->updateDataNum = updateDataNum;
    tiling->K = K;
    tiling->reserved = 0;
    tiling->reservedTail = 0;
    for (int32_t k = 0; k < K && k < MAX_STRIDES; k++) {
        tiling->strides[k] = strides[k];
    }
    context->SetBlockDim(static_cast<uint32_t>(needCoreNum));
    size_t* ws = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, ws);
    ws[0] = static_cast<size_t>(sysWorkspaceSize);
    constexpr uint32_t DCACHE_SIZE = 128 * 1024;
    constexpr uint32_t STATIC_UB_ESTIMATE = 0;
    if (ubSize > static_cast<uint64_t>(DCACHE_SIZE) + static_cast<uint64_t>(STATIC_UB_ESTIMATE)) {
        context->SetLocalMemorySize(static_cast<uint32_t>(ubSize - DCACHE_SIZE - STATIC_UB_ESTIMATE));
    }
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForScatterNonAliasingAdd(gert::TilingParseContext* context)
{
    OP_CHECK_NULL_WITH_CONTEXT(context, context);
    auto compileInfo = context->GetCompiledInfo<ScatterNonAliasingAddCompileInfo>();
    OP_CHECK_NULL_WITH_CONTEXT(context, compileInfo);

    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);

    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    compileInfo->coreNum = static_cast<int64_t>(ascendcPlatform.GetCoreNumAiv());
    OP_CHECK_IF(compileInfo->coreNum <= 0, OP_LOGE(context, "Failed to get core num"), return ge::GRAPH_FAILED);

    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, compileInfo->ubSize);
    compileInfo->sysWorkspaceSize = ascendcPlatform.GetLibApiWorkSpaceSize();

    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(ScatterNonAliasingAdd)
    .Tiling(ScatterNonAliasingAddTilingFunc)
    .TilingParse<ScatterNonAliasingAddCompileInfo>(TilingParseForScatterNonAliasingAdd);

} // namespace optiling
