/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file smooth_l1_loss_grad_tiling_arch35.cpp
 * \brief SmoothL1LossGrad Host 侧 Tiling 计算（arch35 / DAV_3510）
 *
 * Tiling 流程：
 *   1. 获取平台信息（ubSize, coreNum；PlatformAscendC，禁止硬编码）
 *   2. 获取 shape / 属性信息（totalLength, dtype, sigma → negSigma=-sigma, recipSigma=1/sigma）
 *   3. 空 Tensor 短路（totalLength=0 → blockNum=0，避免除零；SetBlockDim(1)）
 *   4. 多核切分（coreNum/blockFormer/blockNum 两步，512 对齐后反推 blockNum）
 *   5. UB 切分（byte 量纲 maxElemNum 无 ×8；alignFactor = 256/elemBytes；ubFormer 256B 对齐）
 *
 * elemBytes 由
 *   ge::GetSizeByDataType(dataType) 运行时取（fp16/bf16=2、fp32=4），alignFactor 随之
 *   参数化（256/elemBytes = 128/128/64）；同一份 tiling 逻辑覆盖 2B/4B 两类 UB 对齐结构。
 *
 * 量纲说明：
 *   maxElemNum = (ubSize - extraSize) / bufferDivisor，bufferDivisor = BUFFER_NUM * elemBytes（byte 量纲）。
 *   alignFactor = ALIGN_256 / elemBytes（fp16/bf16 = 128、fp32 = 64）。
 *   extraSize = ALIGN_256（对齐 / 框架预留 256B，规避 InitBuffer 内部对齐开销致 UB 溢出）。
 */

#include "register/op_def_registry.h"
#include "op_common/log/log.h"
#include "op_common/op_host/util/math_util.h"
#include "op_common/op_host/util/platform_util.h"
#include <set>
#include "../../op_kernel/arch35/smooth_l1_loss_grad_tiling_data.h"

namespace optiling {

using Ops::Base::CeilAlign;
using Ops::Base::CeilDiv;

// 常量（禁止硬编码核数）
constexpr uint32_t WS_SYS_SIZE = 0U;                     // workspace 恒为 0
constexpr size_t WORKSPACE_NUM = 1;                      // 即使为 0 也须声明 slot
constexpr int64_t MIN_TILING_BITS_SIZE_PER_CORE = 32768; // 每核 ≥ 4KB，单位 bits
constexpr int64_t ELEM_ALIGN_FACTOR = 512;               // 多核切分元素对齐因子
constexpr int64_t ALIGN_256 = 256;                       // UB 对齐字节数（亦作 extraSize 预留）
constexpr int64_t BUFFER_NUM = 8;                        // double buffer：(3 VECIN + 1 VECOUT) × 2
constexpr float DEFAULT_SIGMA = 1.0f;                    // sigma 默认值
constexpr size_t MAX_SUPPORTED_RANK = 8;                 // README 接口约束：支持 0-8 维

static const gert::Shape g_vec_1_shape = {1};

// rank=0 标量 → {1}（展平 dim0=1）；否则保持原 shape
static inline const gert::Shape EnsureNotScalar(const gert::Shape& in_shape)
{
    if (in_shape.GetDimNum() == 0) {
        return g_vec_1_shape;
    }
    return in_shape;
}

// 获取平台信息（ubSize, coreNum；PlatformAscendC，禁止硬编码）
static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t* ubSize, int64_t* coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    *coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(*coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, *ubSize);
    OP_CHECK_IF(*ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// 获取 shape / dtype / 属性信息
static ge::graphStatus GetShapeAttrsInfo(gert::TilingContext* context, int64_t* totalLength, ge::DataType* dataType,
                                         float* sigma)
{
    // 输入 predict shape → 展平为 totalLength（rank=0 → 1，空 Tensor → 0）
    auto inputPredict = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputPredict);
    OP_CHECK_IF(inputPredict->GetStorageShape().GetDimNum() > MAX_SUPPORTED_RANK,
                OP_LOGE(context, "SmoothL1LossGrad: predict rank %zu exceeds supported range [0, 8]",
                        inputPredict->GetStorageShape().GetDimNum()),
                return ge::GRAPH_FAILED);
    auto predictShape = EnsureNotScalar(inputPredict->GetStorageShape());
    *totalLength = predictShape.GetShapeSize();

    // dtype 校验（全 3 dtype）
    const std::set<ge::DataType> supportedDtype = {ge::DT_FLOAT16, ge::DT_BF16, ge::DT_FLOAT};
    auto inputDesc = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
    const auto predictFormat = inputDesc->GetFormat().GetStorageFormat();
    OP_CHECK_IF(
        predictFormat != ge::FORMAT_ND,
        OP_LOGE(context, "SmoothL1LossGrad: input[0] format %d is unsupported; input name=predict, legal format=ND",
                static_cast<int>(predictFormat)),
        return ge::GRAPH_FAILED);
    *dataType = inputDesc->GetDataType();
    OP_CHECK_IF(supportedDtype.count(*dataType) == 0,
                OP_LOGE(context,
                        "SmoothL1LossGrad: unsupported dtype %d (supports FLOAT16/BF16/FLOAT); input name=predict, "
                        "legal dtypes={FLOAT16,BF16,FLOAT}",
                        static_cast<int>(*dataType)),
                return ge::GRAPH_FAILED);

    // === 三输入 shape/dtype 一致性校验 ===
    // shape 一致性校验（不支持广播）
    auto inputLabel = context->GetInputShape(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputLabel);
    OP_CHECK_IF(inputLabel->GetStorageShape() != inputPredict->GetStorageShape(),
                OP_LOGE(context,
                        "SmoothL1LossGrad: shape mismatch between predict and label; actual predict shape=%s, "
                        "actual label shape=%s, legal relation=label shape must equal predict shape",
                        Ops::Base::ToString(inputPredict->GetStorageShape()).c_str(),
                        Ops::Base::ToString(inputLabel->GetStorageShape()).c_str()),
                return ge::GRAPH_FAILED);

    auto inputDout = context->GetInputShape(2);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDout);
    OP_CHECK_IF(inputDout->GetStorageShape() != inputPredict->GetStorageShape(),
                OP_LOGE(context,
                        "SmoothL1LossGrad: shape mismatch between predict and dout; actual predict shape=%s, actual "
                        "dout shape=%s, legal relation=dout shape must equal predict shape",
                        Ops::Base::ToString(inputPredict->GetStorageShape()).c_str(),
                        Ops::Base::ToString(inputDout->GetStorageShape()).c_str()),
                return ge::GRAPH_FAILED);

    // dtype 一致性校验
    auto labelDesc = context->GetInputDesc(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, labelDesc);
    const auto labelFormat = labelDesc->GetFormat().GetStorageFormat();
    OP_CHECK_IF(
        labelFormat != ge::FORMAT_ND,
        OP_LOGE(context, "SmoothL1LossGrad: input[1] format %d is unsupported; input name=label, legal format=ND",
                static_cast<int>(labelFormat)),
        return ge::GRAPH_FAILED);
    const auto labelDtype = labelDesc->GetDataType();
    OP_CHECK_IF(supportedDtype.count(labelDtype) == 0,
                OP_LOGE(context,
                        "SmoothL1LossGrad: input[1] unsupported dtype %d (supports FLOAT16/BF16/FLOAT); input "
                        "name=label, legal dtypes={FLOAT16,BF16,FLOAT}",
                        static_cast<int>(labelDtype)),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(labelDtype != *dataType,
                OP_LOGE(context,
                        "SmoothL1LossGrad: dtype mismatch between predict and label; actual predict dtype=%d, actual "
                        "label dtype=%d, legal relation=label dtype must equal predict dtype",
                        static_cast<int>(*dataType), static_cast<int>(labelDtype)),
                return ge::GRAPH_FAILED);

    auto doutDesc = context->GetInputDesc(2);
    OP_CHECK_NULL_WITH_CONTEXT(context, doutDesc);
    const auto doutFormat = doutDesc->GetFormat().GetStorageFormat();
    OP_CHECK_IF(
        doutFormat != ge::FORMAT_ND,
        OP_LOGE(context, "SmoothL1LossGrad: input[2] format %d is unsupported; input name=dout, legal format=ND",
                static_cast<int>(doutFormat)),
        return ge::GRAPH_FAILED);
    const auto doutDtype = doutDesc->GetDataType();
    OP_CHECK_IF(supportedDtype.count(doutDtype) == 0,
                OP_LOGE(context,
                        "SmoothL1LossGrad: input[2] unsupported dtype %d (supports FLOAT16/BF16/FLOAT); input "
                        "name=dout, legal dtypes={FLOAT16,BF16,FLOAT}",
                        static_cast<int>(doutDtype)),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(doutDtype != *dataType,
                OP_LOGE(context,
                        "SmoothL1LossGrad: dtype mismatch between predict and dout; actual predict dtype=%d, actual "
                        "dout dtype=%d, legal relation=dout dtype must equal predict dtype",
                        static_cast<int>(*dataType), static_cast<int>(doutDtype)),
                return ge::GRAPH_FAILED);

    auto outputDesc = context->GetOutputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, outputDesc);
    const auto outputFormat = outputDesc->GetFormat().GetStorageFormat();
    OP_CHECK_IF(
        outputFormat != ge::FORMAT_ND,
        OP_LOGE(context, "SmoothL1LossGrad: output[0] format %d is unsupported; output name=gradient, legal format=ND",
                static_cast<int>(outputFormat)),
        return ge::GRAPH_FAILED);

    // 属性 sigma（Float，index 0，默认 1.0）
    const auto* attrs = context->GetAttrs();
    if (attrs != nullptr) {
        const float* sigmaPtr = attrs->GetAttrPointer<float>(0);
        *sigma = (sigmaPtr != nullptr) ? *sigmaPtr : DEFAULT_SIGMA;
    } else {
        *sigma = DEFAULT_SIGMA;
    }

    // sigma > 0 校验
    OP_CHECK_IF(
        *sigma <= 0.0f,
        OP_LOGE(context, "SmoothL1LossGrad: sigma must be > 0, got %f; attribute name=sigma, legal range=(0, +inf)",
                *sigma),
        return ge::GRAPH_FAILED);

    return ge::GRAPH_SUCCESS;
}

// workspace 声明（即使为 0 也必须声明 slot，否则运行时不分配 workspace 指针）
static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    size_t* currentWorkspace = context->GetWorkspaceSizes(WORKSPACE_NUM);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = WS_SYS_SIZE;
    return ge::GRAPH_SUCCESS;
}

// 多核 + UB 切分
static void ComputeTilingParams(int64_t totalLength, ge::DataType dataType, uint64_t ubSize, int64_t availableCoreNum,
                                int64_t* coreNum, int64_t* blockFormer, int64_t* blockNum, int64_t* blockTail,
                                int64_t* ubFormer)
{
    int64_t elemBytes = static_cast<int64_t>(ge::GetSizeByDataType(dataType)); // fp16/bf16 → 2, fp32 → 4
    int64_t minDtypeBits = elemBytes * 8;                                      // fp16/bf16 → 16, fp32 → 32

    // 多核切分（coreNum/blockFormer/blockNum 两步，512 对齐后反推）
    *coreNum = (totalLength * minDtypeBits + MIN_TILING_BITS_SIZE_PER_CORE - 1) / MIN_TILING_BITS_SIZE_PER_CORE;
    *coreNum = std::min(*coreNum, availableCoreNum);
    *blockFormer = CeilAlign(CeilDiv(totalLength, *coreNum), ELEM_ALIGN_FACTOR); // 512 元素对齐
    *blockNum = CeilDiv(totalLength, *blockFormer);                              // 工作核数（恒 ≤ coreNum）
    *blockTail = totalLength - (*blockNum - 1) * *blockFormer;                   // int64 防回绕

    // UB 切分（byte 量纲无 ×8，extraSize=ALIGN_256 预留）
    int64_t bufferDivisor = BUFFER_NUM * elemBytes; // fp16/bf16 → 16, fp32 → 32
    int64_t maxElemNum = (static_cast<int64_t>(ubSize) - ALIGN_256) / bufferDivisor;
    int64_t alignFactor = ALIGN_256 / elemBytes;          // = 256/elemBytes
    *ubFormer = (maxElemNum / alignFactor) * alignFactor; // 256B 对齐
}

static ge::graphStatus SmoothL1LossGradTilingFunc(gert::TilingContext* context)
{
    OP_LOGI(context->GetNodeName(), "Enter SmoothL1LossGradTilingFunc");
    // 1. 平台信息 + shape/dtype/属性 + workspace
    uint64_t ubSize;
    int64_t availableCoreNum;
    OP_CHECK_IF(GetPlatformInfo(context, &ubSize, &availableCoreNum) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetPlatformInfo error"), return ge::GRAPH_FAILED);
    int64_t totalLength;
    ge::DataType dataType;
    float sigma;
    OP_CHECK_IF(GetShapeAttrsInfo(context, &totalLength, &dataType, &sigma) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetShapeAttrsInfo error"), return ge::GRAPH_FAILED);
    OP_CHECK_IF(GetWorkspaceSize(context) != ge::GRAPH_SUCCESS, OP_LOGE(context, "GetWorkspaceSize error"),
                return ge::GRAPH_FAILED);

    // 2. TilingData 初始化 + 属性标量预计算
    SmoothL1LossGradTilingData* tiling = context->GetTilingData<SmoothL1LossGradTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(memset_s(tiling, sizeof(SmoothL1LossGradTilingData), 0, sizeof(SmoothL1LossGradTilingData)) != EOK,
                OP_LOGE(context, "set tiling data error"), return ge::GRAPH_FAILED);
    tiling->totalLength = totalLength;
    tiling->sigma = sigma;
    tiling->negSigma = -sigma;
    tiling->recipSigma = 1.0f / sigma;

    // 3. 空 Tensor 短路（blockNum=0，kernel 守卫 return）
    if (totalLength == 0) {
        context->SetBlockDim(1);
        return ge::GRAPH_SUCCESS;
    }

    // 4. 多核 + UB 切分
    int64_t coreNum, blockFormer, blockNum, blockTail, ubFormer;
    ComputeTilingParams(totalLength, dataType, ubSize, availableCoreNum, &coreNum, &blockFormer, &blockNum, &blockTail,
                        &ubFormer);

    // 5. 填充 TilingData + BlockDim + TilingKey
    tiling->coreNum = static_cast<int32_t>(coreNum);
    tiling->blockFormer = blockFormer;
    tiling->blockNum = blockNum;
    tiling->blockTail = blockTail;
    tiling->ubFormer = ubFormer;
    context->SetBlockDim(static_cast<uint32_t>(blockNum));
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForSmoothL1LossGrad([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

struct SmoothL1LossGradCompileInfo {}; // 必须定义，入图场景依赖

IMPL_OP_OPTILING(SmoothL1LossGrad)
    .Tiling(SmoothL1LossGradTilingFunc)
    .TilingParse<SmoothL1LossGradCompileInfo>(TilingParseForSmoothL1LossGrad);

} // namespace optiling
