/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

/*!
 * \file foreach_mul_list_simt.h
 * \brief SIMT kernel implementation for foreach_mul_list
 */

#ifndef FOREACH_MUL_LIST_SIMT_H
#define FOREACH_MUL_LIST_SIMT_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "foreach_mul_list_tiling_data.h"
#include "foreach_mul_list_tiling_key.h"
#include "kernel_operator_list_tensor_intf.h"
#include "simt_api/asc_simt.h"
#include "simt_api/asc_fp16.h"
#include "simt_api/asc_bf16.h"

namespace NsForeachMulList {

using namespace AscendC;

constexpr uint32_t THREAD_NUM = 512;

enum class ForeachMulListSchMode : int32_t {
    FLOAT = FOREACH_MUL_LIST_TPL_SCH_MODE_FLOAT,
    FLOAT16 = FOREACH_MUL_LIST_TPL_SCH_MODE_FLOAT16,
    BF16 = FOREACH_MUL_LIST_TPL_SCH_MODE_BF16,
    INT32 = FOREACH_MUL_LIST_TPL_SCH_MODE_INT32,
    INT16 = FOREACH_MUL_LIST_TPL_SCH_MODE_INT16,
    INT8 = FOREACH_MUL_LIST_TPL_SCH_MODE_INT8,
    UINT8 = FOREACH_MUL_LIST_TPL_SCH_MODE_UINT8,
};

// ===== float32 VF kernel: direct mul =====
__simt_vf__ __aicore__ LAUNCH_BOUND(THREAD_NUM) inline void ForeachMulListSimtFp32(int64_t count, __gm__ float* x1,
                                                                                   __gm__ float* x2, __gm__ float* y)
{
    for (int64_t idx = static_cast<int64_t>(Simt::GetThreadIdx()); idx < count;
         idx += static_cast<int64_t>(Simt::GetThreadNum())) {
        y[idx] = x1[idx] * x2[idx];
    }
}

// ===== float16 VF kernel: promote to float32 for computation =====
__simt_vf__ __aicore__ LAUNCH_BOUND(THREAD_NUM) inline void ForeachMulListSimtFp16(int64_t count, __gm__ half* x1,
                                                                                   __gm__ half* x2, __gm__ half* y)
{
    for (int64_t idx = static_cast<int64_t>(Simt::GetThreadIdx()); idx < count;
         idx += static_cast<int64_t>(Simt::GetThreadNum())) {
        float val1 = __half2float(x1[idx]);
        float val2 = __half2float(x2[idx]);
        y[idx] = __float2half(val1 * val2);
    }
}

// ===== bfloat16 VF kernel: promote to float32 for computation =====
__simt_vf__ __aicore__ LAUNCH_BOUND(THREAD_NUM) inline void ForeachMulListSimtBf16(int64_t count, __gm__ bfloat16_t* x1,
                                                                                   __gm__ bfloat16_t* x2,
                                                                                   __gm__ bfloat16_t* y)
{
    for (int64_t idx = static_cast<int64_t>(Simt::GetThreadIdx()); idx < count;
         idx += static_cast<int64_t>(Simt::GetThreadNum())) {
        float val1 = __bfloat162float(x1[idx]);
        float val2 = __bfloat162float(x2[idx]);
        y[idx] = __float2bfloat16(val1 * val2);
    }
}

// ===== int32 VF kernel: direct integer mul =====
__simt_vf__ __aicore__ LAUNCH_BOUND(THREAD_NUM) inline void ForeachMulListSimtInt32(int64_t count, __gm__ int32_t* x1,
                                                                                    __gm__ int32_t* x2,
                                                                                    __gm__ int32_t* y)
{
    for (int64_t idx = static_cast<int64_t>(Simt::GetThreadIdx()); idx < count;
         idx += static_cast<int64_t>(Simt::GetThreadNum())) {
        y[idx] = x1[idx] * x2[idx];
    }
}

// ===== int16 VF kernel: direct integer mul =====
__simt_vf__ __aicore__ LAUNCH_BOUND(THREAD_NUM) inline void ForeachMulListSimtInt16(int64_t count, __gm__ int16_t* x1,
                                                                                    __gm__ int16_t* x2,
                                                                                    __gm__ int16_t* y)
{
    for (int64_t idx = static_cast<int64_t>(Simt::GetThreadIdx()); idx < count;
         idx += static_cast<int64_t>(Simt::GetThreadNum())) {
        int32_t product = static_cast<int32_t>(x1[idx]) * static_cast<int32_t>(x2[idx]);
        uint32_t lowHalf = static_cast<uint32_t>(product) & 0xFFFFU;
        int32_t wrappedValue = (lowHalf >= 0x8000U) ? static_cast<int32_t>(lowHalf) - 0x10000 :
                                                      static_cast<int32_t>(lowHalf);
        y[idx] = static_cast<int16_t>(wrappedValue);
    }
}

// ===== int8 VF kernel: direct integer mul =====
__simt_vf__ __aicore__ LAUNCH_BOUND(THREAD_NUM) inline void ForeachMulListSimtInt8(int64_t count, __gm__ int8_t* x1,
                                                                                   __gm__ int8_t* x2, __gm__ int8_t* y)
{
    for (int64_t idx = static_cast<int64_t>(Simt::GetThreadIdx()); idx < count;
         idx += static_cast<int64_t>(Simt::GetThreadNum())) {
        int32_t product = static_cast<int32_t>(x1[idx]) * static_cast<int32_t>(x2[idx]);
        uint32_t lowByte = static_cast<uint32_t>(product) & 0xFFU;
        int32_t wrappedValue = (lowByte >= 0x80U) ? static_cast<int32_t>(lowByte) - 0x100 :
                                                    static_cast<int32_t>(lowByte);
        y[idx] = static_cast<int8_t>(wrappedValue);
    }
}

// ===== uint8 VF kernel: direct integer mul =====
__simt_vf__ __aicore__ LAUNCH_BOUND(THREAD_NUM) inline void ForeachMulListSimtUint8(int64_t count, __gm__ uint8_t* x1,
                                                                                    __gm__ uint8_t* x2,
                                                                                    __gm__ uint8_t* y)
{
    for (int64_t idx = static_cast<int64_t>(Simt::GetThreadIdx()); idx < count;
         idx += static_cast<int64_t>(Simt::GetThreadNum())) {
        y[idx] = static_cast<uint8_t>(x1[idx] * x2[idx]);
    }
}

template <int32_t schMode>
struct ForeachMulListSimtCaller {};

template <>
struct ForeachMulListSimtCaller<FOREACH_MUL_LIST_TPL_SCH_MODE_FLOAT> {
    template <typename T>
    __aicore__ static inline void Call(int64_t cnt, __gm__ T* x1P, __gm__ T* x2P, __gm__ T* yP)
    {
        Simt::VF_CALL<ForeachMulListSimtFp32>(Simt::Dim3(THREAD_NUM), cnt, reinterpret_cast<__gm__ float*>(x1P),
                                              reinterpret_cast<__gm__ float*>(x2P),
                                              reinterpret_cast<__gm__ float*>(yP));
    }
};

template <>
struct ForeachMulListSimtCaller<FOREACH_MUL_LIST_TPL_SCH_MODE_FLOAT16> {
    template <typename T>
    __aicore__ static inline void Call(int64_t cnt, __gm__ T* x1P, __gm__ T* x2P, __gm__ T* yP)
    {
        Simt::VF_CALL<ForeachMulListSimtFp16>(Simt::Dim3(THREAD_NUM), cnt, reinterpret_cast<__gm__ half*>(x1P),
                                              reinterpret_cast<__gm__ half*>(x2P), reinterpret_cast<__gm__ half*>(yP));
    }
};

template <>
struct ForeachMulListSimtCaller<FOREACH_MUL_LIST_TPL_SCH_MODE_BF16> {
    template <typename T>
    __aicore__ static inline void Call(int64_t cnt, __gm__ T* x1P, __gm__ T* x2P, __gm__ T* yP)
    {
        Simt::VF_CALL<ForeachMulListSimtBf16>(Simt::Dim3(THREAD_NUM), cnt, reinterpret_cast<__gm__ bfloat16_t*>(x1P),
                                              reinterpret_cast<__gm__ bfloat16_t*>(x2P),
                                              reinterpret_cast<__gm__ bfloat16_t*>(yP));
    }
};

template <>
struct ForeachMulListSimtCaller<FOREACH_MUL_LIST_TPL_SCH_MODE_INT32> {
    template <typename T>
    __aicore__ static inline void Call(int64_t cnt, __gm__ T* x1P, __gm__ T* x2P, __gm__ T* yP)
    {
        Simt::VF_CALL<ForeachMulListSimtInt32>(Simt::Dim3(THREAD_NUM), cnt, reinterpret_cast<__gm__ int32_t*>(x1P),
                                               reinterpret_cast<__gm__ int32_t*>(x2P),
                                               reinterpret_cast<__gm__ int32_t*>(yP));
    }
};

template <>
struct ForeachMulListSimtCaller<FOREACH_MUL_LIST_TPL_SCH_MODE_INT16> {
    template <typename T>
    __aicore__ static inline void Call(int64_t cnt, __gm__ T* x1P, __gm__ T* x2P, __gm__ T* yP)
    {
        Simt::VF_CALL<ForeachMulListSimtInt16>(Simt::Dim3(THREAD_NUM), cnt, reinterpret_cast<__gm__ int16_t*>(x1P),
                                               reinterpret_cast<__gm__ int16_t*>(x2P),
                                               reinterpret_cast<__gm__ int16_t*>(yP));
    }
};

template <>
struct ForeachMulListSimtCaller<FOREACH_MUL_LIST_TPL_SCH_MODE_INT8> {
    template <typename T>
    __aicore__ static inline void Call(int64_t cnt, __gm__ T* x1P, __gm__ T* x2P, __gm__ T* yP)
    {
        Simt::VF_CALL<ForeachMulListSimtInt8>(Simt::Dim3(THREAD_NUM), cnt, reinterpret_cast<__gm__ int8_t*>(x1P),
                                              reinterpret_cast<__gm__ int8_t*>(x2P),
                                              reinterpret_cast<__gm__ int8_t*>(yP));
    }
};

template <>
struct ForeachMulListSimtCaller<FOREACH_MUL_LIST_TPL_SCH_MODE_UINT8> {
    template <typename T>
    __aicore__ static inline void Call(int64_t cnt, __gm__ T* x1P, __gm__ T* x2P, __gm__ T* yP)
    {
        Simt::VF_CALL<ForeachMulListSimtUint8>(Simt::Dim3(THREAD_NUM), cnt, reinterpret_cast<__gm__ uint8_t*>(x1P),
                                               reinterpret_cast<__gm__ uint8_t*>(x2P),
                                               reinterpret_cast<__gm__ uint8_t*>(yP));
    }
};

// ===== Process: multi-core iterate tensor list =====
template <typename T, int32_t schMode>
__aicore__ inline void Process(GM_ADDR x1, GM_ADDR x2, GM_ADDR y, const ForeachMulListTilingData* tilingData)
{
    // Compute core element range
    int64_t coreStart = static_cast<int64_t>(GetBlockIdx()) * tilingData->perCoreElements;
    int64_t coreEnd = coreStart + tilingData->perCoreElements;
    if (static_cast<int32_t>(GetBlockIdx()) == tilingData->needCoreNum - 1) {
        coreEnd = tilingData->totalElements;
    }
    if (coreStart >= coreEnd) {
        return;
    }

    // Initialize ListTensorDesc for TensorList
    ListTensorDesc x1List(reinterpret_cast<__gm__ void*>(x1));
    ListTensorDesc x2List(reinterpret_cast<__gm__ void*>(x2));
    ListTensorDesc yList(reinterpret_cast<__gm__ void*>(y));

    // Iterate tensors, find overlap with core range, compute
    int64_t tStart = 0;
    for (int32_t t = 0; t < tilingData->tensorNum; t++) {
        int64_t tSize = tilingData->tensorSizes[t];
        int64_t tEnd = tStart + tSize;

        int64_t oS = (coreStart > tStart) ? coreStart : tStart;
        int64_t oE = (coreEnd < tEnd) ? coreEnd : tEnd;

        if (oS < oE) {
            int64_t localOff = oS - tStart;
            int64_t cnt = oE - oS;
            __gm__ T* x1P = x1List.GetDataPtr<T>(t) + localOff;
            __gm__ T* x2P = x2List.GetDataPtr<T>(t) + localOff;
            __gm__ T* yP = yList.GetDataPtr<T>(t) + localOff;

            ForeachMulListSimtCaller<schMode>::Call(cnt, x1P, x2P, yP);
        }
        tStart = tEnd;
    }
}

} // namespace NsForeachMulList
#endif // FOREACH_MUL_LIST_SIMT_H
