/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <iostream>
#include <vector>
#include <gtest/gtest.h>
#include "log/log.h"
#include "kernel_run_context_facker.h"
#include "test_cube_util.h"
#include "exe_graph/runtime/storage_format.h"
#include "exe_graph/runtime/storage_shape.h"
#include "platform/platform_infos_def.h"
#include "ut_op_util.h"

using namespace ut_util;
using namespace std;
using namespace ge;

namespace optiling {
struct Relu6DCompileInfo {};
} // namespace optiling

class Relu6DTilingTest : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "Relu6DTilingTest SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "Relu6DTilingTest TearDown" << std::endl; }
};

static void Relu6DTilingTestCase(std::initializer_list<int64_t> inputShape, ge::DataType dtype, float scale,
                                 ge::graphStatus expectedStatus, ge::Format inputFormat = ge::FORMAT_ND,
                                 ge::Format outputFormat = ge::FORMAT_ND)
{
    gert::StorageShape inputStorageShape = {inputShape, inputShape};
    std::map<std::string, std::string> soc_infos;
    std::map<std::string, std::string> aicore_spec;
    std::map<std::string, std::string> intrinsics;
    std::map<std::string, std::string> soc_version_infos = {{"Short_SoC_version", "Ascend950"}, {"NpuArch", "3510"}};
    std::string compile_info_string = R"({
      "hardware_info": {
        "BT_SIZE": 0, "load3d_constraints": "1",
        "Intrinsic_fix_pipe_l0c2out": false, "Intrinsic_data_move_l12ub": true,
        "Intrinsic_data_move_l0c2ub": true, "Intrinsic_data_move_out2l1_nd2nz": false,
        "UB_SIZE": 245760, "L2_SIZE": 33554432, "L1_SIZE": 524288,
        "L0A_SIZE": 65536, "L0B_SIZE": 65536, "L0C_SIZE": 131072, "CORE_NUM": 64
      }
    })";
    std::string op_type("Relu6D");

    GetPlatFormInfos(compile_info_string.c_str(), soc_infos, aicore_spec, intrinsics);

    fe::PlatFormInfos platform_info;
    platform_info.Init();

    optiling::Relu6DCompileInfo compile_info;

    auto tiling_func = gert::OpImplRegistry::GetInstance().GetOpImpl("Relu6D")->tiling;
    auto tiling_parse_func = gert::OpImplRegistry::GetInstance().GetOpImpl("Relu6D")->tiling_parse;

    auto kernel_holder = gert::KernelRunContextFaker()
                             .KernelIONum(1, 1)
                             .Inputs({const_cast<char*>(compile_info_string.c_str()),
                                      reinterpret_cast<void*>(&platform_info)})
                             .Outputs({&compile_info})
                             .Build();

    ASSERT_TRUE(kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->Init());
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("SoCInfo", soc_infos);
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("AICoreSpec", aicore_spec);
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetCoreNumByCoreType("AICore");
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("AICoreintrinsicDtypeMap",
                                                                                            intrinsics);
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("version",
                                                                                            soc_version_infos);
    ASSERT_EQ(tiling_parse_func(kernel_holder.GetContext<gert::KernelContext>()), ge::GRAPH_SUCCESS);

    auto param = gert::TilingData::CreateCap(4096);
    ASSERT_NE(param, nullptr);
    auto workspace_size_holer = gert::ContinuousVector::Create<size_t>(4096);
    auto ws_size = reinterpret_cast<gert::ContinuousVector*>(workspace_size_holer.get());

    auto holder = gert::TilingContextFaker()
                      .SetOpType(op_type)
                      .NodeIoNum(1, 1)
                      .IrInstanceNum({1})
                      .InputShapes({&inputStorageShape})
                      .OutputShapes({&inputStorageShape})
                      .CompileInfo(&compile_info)
                      .PlatformInfo(reinterpret_cast<char*>(&platform_info))
                      .NodeInputTd(0, dtype, inputFormat, inputFormat)
                      .NodeOutputTd(0, dtype, outputFormat, outputFormat)
                      .NodeAttrs({{"scale", Ops::NN::AnyValue::CreateFrom<float>(scale)}})
                      .TilingData(param.get())
                      .Workspace(ws_size)
                      .Build();
    gert::TilingContext* tiling_context = holder.GetContext<gert::TilingContext>();
    ASSERT_NE(tiling_context->GetPlatformInfo(), nullptr);

    tiling_context->GetPlatformInfo()->SetPlatformRes("SoCInfo", soc_infos);
    tiling_context->GetPlatformInfo()->SetPlatformRes("AICoreSpec", aicore_spec);
    tiling_context->GetPlatformInfo()->SetCoreNumByCoreType("AICore");
    tiling_context->GetPlatformInfo()->SetPlatformRes("AICoreintrinsicDtypeMap", intrinsics);

    EXPECT_EQ(tiling_func(tiling_context), expectedStatus);
}

TEST_F(Relu6DTilingTest, test_tiling_fp16_001)
{
    Relu6DTilingTestCase({1, 64, 2, 64}, ge::DT_FLOAT16, 1.0f, ge::GRAPH_SUCCESS);
}

TEST_F(Relu6DTilingTest, test_tiling_fp32_002)
{
    Relu6DTilingTestCase({1, 64, 2, 64}, ge::DT_FLOAT, 1.0f, ge::GRAPH_SUCCESS);
}

TEST_F(Relu6DTilingTest, test_tiling_int32_003)
{
    Relu6DTilingTestCase({1, 64, 2, 64}, ge::DT_INT32, 1.0f, ge::GRAPH_SUCCESS);
}

TEST_F(Relu6DTilingTest, test_tiling_bf16_004)
{
    Relu6DTilingTestCase({1, 64, 2, 64}, ge::DT_BF16, 1.0f, ge::GRAPH_SUCCESS);
}

TEST_F(Relu6DTilingTest, test_tiling_small_shape_005)
{
    Relu6DTilingTestCase({4, 2}, ge::DT_FLOAT, 1.0f, ge::GRAPH_SUCCESS);
}

TEST_F(Relu6DTilingTest, test_tiling_large_shape_006)
{
    Relu6DTilingTestCase({256, 1024, 64}, ge::DT_FLOAT16, 1.0f, ge::GRAPH_SUCCESS);
}

TEST_F(Relu6DTilingTest, test_tiling_1d_shape_007)
{
    Relu6DTilingTestCase({8192}, ge::DT_FLOAT, 1.0f, ge::GRAPH_SUCCESS);
}

TEST_F(Relu6DTilingTest, test_tiling_scalar_shape_008)
{
    Relu6DTilingTestCase({1}, ge::DT_FLOAT16, 1.0f, ge::GRAPH_SUCCESS);
}

TEST_F(Relu6DTilingTest, test_tiling_empty_tensor_009)
{
    Relu6DTilingTestCase({0, 3, 4}, ge::DT_FLOAT, 1.0f, ge::GRAPH_SUCCESS);
}

TEST_F(Relu6DTilingTest, test_tiling_unsupported_dtype_010)
{
    Relu6DTilingTestCase({1, 64, 2, 64}, ge::DT_INT8, 1.0f, ge::GRAPH_FAILED);
}

TEST_F(Relu6DTilingTest, test_tiling_5d_shape_011)
{
    Relu6DTilingTestCase({1, 2, 3, 4, 5}, ge::DT_BF16, 1.0f, ge::GRAPH_SUCCESS);
}

TEST_F(Relu6DTilingTest, test_tiling_scale_zero_012)
{
    Relu6DTilingTestCase({4, 8}, ge::DT_FLOAT16, 0.0f, ge::GRAPH_SUCCESS);
}

TEST_F(Relu6DTilingTest, test_tiling_scale_half_013)
{
    Relu6DTilingTestCase({4, 8}, ge::DT_FLOAT, 0.5f, ge::GRAPH_SUCCESS);
}

TEST_F(Relu6DTilingTest, test_tiling_scale_negative_014)
{
    Relu6DTilingTestCase({4, 8}, ge::DT_INT32, -1.0f, ge::GRAPH_SUCCESS);
}

TEST_F(Relu6DTilingTest, test_tiling_unsupported_format_015)
{
    Relu6DTilingTestCase({1, 2, 3, 4}, ge::DT_FLOAT, 1.0f, ge::GRAPH_FAILED, ge::FORMAT_NCHW);
}

TEST_F(Relu6DTilingTest, test_tiling_rank_9_016)
{
    Relu6DTilingTestCase({1, 1, 1, 1, 1, 1, 1, 1, 2}, ge::DT_FLOAT16, 1.0f, ge::GRAPH_FAILED);
}

TEST_F(Relu6DTilingTest, test_tiling_unsupported_output_format_017)
{
    Relu6DTilingTestCase({1, 2, 3, 4}, ge::DT_FLOAT, 1.0f, ge::GRAPH_FAILED, ge::FORMAT_ND, ge::FORMAT_NCHW);
}
