/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file test_max_pool_v3_grad_tiling.cpp
 * \brief Tiling UT for max_pool_v3_grad operator (nn 仓 TilingContextFaker 框架, 4D NCHW/NHWC)
 *
 * 测试场景:
 *   - float32 非重叠 NCHW: (1,1,4,4), ksize=[1,1,2,2], strides=[1,1,2,2] -> NON_OVERLAP, TilingKey=0
 *   - float16 重叠 NCHW: (1,1,5,5), ksize=[1,1,3,3], strides=[1,1,1,1], pads=[1,1,1,1] -> OVERLAP, TilingKey=1
 *   - float32 非重叠 NHWC: (1,4,4,1), ksize=[1,2,2,1], strides=[1,2,2,1] -> NON_OVERLAP, TilingKey=0
 *   - 大 shape (int64 范围, 无溢出): 验证 int64_t 字段正确填充
 *   - 乘法溢出拦截: N*C*Ho*Wo 溢出 INT64_MAX -> GRAPH_FAILED
 *   - 动态 shape (-1) 拦截: orig_input/grad 含 -1 -> GRAPH_FAILED
 */

#include <gtest/gtest.h>
#include <iostream>
#include <string>
#include "kernel_run_context_facker.h"
#include "test_cube_util.h"
#include "exe_graph/runtime/storage_format.h"
#include "exe_graph/runtime/storage_shape.h"
#include "platform/platform_infos_def.h"
#include "platform/platform_info.h"
#include "register/op_impl_registry.h"
#include "ut_op_util.h"
#include "../../../../op_kernel/arch35/max_pool_v3_grad_tiling_data.h"

using namespace ut_util;
using namespace std;
using namespace ge;

static void SetAscend950GlobalPlatformInfo()
{
    fe::PlatformInfo platformInfo;
    fe::OptionalInfo optiCompilationInfo;
    platformInfo.soc_info.ai_core_cnt = 64;
    platformInfo.str_info.short_soc_version = "Ascend950";
    optiCompilationInfo.soc_version = "Ascend950";
    fe::PlatformInfoManager::Instance().platform_info_map_["Ascend950"] = platformInfo;
    fe::PlatformInfoManager::Instance().SetOptionalCompilationInfo(optiCompilationInfo);
}

static const MaxPoolV3GradTilingData* ExtractTilingData(gert::TilingContext* ctx)
{
    auto* raw = ctx->GetRawTilingData();
    EXPECT_NE(raw, nullptr);
    EXPECT_GE(raw->GetDataSize(), sizeof(MaxPoolV3GradTilingData));
    return reinterpret_cast<const MaxPoolV3GradTilingData*>(raw->GetData());
}

class MaxPoolV3GradTilingTest : public testing::Test {
protected:
    static void SetUpTestCase()
    {
        std::cout << "MaxPoolV3GradTilingTest SetUp" << std::endl;
        SetAscend950GlobalPlatformInfo();
    }
    static void TearDownTestCase() { std::cout << "MaxPoolV3GradTilingTest TearDown" << std::endl; }
};

static void ExecuteMaxPoolV3GradTestCase(const std::initializer_list<int64_t>& origInputShape,
                                         const std::initializer_list<int64_t>& origOutputShape,
                                         const std::initializer_list<int64_t>& gradShape, ge::DataType dt,
                                         const std::vector<int64_t>& ksize, const std::vector<int64_t>& strides,
                                         const std::string& paddingMode, const std::vector<int64_t>& pads,
                                         const std::string& dataFormat, bool globalPooling, bool ceilMode,
                                         uint64_t expectKey)
{
    string compile_info_string = R"({
        "hardware_info": {"BT_SIZE": 0, "load3d_constraints": "1",
                          "Intrinsic_fix_pipe_l0c2out": false,
                          "Intrinsic_data_move_l12ub": true,
                          "Intrinsic_data_move_l0c2ub": true,
                          "Intrinsic_data_move_out2l1_nd2nz": false,
                          "UB_SIZE": 253952, "L2_SIZE": 33554432, "L1_SIZE": 524288,
                          "L0A_SIZE": 65536, "L0B_SIZE": 65536, "L0C_SIZE": 131072,
                          "CORE_NUM": 64}
                          })";

    map<string, string> soc_infos;
    map<string, string> aicore_spec;
    map<string, string> intrinsics;
    GetPlatFormInfos(compile_info_string.c_str(), soc_infos, aicore_spec, intrinsics);

    std::map<std::string, std::string> soc_version_infos = {{"Short_SoC_version", "Ascend950"}, {"NpuArch", "3510"}};

    fe::PlatFormInfos platform_info;
    platform_info.Init();

    struct MaxPoolV3GradCompileInfo {
    } compile_info;

    std::string op_type("MaxPoolV3Grad");
    ASSERT_NE(gert::OpImplRegistry::GetInstance().GetOpImpl(op_type.c_str()), nullptr);
    auto tiling_func = gert::OpImplRegistry::GetInstance().GetOpImpl(op_type.c_str())->tiling;
    auto tiling_parse_func = gert::OpImplRegistry::GetInstance().GetOpImpl(op_type.c_str())->tiling_parse;

    auto kernel_holder = gert::KernelRunContextFaker()
                             .KernelIONum(2, 1)
                             .Inputs({const_cast<char*>(compile_info_string.c_str()),
                                      reinterpret_cast<void*>(&platform_info)})
                             .Outputs({&compile_info})
                             .Build();

    ASSERT_TRUE(kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->Init());
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("SoCInfo", soc_infos);
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("AICoreSpec", aicore_spec);
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetCoreNumByCoreType("AICore");
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("AICoreintrinsicDtypeMap",
                                                                                            intrinsics);
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("version",
                                                                                            soc_version_infos);

    ASSERT_EQ(tiling_parse_func(kernel_holder.GetContext<gert::KernelContext>()), ge::GRAPH_SUCCESS);

    gert::StorageShape origInputS = {origInputShape, origInputShape};
    gert::StorageShape origOutputS = {origOutputShape, origOutputShape};
    gert::StorageShape gradS = {gradShape, gradShape};
    gert::StorageShape outGradS = {origInputShape, origInputShape};

    auto tiling_data = gert::TilingData::CreateCap(4096);
    auto workspace_size_holer = gert::ContinuousVector::Create<size_t>(4096);
    auto ws_size = reinterpret_cast<gert::ContinuousVector*>(workspace_size_holer.get());

    auto holder = gert::TilingContextFaker()
                      .SetOpType(op_type)
                      .NodeIoNum(3, 1)
                      .IrInstanceNum({1, 1, 1})
                      .InputShapes({&origInputS, &origOutputS, &gradS})
                      .OutputShapes({&outGradS})
                      .CompileInfo(&compile_info)
                      .PlatformInfo(reinterpret_cast<char*>(&platform_info))
                      .NodeInputTd(0, dt, ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeInputTd(1, dt, ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeInputTd(2, dt, ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeOutputTd(0, dt, ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeAttrs({{"ksize", Ops::NN::AnyValue::CreateFrom<std::vector<int64_t>>(ksize)},
                                  {"strides", Ops::NN::AnyValue::CreateFrom<std::vector<int64_t>>(strides)},
                                  {"padding_mode", Ops::NN::AnyValue::CreateFrom<std::string>(paddingMode)},
                                  {"pads", Ops::NN::AnyValue::CreateFrom<std::vector<int64_t>>(pads)},
                                  {"data_format", Ops::NN::AnyValue::CreateFrom<std::string>(dataFormat)},
                                  {"global_pooling", Ops::NN::AnyValue::CreateFrom<bool>(globalPooling)},
                                  {"ceil_mode", Ops::NN::AnyValue::CreateFrom<bool>(ceilMode)}})
                      .TilingData(tiling_data.get())
                      .Workspace(ws_size)
                      .Build();

    gert::TilingContext* tiling_context = holder.GetContext<gert::TilingContext>();
    ASSERT_NE(tiling_context->GetPlatformInfo(), nullptr);
    holder.GetContext<gert::TilingContext>()->GetPlatformInfo()->SetPlatformRes("SoCInfo", soc_infos);
    holder.GetContext<gert::TilingContext>()->GetPlatformInfo()->SetPlatformRes("AICoreSpec", aicore_spec);
    holder.GetContext<gert::TilingContext>()->GetPlatformInfo()->SetCoreNumByCoreType("AICore");
    holder.GetContext<gert::TilingContext>()->GetPlatformInfo()->SetPlatformRes("AICoreintrinsicDtypeMap", intrinsics);
    holder.GetContext<gert::TilingContext>()->GetPlatformInfo()->SetPlatformRes("version", soc_version_infos);

    ASSERT_EQ(tiling_func(tiling_context), ge::GRAPH_SUCCESS);
    ASSERT_EQ(tiling_context->GetTilingKey(), expectKey);

    // 校验 TilingData 字段
    const auto* td = ExtractTilingData(tiling_context);
    ASSERT_NE(td, nullptr);
    int64_t N = origInputShape.begin()[0];
    int64_t C = (dataFormat == "NCHW") ? origInputShape.begin()[1] : origInputShape.begin()[3];
    int64_t H = (dataFormat == "NCHW") ? origInputShape.begin()[2] : origInputShape.begin()[1];
    int64_t W = (dataFormat == "NCHW") ? origInputShape.begin()[3] : origInputShape.begin()[2];
    int64_t kh = (dataFormat == "NCHW") ? ksize[2] : ksize[1];
    int64_t kw = (dataFormat == "NCHW") ? ksize[3] : ksize[2];
    int64_t sh = (dataFormat == "NCHW") ? strides[2] : strides[1];
    int64_t sw = (dataFormat == "NCHW") ? strides[3] : strides[2];
    // 计算 Ho/Wo (与 tiling 逻辑一致: CALCULATED floor 模式)
    int64_t padTop = 0, padLeft = 0;
    if (paddingMode == "CALCULATED") {
        padTop = pads[0];
        padLeft = pads[2];
        int64_t padBottom = pads[1];
        int64_t padRight = pads[3];
        // floor div (向负无穷), 与 tiling FloorDiv 一致
        auto floorDiv = [](int64_t a, int64_t b) -> int64_t {
            int64_t q = a / b;
            int64_t r = a % b;
            return (r != 0 && r < 0) ? (q - 1) : q;
        };
        int64_t Ho = floorDiv(H - kh + padTop + padBottom, sh) + 1;
        int64_t Wo = floorDiv(W - kw + padLeft + padRight, sw) + 1;
        Ho = std::max(Ho, static_cast<int64_t>(0));
        Wo = std::max(Wo, static_cast<int64_t>(0));
        EXPECT_EQ(td->HoWo, Ho * Wo);
        EXPECT_EQ(td->Wo, Wo);
        EXPECT_EQ(td->totalOutputPos, N * C * Ho * Wo);
    } else if (paddingMode == "VALID") {
        int64_t Ho = (H - kh + sh) / sh; // CeilDiv for non-negative
        int64_t Wo = (W - kw + sw) / sw;
        Ho = std::max(Ho, static_cast<int64_t>(0));
        Wo = std::max(Wo, static_cast<int64_t>(0));
        EXPECT_EQ(td->HoWo, Ho * Wo);
        EXPECT_EQ(td->Wo, Wo);
        EXPECT_EQ(td->totalOutputPos, N * C * Ho * Wo);
    }
    EXPECT_EQ(td->C, C);
    EXPECT_EQ(td->HW, H * W);
    EXPECT_EQ(td->W, W);
    EXPECT_EQ(td->kh, kh);
    EXPECT_EQ(td->kw, kw);
    EXPECT_EQ(td->sh, sh);
    EXPECT_EQ(td->sw, sw);
    EXPECT_EQ(td->padTop, padTop);
    EXPECT_EQ(td->padLeft, padLeft);
    EXPECT_EQ(td->totalInputElements, N * C * H * W);
    bool overlap = (sh < kh) || (sw < kw);
    EXPECT_EQ(td->overlapMode, overlap ? 1 : 0);
}

static void ExecuteMaxPoolV3GradTestCaseExpectFail(const std::initializer_list<int64_t>& origInputShape,
                                                   const std::initializer_list<int64_t>& origOutputShape,
                                                   const std::initializer_list<int64_t>& gradShape, ge::DataType dt,
                                                   const std::vector<int64_t>& ksize,
                                                   const std::vector<int64_t>& strides, const std::string& paddingMode,
                                                   const std::vector<int64_t>& pads, const std::string& dataFormat,
                                                   bool globalPooling, bool ceilMode)
{
    string compile_info_string = R"({
        "hardware_info": {"BT_SIZE": 0, "load3d_constraints": "1",
                          "Intrinsic_fix_pipe_l0c2out": false,
                          "Intrinsic_data_move_l12ub": true,
                          "Intrinsic_data_move_l0c2ub": true,
                          "Intrinsic_data_move_out2l1_nd2nz": false,
                          "UB_SIZE": 253952, "L2_SIZE": 33554432, "L1_SIZE": 524288,
                          "L0A_SIZE": 65536, "L0B_SIZE": 65536, "L0C_SIZE": 131072,
                          "CORE_NUM": 64}
                          })";

    map<string, string> soc_infos;
    map<string, string> aicore_spec;
    map<string, string> intrinsics;
    GetPlatFormInfos(compile_info_string.c_str(), soc_infos, aicore_spec, intrinsics);

    std::map<std::string, std::string> soc_version_infos = {{"Short_SoC_version", "Ascend950"}, {"NpuArch", "3510"}};

    fe::PlatFormInfos platform_info;
    platform_info.Init();

    struct MaxPoolV3GradCompileInfo {
    } compile_info;

    std::string op_type("MaxPoolV3Grad");
    ASSERT_NE(gert::OpImplRegistry::GetInstance().GetOpImpl(op_type.c_str()), nullptr);
    auto tiling_func = gert::OpImplRegistry::GetInstance().GetOpImpl(op_type.c_str())->tiling;

    gert::StorageShape origInputS = {origInputShape, origInputShape};
    gert::StorageShape origOutputS = {origOutputShape, origOutputShape};
    gert::StorageShape gradS = {gradShape, gradShape};
    gert::StorageShape outGradS = {origInputShape, origInputShape};

    auto tiling_data = gert::TilingData::CreateCap(4096);
    auto workspace_size_holer = gert::ContinuousVector::Create<size_t>(4096);
    auto ws_size = reinterpret_cast<gert::ContinuousVector*>(workspace_size_holer.get());

    auto holder = gert::TilingContextFaker()
                      .SetOpType(op_type)
                      .NodeIoNum(3, 1)
                      .IrInstanceNum({1, 1, 1})
                      .InputShapes({&origInputS, &origOutputS, &gradS})
                      .OutputShapes({&outGradS})
                      .CompileInfo(&compile_info)
                      .PlatformInfo(reinterpret_cast<char*>(&platform_info))
                      .NodeInputTd(0, dt, ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeInputTd(1, dt, ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeInputTd(2, dt, ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeOutputTd(0, dt, ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeAttrs({{"ksize", Ops::NN::AnyValue::CreateFrom<std::vector<int64_t>>(ksize)},
                                  {"strides", Ops::NN::AnyValue::CreateFrom<std::vector<int64_t>>(strides)},
                                  {"padding_mode", Ops::NN::AnyValue::CreateFrom<std::string>(paddingMode)},
                                  {"pads", Ops::NN::AnyValue::CreateFrom<std::vector<int64_t>>(pads)},
                                  {"data_format", Ops::NN::AnyValue::CreateFrom<std::string>(dataFormat)},
                                  {"global_pooling", Ops::NN::AnyValue::CreateFrom<bool>(globalPooling)},
                                  {"ceil_mode", Ops::NN::AnyValue::CreateFrom<bool>(ceilMode)}})
                      .TilingData(tiling_data.get())
                      .Workspace(ws_size)
                      .Build();

    gert::TilingContext* tiling_context = holder.GetContext<gert::TilingContext>();
    ASSERT_NE(tiling_context->GetPlatformInfo(), nullptr);
    holder.GetContext<gert::TilingContext>()->GetPlatformInfo()->SetPlatformRes("SoCInfo", soc_infos);
    holder.GetContext<gert::TilingContext>()->GetPlatformInfo()->SetPlatformRes("AICoreSpec", aicore_spec);
    holder.GetContext<gert::TilingContext>()->GetPlatformInfo()->SetCoreNumByCoreType("AICore");
    holder.GetContext<gert::TilingContext>()->GetPlatformInfo()->SetPlatformRes("AICoreintrinsicDtypeMap", intrinsics);
    holder.GetContext<gert::TilingContext>()->GetPlatformInfo()->SetPlatformRes("version", soc_version_infos);

    ASSERT_EQ(tiling_func(tiling_context), ge::GRAPH_FAILED);
}

// float32 非重叠: (1,1,4,4), ksize=[1,1,2,2], strides=[1,1,2,2] -> NON_OVERLAP, TilingKey=0
TEST_F(MaxPoolV3GradTilingTest, max_pool_v3_grad_fp32_non_overlap)
{
    ExecuteMaxPoolV3GradTestCase({1, 1, 4, 4}, {1, 1, 2, 2}, {1, 1, 2, 2}, ge::DT_FLOAT, {1, 1, 2, 2}, {1, 1, 2, 2},
                                 "CALCULATED", {0, 0, 0, 0}, "NCHW", false, false, 0);
}

// float16 重叠: (1,1,5,5), ksize=[1,1,3,3], strides=[1,1,1,1], pads=[1,1,1,1] -> OVERLAP_NCHW, TilingKey=2
TEST_F(MaxPoolV3GradTilingTest, max_pool_v3_grad_fp16_overlap)
{
    ExecuteMaxPoolV3GradTestCase({1, 1, 5, 5}, {1, 1, 5, 5}, {1, 1, 5, 5}, ge::DT_FLOAT16, {1, 1, 3, 3}, {1, 1, 1, 1},
                                 "CALCULATED", {1, 1, 1, 1}, "NCHW", false, false, 2);
}

// 动态 shape (-1) 拦截: orig_input 含 -1, tiling 应报错
TEST_F(MaxPoolV3GradTilingTest, max_pool_v3_grad_fail_dynamic_shape_orig_input)
{
    ExecuteMaxPoolV3GradTestCaseExpectFail({1, 1, -1, 4}, {1, 1, 2, 2}, {1, 1, 2, 2}, ge::DT_FLOAT, {1, 1, 2, 2},
                                           {1, 1, 2, 2}, "CALCULATED", {0, 0, 0, 0}, "NCHW", false, false);
}

// 动态 shape (-1) 拦截: grad 含 -1, tiling 应报错
TEST_F(MaxPoolV3GradTilingTest, max_pool_v3_grad_fail_dynamic_shape_grad)
{
    ExecuteMaxPoolV3GradTestCaseExpectFail({1, 1, 4, 4}, {1, 1, 2, 2}, {1, 1, -1, 2}, ge::DT_FLOAT, {1, 1, 2, 2},
                                           {1, 1, 2, 2}, "CALCULATED", {0, 0, 0, 0}, "NCHW", false, false);
}

// float32 非重叠 NHWC: (1,4,4,1), ksize=[1,2,2,1], strides=[1,2,2,1] -> NON_OVERLAP_NHWC, TilingKey=1
TEST_F(MaxPoolV3GradTilingTest, max_pool_v3_grad_fp32_non_overlap_nhwc)
{
    ExecuteMaxPoolV3GradTestCase({1, 4, 4, 1}, {1, 2, 2, 1}, {1, 2, 2, 1}, ge::DT_FLOAT, {1, 2, 2, 1}, {1, 2, 2, 1},
                                 "CALCULATED", {0, 0, 0, 0}, "NHWC", false, false, 1);
}

// 大 shape (int64 范围, 无溢出): H/W 超过 INT32_MAX, 验证 int64_t 字段正确填充不截断
// (1, 1, 50000, 50000), ksize=[1,1,2,2], strides=[1,1,2,2] -> H*W=2.5e9 > INT32_MAX
TEST_F(MaxPoolV3GradTilingTest, max_pool_v3_grad_large_shape_int64)
{
    ExecuteMaxPoolV3GradTestCase({1, 1, 50000, 50000}, {1, 1, 25000, 25000}, {1, 1, 25000, 25000}, ge::DT_FLOAT,
                                 {1, 1, 2, 2}, {1, 1, 2, 2}, "CALCULATED", {0, 0, 0, 0}, "NCHW", false, false, 0);
}

// 乘法溢出拦截: N*C*Ho*Wo 溢出 INT64_MAX -> GRAPH_FAILED
// 取 C=3037000500, H=W=2, ksize=1, stride=1 -> Ho=Wo=2, HoWo=4
// N*C*HoWo = 1*3037000500*4 = 12148000200 (不溢出), 但 C*HoWo 在 nc*hoWo 步骤:
// 取 C=3037000500, Ho=Wo=3037000500 -> C*HoWo 溢出 INT64_MAX
// 用 H=W=3037000500, kh=kw=1, sh=sw=1 -> Ho=Wo=3037000500
TEST_F(MaxPoolV3GradTilingTest, max_pool_v3_grad_fail_mul_overflow)
{
    int64_t big = 3037000500LL; // big^2 > INT64_MAX
    // N=1, C=1, H=W=big, kh=kw=1, sh=sw=1 -> Ho=Wo=big, HoWo=big^2 > INT64_MAX
    ExecuteMaxPoolV3GradTestCaseExpectFail({1, 1, big, big}, {1, 1, big, big}, {1, 1, big, big}, ge::DT_FLOAT,
                                           {1, 1, 1, 1}, {1, 1, 1, 1}, "CALCULATED", {0, 0, 0, 0}, "NCHW", false,
                                           false);
}
