/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

/*!
 * \file avg_pool1_d_tiling.cpp
 * \brief Tiling implementation for avg_pool1_d (MDE §3.2)
 */
#include "log/log.h"
#include "platform/platform_ascendc.h"
#include "op_host/tiling_util.h"
#include "op_host/tiling_templates_registry.h"
#include "../../op_kernel/arch35/avg_pool1_d_tiling_data.h"
#include "../../op_kernel/arch35/avg_pool1_d_tiling_key.h"
#include <string>

namespace optiling {

// ══ 命名常量（SE §2.2）════
constexpr int32_t K_X_IDX = 0;
constexpr int64_t MIN_RANK = 3;     // SE §5.4: x rank >= 3 (3D 输入 (N, C, L))
constexpr int64_t MAX_RANK = 8;     // ND 格式维度上限 8D
constexpr size_t PAD_LIST_SIZE = 2; // SE §2.4: pads 长度必须为 2

// ══ 常量定义（MDE §3.2）════
constexpr int64_t PER_CORE_MIN = 1024;
constexpr uint32_t DCACHE_SIZE = 32 * 1024;
constexpr uint32_t STATIC_UB_ESTIMATE = 0;

struct AvgPool1DCompileInfo {};

// ══ ValidateDtype（SE §2.2 Dtype 列 / §5.3 / §6.3）══
static ge::graphStatus ValidateDtype(gert::TilingContext* context)
{
    auto inputDesc = context->GetInputDesc(K_X_IDX);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
    auto dtype = inputDesc->GetDataType();
    // SE §2.2: x dtype ∈ {float16, float32}
    OP_CHECK_IF(dtype != ge::DT_FLOAT16 && dtype != ge::DT_FLOAT,
                OP_LOGE_FOR_INVALID_DTYPE_WITH_REASON(context->GetNodeName(), "x", Ops::Base::ToString(dtype).c_str(),
                                                      "dtype must be float16 or float32"),
                return ge::GRAPH_FAILED);
    // SE §5.3: format must be ND
    auto format = inputDesc->GetStorageFormat();
    OP_CHECK_IF(format != ge::FORMAT_ND,
                OP_LOGE_FOR_INVALID_DTYPE_WITH_REASON(context->GetNodeName(), "x", Ops::Base::ToString(format).c_str(),
                                                      "format must be ND"),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// ══ ValidateShape（SE §5.4 ND改造: rank >= 3 / §6.3 L >= 0）══
static ge::graphStatus ValidateShape(gert::TilingContext* context)
{
    auto xShape = context->GetInputShape(K_X_IDX);
    OP_CHECK_NULL_WITH_CONTEXT(context, xShape);
    auto storageShape = xShape->GetStorageShape();
    int64_t dimNum = static_cast<int64_t>(storageShape.GetDimNum());
    // SE §5.4: x rank >= 3 (3D 输入 (N, C, L))
    OP_CHECK_IF(dimNum < MIN_RANK,
                OP_LOGE_FOR_INVALID_SHAPEDIMS_WITH_REASON(context->GetNodeName(), "x", std::to_string(dimNum).c_str(),
                                                          "rank must be >= 3"),
                return ge::GRAPH_FAILED);
    // ND 格式维度上限 8D
    OP_CHECK_IF(dimNum > MAX_RANK,
                OP_LOGE_FOR_INVALID_SHAPEDIMS_WITH_REASON(context->GetNodeName(), "x", std::to_string(dimNum).c_str(),
                                                          "rank must be <= 8 for ND format"),
                return ge::GRAPH_FAILED);
    // SE §6.3: L >= 0（空 tensor L=0 允许返回空输出，L < 0 需拦截）
    int64_t L = storageShape.GetDim(static_cast<size_t>(dimNum - 1));
    OP_CHECK_IF(L < 0,
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "L", std::to_string(L).c_str(),
                                                      "L must be >= 0, L=0 is allowed for empty tensor"),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// ══ ValidateAttr（SE §2.4 算子属性）══
static ge::graphStatus ValidateAttr(gert::TilingContext* context)
{
    auto attrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, attrs);

    const auto* ksizePtr = attrs->GetAttrPointer<int64_t>(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, ksizePtr);
    // SE §2.4: ksize >= 1
    OP_CHECK_IF(*ksizePtr < 1,
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "ksize", std::to_string(*ksizePtr).c_str(), ">= 1"),
                return ge::GRAPH_FAILED);

    const auto* stridesPtr = attrs->GetAttrPointer<int64_t>(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, stridesPtr);
    // SE §2.4: strides >= 1（stride=0 报错）
    OP_CHECK_IF(
        *stridesPtr < 1,
        OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "strides", std::to_string(*stridesPtr).c_str(), ">= 1"),
        return ge::GRAPH_FAILED);

    const auto* padsVec = attrs->GetAttrPointer<gert::ContinuousVector>(2);
    OP_CHECK_NULL_WITH_CONTEXT(context, padsVec);
    // SE §2.4: pads 长度必须为 2
    OP_CHECK_IF(
        padsVec->GetSize() != PAD_LIST_SIZE,
        OP_LOGE_FOR_INVALID_LISTSIZE(context->GetNodeName(), "pads", std::to_string(padsVec->GetSize()).c_str(), "2"),
        return ge::GRAPH_FAILED);
    // SE §2.4: pads 元素 >= 0
    const int64_t* pads = static_cast<const int64_t*>(padsVec->GetData());
    OP_CHECK_NULL_WITH_CONTEXT(context, pads);
    OP_CHECK_IF(pads[0] < 0 || pads[1] < 0,
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(
                    context->GetNodeName(), "pads",
                    ("[" + std::to_string(pads[0]) + ", " + std::to_string(pads[1]) + "]").c_str(),
                    "pads elements must be >= 0"),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// ══ ValidateInputs 调度器 ══
static ge::graphStatus ValidateInputs(gert::TilingContext* context)
{
    // 子函数内已有具体的 OP_LOGE_FOR_INVALID_* 错误信息，此处不再重复打印
    OP_CHECK_IF(ValidateDtype(context) != ge::GRAPH_SUCCESS, (void)0, return ge::GRAPH_FAILED);
    OP_CHECK_IF(ValidateShape(context) != ge::GRAPH_SUCCESS, (void)0, return ge::GRAPH_FAILED);
    OP_CHECK_IF(ValidateAttr(context) != ge::GRAPH_SUCCESS, (void)0, return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// ══ DFX: 打印 TilingData 全部标量字段（仅 Debug 构建生效）══
static void DumpTilingData(gert::TilingContext* context, const AvgPool1dTilingData* tiling)
{
    OP_LOGD(context,
            "AvgPool1dTilingData: needCoreNum=%d, totalOutputElements=%ld, L=%ld, L_out=%ld, "
            "ksize=%d, strides=%d, pad_left=%d, pad_right=%d, count_include_pad=%d",
            tiling->needCoreNum, tiling->totalOutputElements, tiling->L, tiling->L_out, tiling->ksize, tiling->strides,
            tiling->pad_left, tiling->pad_right, tiling->count_include_pad);
}

// ══ 获取平台信息 ══
static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t& ubSize, int64_t& coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_IF(platformInfoPtr == nullptr,
                OP_LOGE_FOR_INVALID_CONFIG_WITH_REASON(context->GetNodeName(), "tiling", "platform_info", "null",
                                                       "fail to get platform info"),
                return ge::GRAPH_FAILED);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0,
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "coreNum", std::to_string(coreNum).c_str(), "> 0"),
                return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0,
                OP_LOGE_FOR_INVALID_CONFIG_WITH_REASON(context->GetNodeName(), "tiling", "ubSize", "0", "ubSize is 0"),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// ══ 计算 L_out（MDE §3.2 / SE §6.4）══
static int64_t ComputeLOut(int64_t L, int64_t ksize, int64_t strides, int64_t padLeft, int64_t padRight, bool ceilMode)
{
    if (L == 0) {
        return 0;
    }
    int64_t LOut;
    if (ceilMode) {
        LOut = (L + padLeft + padRight - ksize + strides - 1) / strides + 1;
    } else {
        LOut = (L + padLeft + padRight - ksize) / strides + 1;
    }
    if (padLeft > 0 && (LOut - 1) * strides >= L + padLeft) {
        LOut -= 1;
    }
    if (LOut < 0) {
        LOut = 0;
    }
    return LOut;
}

// ══ 解析 shape 和属性，填充 TilingData ══
static ge::graphStatus ParseShapeAndAttrs(gert::TilingContext* context, AvgPool1dTilingData* tiling)
{
    auto xShape = context->GetInputShape(K_X_IDX);
    OP_CHECK_NULL_WITH_CONTEXT(context, xShape);
    auto storageShape = xShape->GetStorageShape();
    int64_t dimNum = static_cast<int64_t>(storageShape.GetDimNum());

    // L = 最后一维
    int64_t L = storageShape.GetDim(static_cast<size_t>(dimNum - 1));
    tiling->L = L;

    // NC = 前面所有维度的乘积
    int64_t nc = 1;
    for (int64_t i = 0; i < dimNum - 1; i++) {
        nc *= storageShape.GetDim(static_cast<size_t>(i));
    }

    // 读取属性
    auto attrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, attrs);
    int64_t ksize = *attrs->GetAttrPointer<int64_t>(0);
    int64_t strides = *attrs->GetAttrPointer<int64_t>(1);
    const auto* padsVec = attrs->GetAttrPointer<gert::ContinuousVector>(2);
    OP_CHECK_NULL_WITH_CONTEXT(context, padsVec);
    const int64_t* pads = static_cast<const int64_t*>(padsVec->GetData());
    OP_CHECK_NULL_WITH_CONTEXT(context, pads);
    int64_t padLeft = pads[0];
    int64_t padRight = pads[1];

    const auto* ceilModePtr = attrs->GetAttrPointer<bool>(3);
    bool ceilMode = (ceilModePtr != nullptr) ? *ceilModePtr : false;

    const auto* cipPtr = attrs->GetAttrPointer<bool>(4);
    bool countIncludePad = (cipPtr != nullptr) ? *cipPtr : false;

    // 计算 L_out
    int64_t LOut = ComputeLOut(L, ksize, strides, padLeft, padRight, ceilMode);
    tiling->L_out = LOut;
    tiling->totalOutputElements = nc * LOut;
    tiling->ksize = static_cast<int32_t>(ksize);
    tiling->strides = static_cast<int32_t>(strides);
    tiling->pad_left = static_cast<int32_t>(padLeft);
    tiling->pad_right = static_cast<int32_t>(padRight);
    tiling->count_include_pad = countIncludePad ? 1 : 0;
    return ge::GRAPH_SUCCESS;
}

// ══ 核数切分（MDE §2.1 两步法）══
static void ComputeCoreSplit(AvgPool1dTilingData* tiling, int64_t coreNum)
{
    int64_t totalOutputElements = tiling->totalOutputElements;
    if (totalOutputElements <= 0) {
        tiling->needCoreNum = 1;
        return;
    }
    int64_t perCoreElements = (totalOutputElements + coreNum - 1) / coreNum;
    if (perCoreElements < PER_CORE_MIN) {
        perCoreElements = PER_CORE_MIN;
    }
    int64_t needCoreNum = (totalOutputElements + perCoreElements - 1) / perCoreElements;
    if (needCoreNum > coreNum) {
        needCoreNum = coreNum;
    }
    if (needCoreNum <= 0) {
        needCoreNum = 1;
    }
    tiling->needCoreNum = static_cast<int32_t>(needCoreNum);
}

// ══ Tiling 主函数 ══
static ge::graphStatus AvgPool1DTilingFunc(gert::TilingContext* context)
{
    OP_LOGI(context->GetNodeName(), "AvgPool1DTiling is running");

    // 1. 校验输入（子函数内已有具体的 OP_LOGE_FOR_INVALID_* 错误信息）
    OP_CHECK_IF(ValidateInputs(context) != ge::GRAPH_SUCCESS, (void)0, return ge::GRAPH_FAILED);

    // 2. 获取平台信息（子函数内已有具体的 OP_LOGE_FOR_INVALID_* 错误信息）
    uint64_t ubSize = 0;
    int64_t coreNum = 0;
    OP_CHECK_IF(GetPlatformInfo(context, ubSize, coreNum) != ge::GRAPH_SUCCESS, (void)0, return ge::GRAPH_FAILED);

    // 3. 获取 TilingData 并清零
    AvgPool1dTilingData* tiling = context->GetTilingData<AvgPool1dTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(memset_s(tiling, sizeof(AvgPool1dTilingData), 0, sizeof(AvgPool1dTilingData)) != EOK,
                OP_LOGE_FOR_INVALID_CONFIG_WITH_REASON(context->GetNodeName(), "tiling", "memset_s", "failed",
                                                       "set tiling data error"),
                return ge::GRAPH_FAILED);

    // 4. 解析 shape 和属性
    OP_CHECK_IF(ParseShapeAndAttrs(context, tiling) != ge::GRAPH_SUCCESS, (void)0, return ge::GRAPH_FAILED);

    // 5. 核数切分
    ComputeCoreSplit(tiling, coreNum);

    // 6. DFX 日志
    DumpTilingData(context, tiling);

    // 7. workspace 分配（仅系统 workspace，无用户 workspace）
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(context->GetPlatformInfo());
    uint64_t sysWorkspaceSize = ascendcPlatform.GetLibApiWorkSpaceSize();
    size_t* currentWorkspace = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = static_cast<size_t>(sysWorkspaceSize);

    // 8. 设置 BlockDim、LocalMemory、TilingKey
    context->SetBlockDim(tiling->needCoreNum);
    OP_CHECK_IF(ubSize <= DCACHE_SIZE + STATIC_UB_ESTIMATE,
                OP_LOGE_FOR_INVALID_CONFIG_WITH_REASON(context->GetNodeName(), "tiling", "ubSize",
                                                       std::to_string(ubSize).c_str(), "ubSize too small"),
                return ge::GRAPH_FAILED);
    context->SetLocalMemorySize(static_cast<uint32_t>(ubSize - DCACHE_SIZE - STATIC_UB_ESTIMATE));
    context->SetTilingKey(GET_TPL_TILING_KEY(static_cast<uint64_t>(AVG_POOL1D_SCH_MODE_DEFAULT)));

    OP_LOGI(context->GetNodeName(), "AvgPool1DTiling done, needCoreNum=%d, totalOutputElements=%ld, L_out=%ld",
            tiling->needCoreNum, tiling->totalOutputElements, tiling->L_out);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForAvgPool1D([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(AvgPool1D).Tiling(AvgPool1DTilingFunc).TilingParse<AvgPool1DCompileInfo>(TilingParseForAvgPool1D);

} // namespace optiling
