/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file dilation2_d_proto.h
 * \brief operator proto definition for dilation2_d
 */
#ifndef OPS_OP_PROTO_INC_DILATION2D_H_
#define OPS_OP_PROTO_INC_DILATION2D_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
 *@brief Computes morphological dilation 2D.
 *@par Inputs:
 *Two inputs, including:
 * @li x: A 4D Tensor (NHWC or NCHW). Must be one of the following types: float16, float32, float64, int8, int16, int32,
 int64, uint8, uint16.
 * @li filter: A 3D Tensor (fH, fW, C). Must be the same type as x. \n

 *@par Outputs:
 *y: A 4D Tensor (NHWC or NCHW). Must be the same type as x.
 *
 *@par Attributes:
 * @li strides: Required. ListInt. 4 integers, [stride_n, stride_h, stride_w, stride_c].
 * @li rates: Required. ListInt. 4 integers, [rate_n, rate_h, rate_w, rate_c].
 * @li padding_mode: Optional. String. Default "SAME". One of "SAME", "VALID".
 * @li pads: Optional. ListInt. Default {0,0,0,0}.
 * @li ceil_mode: Optional. Bool. Default false.
 * @li data_format: Optional. String. Default "NHWC". One of "NHWC", "NCHW".
 *
 *@par Third-party framework compatibility
 *Compatible with the TensorFlow operator Dilation2D.
 */
#ifndef OPS_PROTO_DEF_DILATION2D
#define OPS_PROTO_DEF_DILATION2D
REG_OP(Dilation2D)
    .INPUT(x, TensorType({DT_FLOAT16, DT_FLOAT, DT_DOUBLE, DT_INT32, DT_INT64, DT_UINT8, DT_INT16, DT_INT8, DT_UINT16}))
    .INPUT(filter,
           TensorType({DT_FLOAT16, DT_FLOAT, DT_DOUBLE, DT_INT32, DT_INT64, DT_UINT8, DT_INT16, DT_INT8, DT_UINT16}))
    .OUTPUT(y,
            TensorType({DT_FLOAT16, DT_FLOAT, DT_DOUBLE, DT_INT32, DT_INT64, DT_UINT8, DT_INT16, DT_INT8, DT_UINT16}))
    .REQUIRED_ATTR(strides, ListInt)
    .REQUIRED_ATTR(rates, ListInt)
    .ATTR(padding_mode, String, "SAME")
    .ATTR(pads, ListInt, {0, 0, 0, 0})
    .ATTR(ceil_mode, Bool, false)
    .ATTR(data_format, String, "NHWC")
    .OP_END_FACTORY_REG(Dilation2D)
#endif
} // namespace ge

#endif // OPS_OP_PROTO_INC_DILATION2D_H_
